/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminAssignPermissions } from "../funcs/adminAssignPermissions.js";
import { adminCreateUserInvitation } from "../funcs/adminCreateUserInvitation.js";
import { adminGetOne } from "../funcs/adminGetOne.js";
import { adminGetUserByToken } from "../funcs/adminGetUserByToken.js";
import { adminRemoveUser } from "../funcs/adminRemoveUser.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Admin extends ClientSDK {
  async getOne(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(adminGetOne(
      this,
      options,
    ));
  }

  async createUserInvitation(
    request: operations.AdminCreateUserInvitationRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(adminCreateUserInvitation(
      this,
      request,
      options,
    ));
  }

  async removeUser(
    request: operations.AdminRemoveUserRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(adminRemoveUser(
      this,
      request,
      options,
    ));
  }

  async getUserByToken(
    request: operations.AdminGetUserByTokenRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(adminGetUserByToken(
      this,
      request,
      options,
    ));
  }

  async assignPermissions(
    request: operations.AdminAssignPermissionsRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(adminAssignPermissions(
      this,
      request,
      options,
    ));
  }
}
