/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationCleanQueues } from "../funcs/applicationCleanQueues.js";
import { applicationCreate } from "../funcs/applicationCreate.js";
import { applicationDelete } from "../funcs/applicationDelete.js";
import { applicationDeploy } from "../funcs/applicationDeploy.js";
import { applicationGetOne } from "../funcs/applicationGetOne.js";
import { applicationMarkRunning } from "../funcs/applicationMarkRunning.js";
import { applicationReadAppMonitoring } from "../funcs/applicationReadAppMonitoring.js";
import { applicationReadTraefikConfig } from "../funcs/applicationReadTraefikConfig.js";
import { applicationRedeploy } from "../funcs/applicationRedeploy.js";
import { applicationRefreshToken } from "../funcs/applicationRefreshToken.js";
import { applicationReload } from "../funcs/applicationReload.js";
import { applicationSaveBitbucketProvider } from "../funcs/applicationSaveBitbucketProvider.js";
import { applicationSaveBuildType } from "../funcs/applicationSaveBuildType.js";
import { applicationSaveDockerProvider } from "../funcs/applicationSaveDockerProvider.js";
import { applicationSaveEnvironment } from "../funcs/applicationSaveEnvironment.js";
import { applicationSaveGithubProvider } from "../funcs/applicationSaveGithubProvider.js";
import { applicationSaveGitlabProvider } from "../funcs/applicationSaveGitlabProvider.js";
import { applicationSaveGitProdiver } from "../funcs/applicationSaveGitProdiver.js";
import { applicationStart } from "../funcs/applicationStart.js";
import { applicationStop } from "../funcs/applicationStop.js";
import { applicationUpdate } from "../funcs/applicationUpdate.js";
import { applicationUpdateTraefikConfig } from "../funcs/applicationUpdateTraefikConfig.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Application extends ClientSDK {
  async create(
    request: operations.ApplicationCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationCreate(
      this,
      request,
      options,
    ));
  }

  async getOne(
    request: operations.ApplicationOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationGetOne(
      this,
      request,
      options,
    ));
  }

  async reload(
    request: operations.ApplicationReloadRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationReload(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.ApplicationDeleteRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationDelete(
      this,
      request,
      options,
    ));
  }

  async stop(
    request: operations.ApplicationStopRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationStop(
      this,
      request,
      options,
    ));
  }

  async start(
    request: operations.ApplicationStartRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationStart(
      this,
      request,
      options,
    ));
  }

  async redeploy(
    request: operations.ApplicationRedeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationRedeploy(
      this,
      request,
      options,
    ));
  }

  async saveEnvironment(
    request: operations.ApplicationSaveEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveEnvironment(
      this,
      request,
      options,
    ));
  }

  async saveBuildType(
    request: operations.ApplicationSaveBuildTypeRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveBuildType(
      this,
      request,
      options,
    ));
  }

  async saveGithubProvider(
    request: operations.ApplicationSaveGithubProviderRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveGithubProvider(
      this,
      request,
      options,
    ));
  }

  async saveGitlabProvider(
    request: operations.ApplicationSaveGitlabProviderRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveGitlabProvider(
      this,
      request,
      options,
    ));
  }

  async saveBitbucketProvider(
    request: operations.ApplicationSaveBitbucketProviderRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveBitbucketProvider(
      this,
      request,
      options,
    ));
  }

  async saveDockerProvider(
    request: operations.ApplicationSaveDockerProviderRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveDockerProvider(
      this,
      request,
      options,
    ));
  }

  async saveGitProdiver(
    request: operations.ApplicationSaveGitProdiverRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationSaveGitProdiver(
      this,
      request,
      options,
    ));
  }

  async markRunning(
    request: operations.ApplicationMarkRunningRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationMarkRunning(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.ApplicationUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationUpdate(
      this,
      request,
      options,
    ));
  }

  async refreshToken(
    request: operations.ApplicationRefreshTokenRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationRefreshToken(
      this,
      request,
      options,
    ));
  }

  async deploy(
    request: operations.ApplicationDeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationDeploy(
      this,
      request,
      options,
    ));
  }

  async cleanQueues(
    request: operations.ApplicationCleanQueuesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationCleanQueues(
      this,
      request,
      options,
    ));
  }

  async readTraefikConfig(
    request: operations.ApplicationReadTraefikConfigRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationReadTraefikConfig(
      this,
      request,
      options,
    ));
  }

  async updateTraefikConfig(
    request: operations.ApplicationUpdateTraefikConfigRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationUpdateTraefikConfig(
      this,
      request,
      options,
    ));
  }

  async readAppMonitoring(
    request: operations.ApplicationReadAppMonitoringRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(applicationReadAppMonitoring(
      this,
      request,
      options,
    ));
  }
}
