/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authConfirmEmail } from "../funcs/authConfirmEmail.js";
import { authCreateAdmin } from "../funcs/authCreateAdmin.js";
import { authCreateUser } from "../funcs/authCreateUser.js";
import { authDisable2FA } from "../funcs/authDisable2FA.js";
import { authGenerate2FASecret } from "../funcs/authGenerate2FASecret.js";
import { authGenerateToken } from "../funcs/authGenerateToken.js";
import { authGet } from "../funcs/authGet.js";
import { authGetOne } from "../funcs/authGetOne.js";
import { authLogin } from "../funcs/authLogin.js";
import { authLogout } from "../funcs/authLogout.js";
import { authResetPassword } from "../funcs/authResetPassword.js";
import { authSendResetPasswordEmail } from "../funcs/authSendResetPasswordEmail.js";
import { authUpdate } from "../funcs/authUpdate.js";
import { authVerify2faSetup } from "../funcs/authVerify2faSetup.js";
import { authVerifyLogin2FA } from "../funcs/authVerifyLogin2FA.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  async createAdmin(
    request: operations.AuthCreateAdminRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authCreateAdmin(
      this,
      request,
      options,
    ));
  }

  async createUser(
    request: operations.AuthCreateUserRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authCreateUser(
      this,
      request,
      options,
    ));
  }

  async login(
    request: operations.AuthLoginRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authLogin(
      this,
      request,
      options,
    ));
  }

  async getOne(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authGetOne(
      this,
      options,
    ));
  }

  async logout(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authLogout(
      this,
      options,
    ));
  }

  async update(
    request: operations.AuthUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authUpdate(
      this,
      request,
      options,
    ));
  }

  async generateToken(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authGenerateToken(
      this,
      options,
    ));
  }

  async get(
    request: operations.AuthOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authGet(
      this,
      request,
      options,
    ));
  }

  async generate2FASecret(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authGenerate2FASecret(
      this,
      options,
    ));
  }

  async verify2faSetup(
    request: operations.AuthVerify2FASetupRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authVerify2faSetup(
      this,
      request,
      options,
    ));
  }

  async verifyLogin2FA(
    request: operations.AuthVerifyLogin2FARequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authVerifyLogin2FA(
      this,
      request,
      options,
    ));
  }

  async disable2FA(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authDisable2FA(
      this,
      options,
    ));
  }

  async sendResetPasswordEmail(
    request: operations.AuthSendResetPasswordEmailRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authSendResetPasswordEmail(
      this,
      request,
      options,
    ));
  }

  async resetPassword(
    request: operations.AuthResetPasswordRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authResetPassword(
      this,
      request,
      options,
    ));
  }

  async confirmEmail(
    request: operations.AuthConfirmEmailRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(authConfirmEmail(
      this,
      request,
      options,
    ));
  }
}
