/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupCreate } from "../funcs/backupCreate.js";
import { backupGet } from "../funcs/backupGet.js";
import { backupManualBackupMariadb } from "../funcs/backupManualBackupMariadb.js";
import { backupManualBackupMongo } from "../funcs/backupManualBackupMongo.js";
import { backupManualBackupMysql } from "../funcs/backupManualBackupMysql.js";
import { backupManualBackupPostgres } from "../funcs/backupManualBackupPostgres.js";
import { backupRemove } from "../funcs/backupRemove.js";
import { backupUpdate } from "../funcs/backupUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Backup extends ClientSDK {
  async create(
    request: operations.BackupCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.BackupOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupGet(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.BackupUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupUpdate(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.BackupRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupRemove(
      this,
      request,
      options,
    ));
  }

  async manualBackupPostgres(
    request: operations.BackupManualBackupPostgresRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupManualBackupPostgres(
      this,
      request,
      options,
    ));
  }

  async manualBackupMysql(
    request: operations.BackupManualBackupMySqlRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupManualBackupMysql(
      this,
      request,
      options,
    ));
  }

  async manualBackupMariadb(
    request: operations.BackupManualBackupMariadbRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupManualBackupMariadb(
      this,
      request,
      options,
    ));
  }

  async manualBackupMongo(
    request: operations.BackupManualBackupMongoRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(backupManualBackupMongo(
      this,
      request,
      options,
    ));
  }
}
