/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bitbucketCreate } from "../funcs/bitbucketCreate.js";
import { bitbucketGet } from "../funcs/bitbucketGet.js";
import { bitbucketGetBranches } from "../funcs/bitbucketGetBranches.js";
import { bitbucketGetRepositories } from "../funcs/bitbucketGetRepositories.js";
import { bitbucketProviders } from "../funcs/bitbucketProviders.js";
import { bitbucketTestConnection } from "../funcs/bitbucketTestConnection.js";
import { bitbucketUpdate } from "../funcs/bitbucketUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Bitbucket extends ClientSDK {
  async create(
    request: operations.BitbucketCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.BitbucketOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketGet(
      this,
      request,
      options,
    ));
  }

  async providers(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketProviders(
      this,
      options,
    ));
  }

  async getRepositories(
    request: operations.BitbucketGetBitbucketRepositoriesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketGetRepositories(
      this,
      request,
      options,
    ));
  }

  async getBranches(
    request: operations.BitbucketGetBitbucketBranchesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketGetBranches(
      this,
      request,
      options,
    ));
  }

  async testConnection(
    request: operations.BitbucketTestConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketTestConnection(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.BitbucketUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(bitbucketUpdate(
      this,
      request,
      options,
    ));
  }
}
