/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { composeCleanQueues } from "../funcs/composeCleanQueues.js";
import { composeCreate } from "../funcs/composeCreate.js";
import { composeDelete } from "../funcs/composeDelete.js";
import { composeDeploy } from "../funcs/composeDeploy.js";
import { composeDeployTemplate } from "../funcs/composeDeployTemplate.js";
import { composeFetchSourceType } from "../funcs/composeFetchSourceType.js";
import { composeGetConverted } from "../funcs/composeGetConverted.js";
import { composeGetDefaultCommand } from "../funcs/composeGetDefaultCommand.js";
import { composeGetOne } from "../funcs/composeGetOne.js";
import { composeGetTags } from "../funcs/composeGetTags.js";
import { composeGetTemplates } from "../funcs/composeGetTemplates.js";
import { composeRandomizeCompose } from "../funcs/composeRandomizeCompose.js";
import { composeRedeploy } from "../funcs/composeRedeploy.js";
import { composeRefreshToken } from "../funcs/composeRefreshToken.js";
import { composeStop } from "../funcs/composeStop.js";
import { composeUpdate } from "../funcs/composeUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Compose extends ClientSDK {
  async create(
    request: operations.ComposeCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeCreate(
      this,
      request,
      options,
    ));
  }

  async getOne(
    request: operations.ComposeOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeGetOne(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.ComposeUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeUpdate(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.ComposeDeleteRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeDelete(
      this,
      request,
      options,
    ));
  }

  async cleanQueues(
    request: operations.ComposeCleanQueuesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeCleanQueues(
      this,
      request,
      options,
    ));
  }

  async fetchSourceType(
    request: operations.ComposeFetchSourceTypeRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeFetchSourceType(
      this,
      request,
      options,
    ));
  }

  async randomizeCompose(
    request: operations.ComposeRandomizeComposeRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeRandomizeCompose(
      this,
      request,
      options,
    ));
  }

  async getConverted(
    request: operations.ComposeGetConvertedComposeRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeGetConverted(
      this,
      request,
      options,
    ));
  }

  async deploy(
    request: operations.ComposeDeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeDeploy(
      this,
      request,
      options,
    ));
  }

  async redeploy(
    request: operations.ComposeRedeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeRedeploy(
      this,
      request,
      options,
    ));
  }

  async stop(
    request: operations.ComposeStopRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeStop(
      this,
      request,
      options,
    ));
  }

  async getDefaultCommand(
    request: operations.ComposeGetDefaultCommandRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeGetDefaultCommand(
      this,
      request,
      options,
    ));
  }

  async refreshToken(
    request: operations.ComposeRefreshTokenRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeRefreshToken(
      this,
      request,
      options,
    ));
  }

  async deployTemplate(
    request: operations.ComposeDeployTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeDeployTemplate(
      this,
      request,
      options,
    ));
  }

  async getTemplates(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeGetTemplates(
      this,
      options,
    ));
  }

  async getTags(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(composeGetTags(
      this,
      options,
    ));
  }
}
