/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentAllByCompose } from "../funcs/deploymentAllByCompose.js";
import { deploymentAllByServer } from "../funcs/deploymentAllByServer.js";
import { deploymentGet } from "../funcs/deploymentGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Deployment extends ClientSDK {
  async get(
    request: operations.DeploymentAllRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(deploymentGet(
      this,
      request,
      options,
    ));
  }

  async allByCompose(
    request: operations.DeploymentAllByComposeRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(deploymentAllByCompose(
      this,
      request,
      options,
    ));
  }

  async allByServer(
    request: operations.DeploymentAllByServerRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(deploymentAllByServer(
      this,
      request,
      options,
    ));
  }
}
