/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainByApplicationId } from "../funcs/domainByApplicationId.js";
import { domainByComposeId } from "../funcs/domainByComposeId.js";
import { domainCreate } from "../funcs/domainCreate.js";
import { domainDelete } from "../funcs/domainDelete.js";
import { domainGenerateDomain } from "../funcs/domainGenerateDomain.js";
import { domainGet } from "../funcs/domainGet.js";
import { domainUpdate } from "../funcs/domainUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Domain extends ClientSDK {
  async create(
    request: operations.DomainCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainCreate(
      this,
      request,
      options,
    ));
  }

  async byApplicationId(
    request: operations.DomainByApplicationIdRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainByApplicationId(
      this,
      request,
      options,
    ));
  }

  async byComposeId(
    request: operations.DomainByComposeIdRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainByComposeId(
      this,
      request,
      options,
    ));
  }

  async generateDomain(
    request: operations.DomainGenerateDomainRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainGenerateDomain(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.DomainUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainUpdate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.DomainOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainGet(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.DomainDeleteRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(domainDelete(
      this,
      request,
      options,
    ));
  }
}
