/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { githubGetBranches } from "../funcs/githubGetBranches.js";
import { githubGetProviders } from "../funcs/githubGetProviders.js";
import { githubGetRepositories } from "../funcs/githubGetRepositories.js";
import { githubOne } from "../funcs/githubOne.js";
import { githubTestConnection } from "../funcs/githubTestConnection.js";
import { githubUpdate } from "../funcs/githubUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Github extends ClientSDK {
  async one(
    request: operations.GithubOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(githubOne(
      this,
      request,
      options,
    ));
  }

  async getRepositories(
    request: operations.GithubGetGithubRepositoriesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(githubGetRepositories(
      this,
      request,
      options,
    ));
  }

  async getBranches(
    request: operations.GithubGetGithubBranchesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(githubGetBranches(
      this,
      request,
      options,
    ));
  }

  async getProviders(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(githubGetProviders(
      this,
      options,
    ));
  }

  async testConnection(
    request: operations.GithubTestConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(githubTestConnection(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.GithubUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(githubUpdate(
      this,
      request,
      options,
    ));
  }
}
