/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gitlabCreate } from "../funcs/gitlabCreate.js";
import { gitlabGetGitlabBranches } from "../funcs/gitlabGetGitlabBranches.js";
import { gitlabGetGitlabRepositories } from "../funcs/gitlabGetGitlabRepositories.js";
import { gitlabOne } from "../funcs/gitlabOne.js";
import { gitlabProviders } from "../funcs/gitlabProviders.js";
import { gitlabTestConnection } from "../funcs/gitlabTestConnection.js";
import { gitlabUpdate } from "../funcs/gitlabUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Gitlab extends ClientSDK {
  async create(
    request: operations.GitlabCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabCreate(
      this,
      request,
      options,
    ));
  }

  async one(
    request: operations.GitlabOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabOne(
      this,
      request,
      options,
    ));
  }

  async providers(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabProviders(
      this,
      options,
    ));
  }

  async getGitlabRepositories(
    request: operations.GitlabGetGitlabRepositoriesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabGetGitlabRepositories(
      this,
      request,
      options,
    ));
  }

  async getGitlabBranches(
    request: operations.GitlabGetGitlabBranchesRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabGetGitlabBranches(
      this,
      request,
      options,
    ));
  }

  async testConnection(
    request: operations.GitlabTestConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabTestConnection(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.GitlabUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitlabUpdate(
      this,
      request,
      options,
    ));
  }
}
