/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gitProviderGetAll } from "../funcs/gitProviderGetAll.js";
import { gitProviderRemove } from "../funcs/gitProviderRemove.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GitProvider extends ClientSDK {
  async getAll(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitProviderGetAll(
      this,
      options,
    ));
  }

  async remove(
    request: operations.GitProviderRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(gitProviderRemove(
      this,
      request,
      options,
    ));
  }
}
