/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mongoChangeStatus } from "../funcs/mongoChangeStatus.js";
import { mongoCreate } from "../funcs/mongoCreate.js";
import { mongoDeploy } from "../funcs/mongoDeploy.js";
import { mongoGet } from "../funcs/mongoGet.js";
import { mongoReload } from "../funcs/mongoReload.js";
import { mongoRemove } from "../funcs/mongoRemove.js";
import { mongoSaveEnvironment } from "../funcs/mongoSaveEnvironment.js";
import { mongoSaveExternalPort } from "../funcs/mongoSaveExternalPort.js";
import { mongoStart } from "../funcs/mongoStart.js";
import { mongoStop } from "../funcs/mongoStop.js";
import { mongoUpdate } from "../funcs/mongoUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mongo extends ClientSDK {
  async create(
    request: operations.MongoCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.MongoOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoGet(
      this,
      request,
      options,
    ));
  }

  async start(
    request: operations.MongoStartRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoStart(
      this,
      request,
      options,
    ));
  }

  async stop(
    request: operations.MongoStopRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoStop(
      this,
      request,
      options,
    ));
  }

  async saveExternalPort(
    request: operations.MongoSaveExternalPortRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoSaveExternalPort(
      this,
      request,
      options,
    ));
  }

  async deploy(
    request: operations.MongoDeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoDeploy(
      this,
      request,
      options,
    ));
  }

  async changeStatus(
    request: operations.MongoChangeStatusRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoChangeStatus(
      this,
      request,
      options,
    ));
  }

  async reload(
    request: operations.MongoReloadRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoReload(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.MongoRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoRemove(
      this,
      request,
      options,
    ));
  }

  async saveEnvironment(
    request: operations.MongoSaveEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoSaveEnvironment(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.MongoUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mongoUpdate(
      this,
      request,
      options,
    ));
  }
}
