/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mysqlChangeStatus } from "../funcs/mysqlChangeStatus.js";
import { mysqlCreate } from "../funcs/mysqlCreate.js";
import { mysqlDeploy } from "../funcs/mysqlDeploy.js";
import { mysqlGet } from "../funcs/mysqlGet.js";
import { mysqlReload } from "../funcs/mysqlReload.js";
import { mysqlRemove } from "../funcs/mysqlRemove.js";
import { mysqlSaveEnvironment } from "../funcs/mysqlSaveEnvironment.js";
import { mysqlSaveExternalPort } from "../funcs/mysqlSaveExternalPort.js";
import { mysqlStart } from "../funcs/mysqlStart.js";
import { mysqlStop } from "../funcs/mysqlStop.js";
import { mysqlUpdate } from "../funcs/mysqlUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mysql extends ClientSDK {
  async create(
    request: operations.MysqlCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.MysqlOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlGet(
      this,
      request,
      options,
    ));
  }

  async start(
    request: operations.MysqlStartRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlStart(
      this,
      request,
      options,
    ));
  }

  async stop(
    request: operations.MysqlStopRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlStop(
      this,
      request,
      options,
    ));
  }

  async saveExternalPort(
    request: operations.MysqlSaveExternalPortRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlSaveExternalPort(
      this,
      request,
      options,
    ));
  }

  async deploy(
    request: operations.MysqlDeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlDeploy(
      this,
      request,
      options,
    ));
  }

  async changeStatus(
    request: operations.MysqlChangeStatusRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlChangeStatus(
      this,
      request,
      options,
    ));
  }

  async reload(
    request: operations.MysqlReloadRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlReload(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.MysqlRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlRemove(
      this,
      request,
      options,
    ));
  }

  async saveEnvironment(
    request: operations.MysqlSaveEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlSaveEnvironment(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.MysqlUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(mysqlUpdate(
      this,
      request,
      options,
    ));
  }
}
