/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationCreateDiscord } from "../funcs/notificationCreateDiscord.js";
import { notificationCreateEmail } from "../funcs/notificationCreateEmail.js";
import { notificationCreateSlack } from "../funcs/notificationCreateSlack.js";
import { notificationCreateTelegram } from "../funcs/notificationCreateTelegram.js";
import { notificationGetAll } from "../funcs/notificationGetAll.js";
import { notificationRemove } from "../funcs/notificationRemove.js";
import { notificationTestDiscordConnection } from "../funcs/notificationTestDiscordConnection.js";
import { notificationTestEmailConnection } from "../funcs/notificationTestEmailConnection.js";
import { notificationTestSlackConnection } from "../funcs/notificationTestSlackConnection.js";
import { notificationTestTelegramConnection } from "../funcs/notificationTestTelegramConnection.js";
import { notificationUpdateDiscord } from "../funcs/notificationUpdateDiscord.js";
import { notificationUpdateEmail } from "../funcs/notificationUpdateEmail.js";
import { notificationUpdateSlack } from "../funcs/notificationUpdateSlack.js";
import { notificationUpdateTelegram } from "../funcs/notificationUpdateTelegram.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Notification extends ClientSDK {
  async createSlack(
    request: operations.NotificationCreateSlackRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationCreateSlack(
      this,
      request,
      options,
    ));
  }

  async updateSlack(
    request: operations.NotificationUpdateSlackRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationUpdateSlack(
      this,
      request,
      options,
    ));
  }

  async testSlackConnection(
    request: operations.NotificationTestSlackConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationTestSlackConnection(
      this,
      request,
      options,
    ));
  }

  async createTelegram(
    request: operations.NotificationCreateTelegramRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationCreateTelegram(
      this,
      request,
      options,
    ));
  }

  async updateTelegram(
    request: operations.NotificationUpdateTelegramRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationUpdateTelegram(
      this,
      request,
      options,
    ));
  }

  async testTelegramConnection(
    request: operations.NotificationTestTelegramConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationTestTelegramConnection(
      this,
      request,
      options,
    ));
  }

  async createDiscord(
    request: operations.NotificationCreateDiscordRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationCreateDiscord(
      this,
      request,
      options,
    ));
  }

  async updateDiscord(
    request: operations.NotificationUpdateDiscordRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationUpdateDiscord(
      this,
      request,
      options,
    ));
  }

  async testDiscordConnection(
    request: operations.NotificationTestDiscordConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationTestDiscordConnection(
      this,
      request,
      options,
    ));
  }

  async createEmail(
    request: operations.NotificationCreateEmailRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationCreateEmail(
      this,
      request,
      options,
    ));
  }

  async updateEmail(
    request: operations.NotificationUpdateEmailRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationUpdateEmail(
      this,
      request,
      options,
    ));
  }

  async testEmailConnection(
    request: operations.NotificationTestEmailConnectionRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationTestEmailConnection(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.NotificationRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationRemove(
      this,
      request,
      options,
    ));
  }

  async getAll(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(notificationGetAll(
      this,
      options,
    ));
  }
}
