/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postgresChangeStatus } from "../funcs/postgresChangeStatus.js";
import { postgresCreate } from "../funcs/postgresCreate.js";
import { postgresDeploy } from "../funcs/postgresDeploy.js";
import { postgresGet } from "../funcs/postgresGet.js";
import { postgresReload } from "../funcs/postgresReload.js";
import { postgresRemove } from "../funcs/postgresRemove.js";
import { postgresSaveEnvironment } from "../funcs/postgresSaveEnvironment.js";
import { postgresSaveExternalPort } from "../funcs/postgresSaveExternalPort.js";
import { postgresStart } from "../funcs/postgresStart.js";
import { postgresStop } from "../funcs/postgresStop.js";
import { postgresUpdate } from "../funcs/postgresUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Postgres extends ClientSDK {
  async create(
    request: operations.PostgresCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.PostgresOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresGet(
      this,
      request,
      options,
    ));
  }

  async start(
    request: operations.PostgresStartRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresStart(
      this,
      request,
      options,
    ));
  }

  async stop(
    request: operations.PostgresStopRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresStop(
      this,
      request,
      options,
    ));
  }

  async saveExternalPort(
    request: operations.PostgresSaveExternalPortRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresSaveExternalPort(
      this,
      request,
      options,
    ));
  }

  async deploy(
    request: operations.PostgresDeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresDeploy(
      this,
      request,
      options,
    ));
  }

  async changeStatus(
    request: operations.PostgresChangeStatusRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresChangeStatus(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.PostgresRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresRemove(
      this,
      request,
      options,
    ));
  }

  async saveEnvironment(
    request: operations.PostgresSaveEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresSaveEnvironment(
      this,
      request,
      options,
    ));
  }

  async reload(
    request: operations.PostgresReloadRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresReload(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.PostgresUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(postgresUpdate(
      this,
      request,
      options,
    ));
  }
}
