/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectAll } from "../funcs/projectAll.js";
import { projectCreate } from "../funcs/projectCreate.js";
import { projectGet } from "../funcs/projectGet.js";
import { projectRemove } from "../funcs/projectRemove.js";
import { projectUpdate } from "../funcs/projectUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Project extends ClientSDK {
  async create(
    request: operations.ProjectCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(projectCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.ProjectOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(projectGet(
      this,
      request,
      options,
    ));
  }

  async all(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(projectAll(
      this,
      options,
    ));
  }

  async remove(
    request: operations.ProjectRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(projectRemove(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.ProjectUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(projectUpdate(
      this,
      request,
      options,
    ));
  }
}
