/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { redirectsCreate } from "../funcs/redirectsCreate.js";
import { redirectsDelete } from "../funcs/redirectsDelete.js";
import { redirectsGetOne } from "../funcs/redirectsGetOne.js";
import { redirectsUpdate } from "../funcs/redirectsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Redirects extends ClientSDK {
  async create(
    request: operations.RedirectsCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redirectsCreate(
      this,
      request,
      options,
    ));
  }

  async getOne(
    request: operations.RedirectsOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redirectsGetOne(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.RedirectsDeleteRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redirectsDelete(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.RedirectsUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redirectsUpdate(
      this,
      request,
      options,
    ));
  }
}
