/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { redisChangeStatus } from "../funcs/redisChangeStatus.js";
import { redisCreate } from "../funcs/redisCreate.js";
import { redisDeploy } from "../funcs/redisDeploy.js";
import { redisGet } from "../funcs/redisGet.js";
import { redisReload } from "../funcs/redisReload.js";
import { redisRemove } from "../funcs/redisRemove.js";
import { redisSaveEnvironment } from "../funcs/redisSaveEnvironment.js";
import { redisSaveExternalPort } from "../funcs/redisSaveExternalPort.js";
import { redisStart } from "../funcs/redisStart.js";
import { redisStop } from "../funcs/redisStop.js";
import { redisUpdate } from "../funcs/redisUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Redis extends ClientSDK {
  async create(
    request: operations.RedisCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.RedisOneRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisGet(
      this,
      request,
      options,
    ));
  }

  async start(
    request: operations.RedisStartRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisStart(
      this,
      request,
      options,
    ));
  }

  async reload(
    request: operations.RedisReloadRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisReload(
      this,
      request,
      options,
    ));
  }

  async stop(
    request: operations.RedisStopRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisStop(
      this,
      request,
      options,
    ));
  }

  async saveExternalPort(
    request: operations.RedisSaveExternalPortRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisSaveExternalPort(
      this,
      request,
      options,
    ));
  }

  async deploy(
    request: operations.RedisDeployRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisDeploy(
      this,
      request,
      options,
    ));
  }

  async changeStatus(
    request: operations.RedisChangeStatusRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisChangeStatus(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.RedisRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisRemove(
      this,
      request,
      options,
    ));
  }

  async saveEnvironment(
    request: operations.RedisSaveEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisSaveEnvironment(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.RedisUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(redisUpdate(
      this,
      request,
      options,
    ));
  }
}
