/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Admin } from "./admin.js";
import { Application } from "./application.js";
import { Auth } from "./auth.js";
import { Backup } from "./backup.js";
import { Bitbucket } from "./bitbucket.js";
import { Certificates } from "./certificates.js";
import { Cluster } from "./cluster.js";
import { Compose } from "./compose.js";
import { Deployment } from "./deployment.js";
import { Destination } from "./destination.js";
import { Docker } from "./docker.js";
import { Domain } from "./domain.js";
import { Github } from "./github.js";
import { Gitlab } from "./gitlab.js";
import { GitProvider } from "./gitprovider.js";
import { Mariadb } from "./mariadb.js";
import { Mongo } from "./mongo.js";
import { Mounts } from "./mounts.js";
import { Mysql } from "./mysql.js";
import { Notification } from "./notification.js";
import { Notifications } from "./notifications.js";
import { Port } from "./port.js";
import { Postgres } from "./postgres.js";
import { Project } from "./project.js";
import { Redirects } from "./redirects.js";
import { Redis } from "./redis.js";
import { Registry } from "./registry.js";
import { Security } from "./security.js";
import { Server } from "./server.js";
import { Servers } from "./servers.js";
import { Settings } from "./settings.js";
import { SshKey } from "./sshkey.js";
import { SshKeys } from "./sshkeys.js";
import { Stripe } from "./stripe.js";
import { User } from "./user.js";

export class Dokploy extends ClientSDK {
  private _admin?: Admin;
  get admin(): Admin {
    return (this._admin ??= new Admin(this._options));
  }

  private _docker?: Docker;
  get docker(): Docker {
    return (this._docker ??= new Docker(this._options));
  }

  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _project?: Project;
  get project(): Project {
    return (this._project ??= new Project(this._options));
  }

  private _application?: Application;
  get application(): Application {
    return (this._application ??= new Application(this._options));
  }

  private _mysql?: Mysql;
  get mysql(): Mysql {
    return (this._mysql ??= new Mysql(this._options));
  }

  private _postgres?: Postgres;
  get postgres(): Postgres {
    return (this._postgres ??= new Postgres(this._options));
  }

  private _redis?: Redis;
  get redis(): Redis {
    return (this._redis ??= new Redis(this._options));
  }

  private _mongo?: Mongo;
  get mongo(): Mongo {
    return (this._mongo ??= new Mongo(this._options));
  }

  private _mariadb?: Mariadb;
  get mariadb(): Mariadb {
    return (this._mariadb ??= new Mariadb(this._options));
  }

  private _compose?: Compose;
  get compose(): Compose {
    return (this._compose ??= new Compose(this._options));
  }

  private _user?: User;
  get user(): User {
    return (this._user ??= new User(this._options));
  }

  private _domain?: Domain;
  get domain(): Domain {
    return (this._domain ??= new Domain(this._options));
  }

  private _destination?: Destination;
  get destination(): Destination {
    return (this._destination ??= new Destination(this._options));
  }

  private _backup?: Backup;
  get backup(): Backup {
    return (this._backup ??= new Backup(this._options));
  }

  private _deployment?: Deployment;
  get deployment(): Deployment {
    return (this._deployment ??= new Deployment(this._options));
  }

  private _mounts?: Mounts;
  get mounts(): Mounts {
    return (this._mounts ??= new Mounts(this._options));
  }

  private _certificates?: Certificates;
  get certificates(): Certificates {
    return (this._certificates ??= new Certificates(this._options));
  }

  private _settings?: Settings;
  get settings(): Settings {
    return (this._settings ??= new Settings(this._options));
  }

  private _security?: Security;
  get security(): Security {
    return (this._security ??= new Security(this._options));
  }

  private _redirects?: Redirects;
  get redirects(): Redirects {
    return (this._redirects ??= new Redirects(this._options));
  }

  private _port?: Port;
  get port(): Port {
    return (this._port ??= new Port(this._options));
  }

  private _registry?: Registry;
  get registry(): Registry {
    return (this._registry ??= new Registry(this._options));
  }

  private _cluster?: Cluster;
  get cluster(): Cluster {
    return (this._cluster ??= new Cluster(this._options));
  }

  private _notification?: Notification;
  get notification(): Notification {
    return (this._notification ??= new Notification(this._options));
  }

  private _notifications?: Notifications;
  get notifications(): Notifications {
    return (this._notifications ??= new Notifications(this._options));
  }

  private _sshKeys?: SshKeys;
  get sshKeys(): SshKeys {
    return (this._sshKeys ??= new SshKeys(this._options));
  }

  private _sshKey?: SshKey;
  get sshKey(): SshKey {
    return (this._sshKey ??= new SshKey(this._options));
  }

  private _gitProvider?: GitProvider;
  get gitProvider(): GitProvider {
    return (this._gitProvider ??= new GitProvider(this._options));
  }

  private _bitbucket?: Bitbucket;
  get bitbucket(): Bitbucket {
    return (this._bitbucket ??= new Bitbucket(this._options));
  }

  private _gitlab?: Gitlab;
  get gitlab(): Gitlab {
    return (this._gitlab ??= new Gitlab(this._options));
  }

  private _github?: Github;
  get github(): Github {
    return (this._github ??= new Github(this._options));
  }

  private _server?: Server;
  get server(): Server {
    return (this._server ??= new Server(this._options));
  }

  private _servers?: Servers;
  get servers(): Servers {
    return (this._servers ??= new Servers(this._options));
  }

  private _stripe?: Stripe;
  get stripe(): Stripe {
    return (this._stripe ??= new Stripe(this._options));
  }
}
