/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serverAll } from "../funcs/serverAll.js";
import { serverCreate } from "../funcs/serverCreate.js";
import { serverRemove } from "../funcs/serverRemove.js";
import { serverSetup } from "../funcs/serverSetup.js";
import { serverUpdate } from "../funcs/serverUpdate.js";
import { serverWithSSHKey } from "../funcs/serverWithSSHKey.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Server extends ClientSDK {
  async create(
    request: operations.ServerCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(serverCreate(
      this,
      request,
      options,
    ));
  }

  async all(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(serverAll(
      this,
      options,
    ));
  }

  async withSSHKey(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(serverWithSSHKey(
      this,
      options,
    ));
  }

  async setup(
    request: operations.ServerSetupRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(serverSetup(
      this,
      request,
      options,
    ));
  }

  async remove(
    request: operations.ServerRemoveRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(serverRemove(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.ServerUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(serverUpdate(
      this,
      request,
      options,
    ));
  }
}
