/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sshKeysAll } from "../funcs/sshKeysAll.js";
import { sshKeysCreate } from "../funcs/sshKeysCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SshKeys extends ClientSDK {
  async create(
    request: operations.SshKeyCreateRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(sshKeysCreate(
      this,
      request,
      options,
    ));
  }

  async all(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(sshKeysAll(
      this,
      options,
    ));
  }
}
