/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userByAuthId } from "../funcs/userByAuthId.js";
import { userByUserId } from "../funcs/userByUserId.js";
import { userGetAll } from "../funcs/userGetAll.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class User extends ClientSDK {
  async getAll(
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(userGetAll(
      this,
      options,
    ));
  }

  async byAuthId(
    request: operations.UserByAuthIdRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(userByAuthId(
      this,
      request,
      options,
    ));
  }

  async byUserId(
    request: operations.UserByUserIdRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(userByUserId(
      this,
      request,
      options,
    ));
  }
}
