/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the dokploy SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx adminGetOne.example.ts
 */

import { Dokploy } from "dokploy";

const dokploy = new Dokploy({
  authorization: process.env["DOKPLOY_AUTHORIZATION"] ?? "",
});

async function main() {
  const result = await dokploy.admin.getOne();

  console.log(result);
}

main().catch(console.error);
