workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Dokploy API:
        inputs:
            - location: https://raw.githubusercontent.com/Dokploy/website/refs/heads/main/apps/docs/api.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/lukehagar/lukehagar/dokploy-api
targets:
    dokploy:
        target: typescript
        source: Dokploy API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/lukehagar/lukehagar/dokploy-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
