/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminAssignPermissionsRequest = {
  userId: string;
  canCreateProjects: boolean;
  canCreateServices: boolean;
  canDeleteProjects: boolean;
  canDeleteServices: boolean;
  accesedProjects: Array<string>;
  accesedServices: Array<string>;
  canAccessToTraefikFiles: boolean;
  canAccessToDocker: boolean;
  canAccessToAPI: boolean;
  canAccessToSSHKeys: boolean;
  canAccessToGitProviders: boolean;
};

/** @internal */
export const AdminAssignPermissionsRequest$inboundSchema: z.ZodType<
  AdminAssignPermissionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string(),
  canCreateProjects: z.boolean(),
  canCreateServices: z.boolean(),
  canDeleteProjects: z.boolean(),
  canDeleteServices: z.boolean(),
  accesedProjects: z.array(z.string()),
  accesedServices: z.array(z.string()),
  canAccessToTraefikFiles: z.boolean(),
  canAccessToDocker: z.boolean(),
  canAccessToAPI: z.boolean(),
  canAccessToSSHKeys: z.boolean(),
  canAccessToGitProviders: z.boolean(),
});

/** @internal */
export type AdminAssignPermissionsRequest$Outbound = {
  userId: string;
  canCreateProjects: boolean;
  canCreateServices: boolean;
  canDeleteProjects: boolean;
  canDeleteServices: boolean;
  accesedProjects: Array<string>;
  accesedServices: Array<string>;
  canAccessToTraefikFiles: boolean;
  canAccessToDocker: boolean;
  canAccessToAPI: boolean;
  canAccessToSSHKeys: boolean;
  canAccessToGitProviders: boolean;
};

/** @internal */
export const AdminAssignPermissionsRequest$outboundSchema: z.ZodType<
  AdminAssignPermissionsRequest$Outbound,
  z.ZodTypeDef,
  AdminAssignPermissionsRequest
> = z.object({
  userId: z.string(),
  canCreateProjects: z.boolean(),
  canCreateServices: z.boolean(),
  canDeleteProjects: z.boolean(),
  canDeleteServices: z.boolean(),
  accesedProjects: z.array(z.string()),
  accesedServices: z.array(z.string()),
  canAccessToTraefikFiles: z.boolean(),
  canAccessToDocker: z.boolean(),
  canAccessToAPI: z.boolean(),
  canAccessToSSHKeys: z.boolean(),
  canAccessToGitProviders: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdminAssignPermissionsRequest$ {
  /** @deprecated use `AdminAssignPermissionsRequest$inboundSchema` instead. */
  export const inboundSchema = AdminAssignPermissionsRequest$inboundSchema;
  /** @deprecated use `AdminAssignPermissionsRequest$outboundSchema` instead. */
  export const outboundSchema = AdminAssignPermissionsRequest$outboundSchema;
  /** @deprecated use `AdminAssignPermissionsRequest$Outbound` instead. */
  export type Outbound = AdminAssignPermissionsRequest$Outbound;
}

export function adminAssignPermissionsRequestToJSON(
  adminAssignPermissionsRequest: AdminAssignPermissionsRequest,
): string {
  return JSON.stringify(
    AdminAssignPermissionsRequest$outboundSchema.parse(
      adminAssignPermissionsRequest,
    ),
  );
}

export function adminAssignPermissionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<AdminAssignPermissionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminAssignPermissionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminAssignPermissionsRequest' from JSON`,
  );
}
