/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminRemoveUserRequest = {
  authId: string;
};

/** @internal */
export const AdminRemoveUserRequest$inboundSchema: z.ZodType<
  AdminRemoveUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  authId: z.string(),
});

/** @internal */
export type AdminRemoveUserRequest$Outbound = {
  authId: string;
};

/** @internal */
export const AdminRemoveUserRequest$outboundSchema: z.ZodType<
  AdminRemoveUserRequest$Outbound,
  z.ZodTypeDef,
  AdminRemoveUserRequest
> = z.object({
  authId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdminRemoveUserRequest$ {
  /** @deprecated use `AdminRemoveUserRequest$inboundSchema` instead. */
  export const inboundSchema = AdminRemoveUserRequest$inboundSchema;
  /** @deprecated use `AdminRemoveUserRequest$outboundSchema` instead. */
  export const outboundSchema = AdminRemoveUserRequest$outboundSchema;
  /** @deprecated use `AdminRemoveUserRequest$Outbound` instead. */
  export type Outbound = AdminRemoveUserRequest$Outbound;
}

export function adminRemoveUserRequestToJSON(
  adminRemoveUserRequest: AdminRemoveUserRequest,
): string {
  return JSON.stringify(
    AdminRemoveUserRequest$outboundSchema.parse(adminRemoveUserRequest),
  );
}

export function adminRemoveUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<AdminRemoveUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminRemoveUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminRemoveUserRequest' from JSON`,
  );
}
