/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminCreateUserInvitationRequest = {
  email: string;
};

/** @internal */
export const AdminCreateUserInvitationRequest$inboundSchema: z.ZodType<
  AdminCreateUserInvitationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
});

/** @internal */
export type AdminCreateUserInvitationRequest$Outbound = {
  email: string;
};

/** @internal */
export const AdminCreateUserInvitationRequest$outboundSchema: z.ZodType<
  AdminCreateUserInvitationRequest$Outbound,
  z.ZodTypeDef,
  AdminCreateUserInvitationRequest
> = z.object({
  email: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdminCreateUserInvitationRequest$ {
  /** @deprecated use `AdminCreateUserInvitationRequest$inboundSchema` instead. */
  export const inboundSchema = AdminCreateUserInvitationRequest$inboundSchema;
  /** @deprecated use `AdminCreateUserInvitationRequest$outboundSchema` instead. */
  export const outboundSchema = AdminCreateUserInvitationRequest$outboundSchema;
  /** @deprecated use `AdminCreateUserInvitationRequest$Outbound` instead. */
  export type Outbound = AdminCreateUserInvitationRequest$Outbound;
}

export function adminCreateUserInvitationRequestToJSON(
  adminCreateUserInvitationRequest: AdminCreateUserInvitationRequest,
): string {
  return JSON.stringify(
    AdminCreateUserInvitationRequest$outboundSchema.parse(
      adminCreateUserInvitationRequest,
    ),
  );
}

export function adminCreateUserInvitationRequestFromJSON(
  jsonString: string,
): SafeParseResult<AdminCreateUserInvitationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminCreateUserInvitationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminCreateUserInvitationRequest' from JSON`,
  );
}
