/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminGetUserByTokenRequest = {
  token: string;
};

/** @internal */
export const AdminGetUserByTokenRequest$inboundSchema: z.ZodType<
  AdminGetUserByTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string(),
});

/** @internal */
export type AdminGetUserByTokenRequest$Outbound = {
  token: string;
};

/** @internal */
export const AdminGetUserByTokenRequest$outboundSchema: z.ZodType<
  AdminGetUserByTokenRequest$Outbound,
  z.ZodTypeDef,
  AdminGetUserByTokenRequest
> = z.object({
  token: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdminGetUserByTokenRequest$ {
  /** @deprecated use `AdminGetUserByTokenRequest$inboundSchema` instead. */
  export const inboundSchema = AdminGetUserByTokenRequest$inboundSchema;
  /** @deprecated use `AdminGetUserByTokenRequest$outboundSchema` instead. */
  export const outboundSchema = AdminGetUserByTokenRequest$outboundSchema;
  /** @deprecated use `AdminGetUserByTokenRequest$Outbound` instead. */
  export type Outbound = AdminGetUserByTokenRequest$Outbound;
}

export function adminGetUserByTokenRequestToJSON(
  adminGetUserByTokenRequest: AdminGetUserByTokenRequest,
): string {
  return JSON.stringify(
    AdminGetUserByTokenRequest$outboundSchema.parse(adminGetUserByTokenRequest),
  );
}

export function adminGetUserByTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<AdminGetUserByTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminGetUserByTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminGetUserByTokenRequest' from JSON`,
  );
}
