/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ApplicationSaveBuildTypeBuildType = {
  Dockerfile: "dockerfile",
  HerokuBuildpacks: "heroku_buildpacks",
  PaketoBuildpacks: "paketo_buildpacks",
  Nixpacks: "nixpacks",
  Static: "static",
} as const;
export type ApplicationSaveBuildTypeBuildType = ClosedEnum<
  typeof ApplicationSaveBuildTypeBuildType
>;

export type ApplicationSaveBuildTypeRequest = {
  applicationId: string;
  buildType: ApplicationSaveBuildTypeBuildType;
  dockerfile?: string | null | undefined;
  dockerContextPath: string | null;
  dockerBuildStage: string | null;
  publishDirectory?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveBuildTypeBuildType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationSaveBuildTypeBuildType
> = z.nativeEnum(ApplicationSaveBuildTypeBuildType);

/** @internal */
export const ApplicationSaveBuildTypeBuildType$outboundSchema: z.ZodNativeEnum<
  typeof ApplicationSaveBuildTypeBuildType
> = ApplicationSaveBuildTypeBuildType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveBuildTypeBuildType$ {
  /** @deprecated use `ApplicationSaveBuildTypeBuildType$inboundSchema` instead. */
  export const inboundSchema = ApplicationSaveBuildTypeBuildType$inboundSchema;
  /** @deprecated use `ApplicationSaveBuildTypeBuildType$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveBuildTypeBuildType$outboundSchema;
}

/** @internal */
export const ApplicationSaveBuildTypeRequest$inboundSchema: z.ZodType<
  ApplicationSaveBuildTypeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  buildType: ApplicationSaveBuildTypeBuildType$inboundSchema,
  dockerfile: z.nullable(z.string()).optional(),
  dockerContextPath: z.nullable(z.string()),
  dockerBuildStage: z.nullable(z.string()),
  publishDirectory: z.nullable(z.string()).optional(),
});

/** @internal */
export type ApplicationSaveBuildTypeRequest$Outbound = {
  applicationId: string;
  buildType: string;
  dockerfile?: string | null | undefined;
  dockerContextPath: string | null;
  dockerBuildStage: string | null;
  publishDirectory?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveBuildTypeRequest$outboundSchema: z.ZodType<
  ApplicationSaveBuildTypeRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveBuildTypeRequest
> = z.object({
  applicationId: z.string(),
  buildType: ApplicationSaveBuildTypeBuildType$outboundSchema,
  dockerfile: z.nullable(z.string()).optional(),
  dockerContextPath: z.nullable(z.string()),
  dockerBuildStage: z.nullable(z.string()),
  publishDirectory: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveBuildTypeRequest$ {
  /** @deprecated use `ApplicationSaveBuildTypeRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationSaveBuildTypeRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveBuildTypeRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationSaveBuildTypeRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveBuildTypeRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveBuildTypeRequest$Outbound;
}

export function applicationSaveBuildTypeRequestToJSON(
  applicationSaveBuildTypeRequest: ApplicationSaveBuildTypeRequest,
): string {
  return JSON.stringify(
    ApplicationSaveBuildTypeRequest$outboundSchema.parse(
      applicationSaveBuildTypeRequest,
    ),
  );
}

export function applicationSaveBuildTypeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationSaveBuildTypeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationSaveBuildTypeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationSaveBuildTypeRequest' from JSON`,
  );
}
