/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationSaveGithubProviderRequest = {
  applicationId: string;
  repository?: string | null | undefined;
  branch?: string | null | undefined;
  owner: string | null;
  buildPath?: string | null | undefined;
  githubId: string | null;
};

/** @internal */
export const ApplicationSaveGithubProviderRequest$inboundSchema: z.ZodType<
  ApplicationSaveGithubProviderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  repository: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  owner: z.nullable(z.string()),
  buildPath: z.nullable(z.string()).optional(),
  githubId: z.nullable(z.string()),
});

/** @internal */
export type ApplicationSaveGithubProviderRequest$Outbound = {
  applicationId: string;
  repository?: string | null | undefined;
  branch?: string | null | undefined;
  owner: string | null;
  buildPath?: string | null | undefined;
  githubId: string | null;
};

/** @internal */
export const ApplicationSaveGithubProviderRequest$outboundSchema: z.ZodType<
  ApplicationSaveGithubProviderRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveGithubProviderRequest
> = z.object({
  applicationId: z.string(),
  repository: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  owner: z.nullable(z.string()),
  buildPath: z.nullable(z.string()).optional(),
  githubId: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveGithubProviderRequest$ {
  /** @deprecated use `ApplicationSaveGithubProviderRequest$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationSaveGithubProviderRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveGithubProviderRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveGithubProviderRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveGithubProviderRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveGithubProviderRequest$Outbound;
}

export function applicationSaveGithubProviderRequestToJSON(
  applicationSaveGithubProviderRequest: ApplicationSaveGithubProviderRequest,
): string {
  return JSON.stringify(
    ApplicationSaveGithubProviderRequest$outboundSchema.parse(
      applicationSaveGithubProviderRequest,
    ),
  );
}

export function applicationSaveGithubProviderRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationSaveGithubProviderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationSaveGithubProviderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationSaveGithubProviderRequest' from JSON`,
  );
}
