/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationStartRequest = {
  applicationId: string;
};

/** @internal */
export const ApplicationStartRequest$inboundSchema: z.ZodType<
  ApplicationStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
});

/** @internal */
export type ApplicationStartRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationStartRequest$outboundSchema: z.ZodType<
  ApplicationStartRequest$Outbound,
  z.ZodTypeDef,
  ApplicationStartRequest
> = z.object({
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationStartRequest$ {
  /** @deprecated use `ApplicationStartRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationStartRequest$inboundSchema;
  /** @deprecated use `ApplicationStartRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationStartRequest$outboundSchema;
  /** @deprecated use `ApplicationStartRequest$Outbound` instead. */
  export type Outbound = ApplicationStartRequest$Outbound;
}

export function applicationStartRequestToJSON(
  applicationStartRequest: ApplicationStartRequest,
): string {
  return JSON.stringify(
    ApplicationStartRequest$outboundSchema.parse(applicationStartRequest),
  );
}

export function applicationStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartRequest' from JSON`,
  );
}
