/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationSaveGitProdiverRequest = {
  customGitBranch?: string | null | undefined;
  applicationId: string;
  customGitBuildPath?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveGitProdiverRequest$inboundSchema: z.ZodType<
  ApplicationSaveGitProdiverRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  customGitBranch: z.nullable(z.string()).optional(),
  applicationId: z.string(),
  customGitBuildPath: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
});

/** @internal */
export type ApplicationSaveGitProdiverRequest$Outbound = {
  customGitBranch?: string | null | undefined;
  applicationId: string;
  customGitBuildPath?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveGitProdiverRequest$outboundSchema: z.ZodType<
  ApplicationSaveGitProdiverRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveGitProdiverRequest
> = z.object({
  customGitBranch: z.nullable(z.string()).optional(),
  applicationId: z.string(),
  customGitBuildPath: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveGitProdiverRequest$ {
  /** @deprecated use `ApplicationSaveGitProdiverRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationSaveGitProdiverRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveGitProdiverRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveGitProdiverRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveGitProdiverRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveGitProdiverRequest$Outbound;
}

export function applicationSaveGitProdiverRequestToJSON(
  applicationSaveGitProdiverRequest: ApplicationSaveGitProdiverRequest,
): string {
  return JSON.stringify(
    ApplicationSaveGitProdiverRequest$outboundSchema.parse(
      applicationSaveGitProdiverRequest,
    ),
  );
}

export function applicationSaveGitProdiverRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationSaveGitProdiverRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationSaveGitProdiverRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationSaveGitProdiverRequest' from JSON`,
  );
}
