/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ApplicationUpdateSourceType = {
  Github: "github",
  Docker: "docker",
  Git: "git",
} as const;
export type ApplicationUpdateSourceType = ClosedEnum<
  typeof ApplicationUpdateSourceType
>;

export type HealthCheckSwarm = {
  test?: Array<string> | undefined;
  interval?: number | undefined;
  timeout?: number | undefined;
  startPeriod?: number | undefined;
  retries?: number | undefined;
};

export type RestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type Spread = {
  spreadDescriptor: string;
};

export type Preference = {
  spread: Spread;
};

export type Platform = {
  architecture: string;
  os: string;
};

export type PlacementSwarm = {
  constraints?: Array<string> | undefined;
  preferences?: Array<Preference> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<Platform> | undefined;
};

export type UpdateConfigSwarm = {
  parallelism: number;
  delay?: number | undefined;
  failureAction?: string | undefined;
  monitor?: number | undefined;
  maxFailureRatio?: number | undefined;
  order: string;
};

export type RollbackConfigSwarm = {
  parallelism: number;
  delay?: number | undefined;
  failureAction?: string | undefined;
  monitor?: number | undefined;
  maxFailureRatio?: number | undefined;
  order: string;
};

export type Replicated = {
  replicas?: number | undefined;
};

export type Global = {};

export type ReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type GlobalJob = {};

export type ModeSwarm = {
  replicated?: Replicated | undefined;
  global?: Global | undefined;
  replicatedJob?: ReplicatedJob | undefined;
  globalJob?: GlobalJob | undefined;
};

export type DriverOpts = {};

export type NetworkSwarm = {
  target?: string | undefined;
  aliases?: Array<string> | undefined;
  driverOpts?: DriverOpts | undefined;
};

export const ApplicationUpdateApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type ApplicationUpdateApplicationStatus = ClosedEnum<
  typeof ApplicationUpdateApplicationStatus
>;

export const ApplicationUpdateBuildType = {
  Dockerfile: "dockerfile",
  HerokuBuildpacks: "heroku_buildpacks",
  PaketoBuildpacks: "paketo_buildpacks",
  Nixpacks: "nixpacks",
  Static: "static",
} as const;
export type ApplicationUpdateBuildType = ClosedEnum<
  typeof ApplicationUpdateBuildType
>;

export type ApplicationUpdateRequest = {
  applicationId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  env?: string | null | undefined;
  buildArgs?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  title?: string | null | undefined;
  enabled?: boolean | null | undefined;
  subtitle?: string | null | undefined;
  command?: string | null | undefined;
  refreshToken?: string | null | undefined;
  sourceType?: ApplicationUpdateSourceType | undefined;
  repository?: string | null | undefined;
  owner?: string | null | undefined;
  branch?: string | null | undefined;
  buildPath?: string | null | undefined;
  autoDeploy?: boolean | null | undefined;
  gitlabProjectId?: number | null | undefined;
  gitlabRepository?: string | null | undefined;
  gitlabOwner?: string | null | undefined;
  gitlabBranch?: string | null | undefined;
  gitlabBuildPath?: string | null | undefined;
  gitlabPathNamespace?: string | null | undefined;
  bitbucketRepository?: string | null | undefined;
  bitbucketOwner?: string | null | undefined;
  bitbucketBranch?: string | null | undefined;
  bitbucketBuildPath?: string | null | undefined;
  username?: string | null | undefined;
  password?: string | null | undefined;
  dockerImage?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  customGitBranch?: string | null | undefined;
  customGitBuildPath?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
  dockerfile?: string | null | undefined;
  dockerContextPath?: string | null | undefined;
  dockerBuildStage?: string | null | undefined;
  dropBuildPath?: string | null | undefined;
  healthCheckSwarm?: HealthCheckSwarm | null | undefined;
  restartPolicySwarm?: RestartPolicySwarm | null | undefined;
  placementSwarm?: PlacementSwarm | null | undefined;
  updateConfigSwarm?: UpdateConfigSwarm | null | undefined;
  rollbackConfigSwarm?: RollbackConfigSwarm | null | undefined;
  modeSwarm?: ModeSwarm | null | undefined;
  labelsSwarm?: { [k: string]: string } | null | undefined;
  networkSwarm?: Array<NetworkSwarm> | null | undefined;
  replicas?: number | undefined;
  applicationStatus?: ApplicationUpdateApplicationStatus | undefined;
  buildType?: ApplicationUpdateBuildType | undefined;
  publishDirectory?: string | null | undefined;
  createdAt?: string | undefined;
  registryId?: string | null | undefined;
  projectId?: string | undefined;
  githubId?: string | null | undefined;
  gitlabId?: string | null | undefined;
  bitbucketId?: string | null | undefined;
};

/** @internal */
export const ApplicationUpdateSourceType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationUpdateSourceType
> = z.nativeEnum(ApplicationUpdateSourceType);

/** @internal */
export const ApplicationUpdateSourceType$outboundSchema: z.ZodNativeEnum<
  typeof ApplicationUpdateSourceType
> = ApplicationUpdateSourceType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationUpdateSourceType$ {
  /** @deprecated use `ApplicationUpdateSourceType$inboundSchema` instead. */
  export const inboundSchema = ApplicationUpdateSourceType$inboundSchema;
  /** @deprecated use `ApplicationUpdateSourceType$outboundSchema` instead. */
  export const outboundSchema = ApplicationUpdateSourceType$outboundSchema;
}

/** @internal */
export const HealthCheckSwarm$inboundSchema: z.ZodType<
  HealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Test: z.array(z.string()).optional(),
  Interval: z.number().optional(),
  Timeout: z.number().optional(),
  StartPeriod: z.number().optional(),
  Retries: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Test": "test",
    "Interval": "interval",
    "Timeout": "timeout",
    "StartPeriod": "startPeriod",
    "Retries": "retries",
  });
});

/** @internal */
export type HealthCheckSwarm$Outbound = {
  Test?: Array<string> | undefined;
  Interval?: number | undefined;
  Timeout?: number | undefined;
  StartPeriod?: number | undefined;
  Retries?: number | undefined;
};

/** @internal */
export const HealthCheckSwarm$outboundSchema: z.ZodType<
  HealthCheckSwarm$Outbound,
  z.ZodTypeDef,
  HealthCheckSwarm
> = z.object({
  test: z.array(z.string()).optional(),
  interval: z.number().optional(),
  timeout: z.number().optional(),
  startPeriod: z.number().optional(),
  retries: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    test: "Test",
    interval: "Interval",
    timeout: "Timeout",
    startPeriod: "StartPeriod",
    retries: "Retries",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HealthCheckSwarm$ {
  /** @deprecated use `HealthCheckSwarm$inboundSchema` instead. */
  export const inboundSchema = HealthCheckSwarm$inboundSchema;
  /** @deprecated use `HealthCheckSwarm$outboundSchema` instead. */
  export const outboundSchema = HealthCheckSwarm$outboundSchema;
  /** @deprecated use `HealthCheckSwarm$Outbound` instead. */
  export type Outbound = HealthCheckSwarm$Outbound;
}

export function healthCheckSwarmToJSON(
  healthCheckSwarm: HealthCheckSwarm,
): string {
  return JSON.stringify(
    HealthCheckSwarm$outboundSchema.parse(healthCheckSwarm),
  );
}

export function healthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<HealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const RestartPolicySwarm$inboundSchema: z.ZodType<
  RestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

/** @internal */
export type RestartPolicySwarm$Outbound = {
  Condition?: string | undefined;
  Delay?: number | undefined;
  MaxAttempts?: number | undefined;
  Window?: number | undefined;
};

/** @internal */
export const RestartPolicySwarm$outboundSchema: z.ZodType<
  RestartPolicySwarm$Outbound,
  z.ZodTypeDef,
  RestartPolicySwarm
> = z.object({
  condition: z.string().optional(),
  delay: z.number().optional(),
  maxAttempts: z.number().optional(),
  window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    condition: "Condition",
    delay: "Delay",
    maxAttempts: "MaxAttempts",
    window: "Window",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RestartPolicySwarm$ {
  /** @deprecated use `RestartPolicySwarm$inboundSchema` instead. */
  export const inboundSchema = RestartPolicySwarm$inboundSchema;
  /** @deprecated use `RestartPolicySwarm$outboundSchema` instead. */
  export const outboundSchema = RestartPolicySwarm$outboundSchema;
  /** @deprecated use `RestartPolicySwarm$Outbound` instead. */
  export type Outbound = RestartPolicySwarm$Outbound;
}

export function restartPolicySwarmToJSON(
  restartPolicySwarm: RestartPolicySwarm,
): string {
  return JSON.stringify(
    RestartPolicySwarm$outboundSchema.parse(restartPolicySwarm),
  );
}

export function restartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<RestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const Spread$inboundSchema: z.ZodType<Spread, z.ZodTypeDef, unknown> = z
  .object({
    SpreadDescriptor: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "SpreadDescriptor": "spreadDescriptor",
    });
  });

/** @internal */
export type Spread$Outbound = {
  SpreadDescriptor: string;
};

/** @internal */
export const Spread$outboundSchema: z.ZodType<
  Spread$Outbound,
  z.ZodTypeDef,
  Spread
> = z.object({
  spreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    spreadDescriptor: "SpreadDescriptor",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Spread$ {
  /** @deprecated use `Spread$inboundSchema` instead. */
  export const inboundSchema = Spread$inboundSchema;
  /** @deprecated use `Spread$outboundSchema` instead. */
  export const outboundSchema = Spread$outboundSchema;
  /** @deprecated use `Spread$Outbound` instead. */
  export type Outbound = Spread$Outbound;
}

export function spreadToJSON(spread: Spread): string {
  return JSON.stringify(Spread$outboundSchema.parse(spread));
}

export function spreadFromJSON(
  jsonString: string,
): SafeParseResult<Spread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Spread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Spread' from JSON`,
  );
}

/** @internal */
export const Preference$inboundSchema: z.ZodType<
  Preference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => Spread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

/** @internal */
export type Preference$Outbound = {
  Spread: Spread$Outbound;
};

/** @internal */
export const Preference$outboundSchema: z.ZodType<
  Preference$Outbound,
  z.ZodTypeDef,
  Preference
> = z.object({
  spread: z.lazy(() => Spread$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    spread: "Spread",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Preference$ {
  /** @deprecated use `Preference$inboundSchema` instead. */
  export const inboundSchema = Preference$inboundSchema;
  /** @deprecated use `Preference$outboundSchema` instead. */
  export const outboundSchema = Preference$outboundSchema;
  /** @deprecated use `Preference$Outbound` instead. */
  export type Outbound = Preference$Outbound;
}

export function preferenceToJSON(preference: Preference): string {
  return JSON.stringify(Preference$outboundSchema.parse(preference));
}

export function preferenceFromJSON(
  jsonString: string,
): SafeParseResult<Preference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Preference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Preference' from JSON`,
  );
}

/** @internal */
export const Platform$inboundSchema: z.ZodType<
  Platform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

/** @internal */
export type Platform$Outbound = {
  Architecture: string;
  OS: string;
};

/** @internal */
export const Platform$outboundSchema: z.ZodType<
  Platform$Outbound,
  z.ZodTypeDef,
  Platform
> = z.object({
  architecture: z.string(),
  os: z.string(),
}).transform((v) => {
  return remap$(v, {
    architecture: "Architecture",
    os: "OS",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Platform$ {
  /** @deprecated use `Platform$inboundSchema` instead. */
  export const inboundSchema = Platform$inboundSchema;
  /** @deprecated use `Platform$outboundSchema` instead. */
  export const outboundSchema = Platform$outboundSchema;
  /** @deprecated use `Platform$Outbound` instead. */
  export type Outbound = Platform$Outbound;
}

export function platformToJSON(platform: Platform): string {
  return JSON.stringify(Platform$outboundSchema.parse(platform));
}

export function platformFromJSON(
  jsonString: string,
): SafeParseResult<Platform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Platform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Platform' from JSON`,
  );
}

/** @internal */
export const PlacementSwarm$inboundSchema: z.ZodType<
  PlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  Preferences: z.array(z.lazy(() => Preference$inboundSchema)).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => Platform$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "Preferences": "preferences",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
  });
});

/** @internal */
export type PlacementSwarm$Outbound = {
  Constraints?: Array<string> | undefined;
  Preferences?: Array<Preference$Outbound> | undefined;
  MaxReplicas?: number | undefined;
  Platforms?: Array<Platform$Outbound> | undefined;
};

/** @internal */
export const PlacementSwarm$outboundSchema: z.ZodType<
  PlacementSwarm$Outbound,
  z.ZodTypeDef,
  PlacementSwarm
> = z.object({
  constraints: z.array(z.string()).optional(),
  preferences: z.array(z.lazy(() => Preference$outboundSchema)).optional(),
  maxReplicas: z.number().optional(),
  platforms: z.array(z.lazy(() => Platform$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    constraints: "Constraints",
    preferences: "Preferences",
    maxReplicas: "MaxReplicas",
    platforms: "Platforms",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlacementSwarm$ {
  /** @deprecated use `PlacementSwarm$inboundSchema` instead. */
  export const inboundSchema = PlacementSwarm$inboundSchema;
  /** @deprecated use `PlacementSwarm$outboundSchema` instead. */
  export const outboundSchema = PlacementSwarm$outboundSchema;
  /** @deprecated use `PlacementSwarm$Outbound` instead. */
  export type Outbound = PlacementSwarm$Outbound;
}

export function placementSwarmToJSON(placementSwarm: PlacementSwarm): string {
  return JSON.stringify(PlacementSwarm$outboundSchema.parse(placementSwarm));
}

export function placementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlacementSwarm' from JSON`,
  );
}

/** @internal */
export const UpdateConfigSwarm$inboundSchema: z.ZodType<
  UpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Parallelism: z.number(),
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  Monitor: z.number().optional(),
  MaxFailureRatio: z.number().optional(),
  Order: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Parallelism": "parallelism",
    "Delay": "delay",
    "FailureAction": "failureAction",
    "Monitor": "monitor",
    "MaxFailureRatio": "maxFailureRatio",
    "Order": "order",
  });
});

/** @internal */
export type UpdateConfigSwarm$Outbound = {
  Parallelism: number;
  Delay?: number | undefined;
  FailureAction?: string | undefined;
  Monitor?: number | undefined;
  MaxFailureRatio?: number | undefined;
  Order: string;
};

/** @internal */
export const UpdateConfigSwarm$outboundSchema: z.ZodType<
  UpdateConfigSwarm$Outbound,
  z.ZodTypeDef,
  UpdateConfigSwarm
> = z.object({
  parallelism: z.number(),
  delay: z.number().optional(),
  failureAction: z.string().optional(),
  monitor: z.number().optional(),
  maxFailureRatio: z.number().optional(),
  order: z.string(),
}).transform((v) => {
  return remap$(v, {
    parallelism: "Parallelism",
    delay: "Delay",
    failureAction: "FailureAction",
    monitor: "Monitor",
    maxFailureRatio: "MaxFailureRatio",
    order: "Order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateConfigSwarm$ {
  /** @deprecated use `UpdateConfigSwarm$inboundSchema` instead. */
  export const inboundSchema = UpdateConfigSwarm$inboundSchema;
  /** @deprecated use `UpdateConfigSwarm$outboundSchema` instead. */
  export const outboundSchema = UpdateConfigSwarm$outboundSchema;
  /** @deprecated use `UpdateConfigSwarm$Outbound` instead. */
  export type Outbound = UpdateConfigSwarm$Outbound;
}

export function updateConfigSwarmToJSON(
  updateConfigSwarm: UpdateConfigSwarm,
): string {
  return JSON.stringify(
    UpdateConfigSwarm$outboundSchema.parse(updateConfigSwarm),
  );
}

export function updateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<UpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RollbackConfigSwarm$inboundSchema: z.ZodType<
  RollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Parallelism: z.number(),
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  Monitor: z.number().optional(),
  MaxFailureRatio: z.number().optional(),
  Order: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Parallelism": "parallelism",
    "Delay": "delay",
    "FailureAction": "failureAction",
    "Monitor": "monitor",
    "MaxFailureRatio": "maxFailureRatio",
    "Order": "order",
  });
});

/** @internal */
export type RollbackConfigSwarm$Outbound = {
  Parallelism: number;
  Delay?: number | undefined;
  FailureAction?: string | undefined;
  Monitor?: number | undefined;
  MaxFailureRatio?: number | undefined;
  Order: string;
};

/** @internal */
export const RollbackConfigSwarm$outboundSchema: z.ZodType<
  RollbackConfigSwarm$Outbound,
  z.ZodTypeDef,
  RollbackConfigSwarm
> = z.object({
  parallelism: z.number(),
  delay: z.number().optional(),
  failureAction: z.string().optional(),
  monitor: z.number().optional(),
  maxFailureRatio: z.number().optional(),
  order: z.string(),
}).transform((v) => {
  return remap$(v, {
    parallelism: "Parallelism",
    delay: "Delay",
    failureAction: "FailureAction",
    monitor: "Monitor",
    maxFailureRatio: "MaxFailureRatio",
    order: "Order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RollbackConfigSwarm$ {
  /** @deprecated use `RollbackConfigSwarm$inboundSchema` instead. */
  export const inboundSchema = RollbackConfigSwarm$inboundSchema;
  /** @deprecated use `RollbackConfigSwarm$outboundSchema` instead. */
  export const outboundSchema = RollbackConfigSwarm$outboundSchema;
  /** @deprecated use `RollbackConfigSwarm$Outbound` instead. */
  export type Outbound = RollbackConfigSwarm$Outbound;
}

export function rollbackConfigSwarmToJSON(
  rollbackConfigSwarm: RollbackConfigSwarm,
): string {
  return JSON.stringify(
    RollbackConfigSwarm$outboundSchema.parse(rollbackConfigSwarm),
  );
}

export function rollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const Replicated$inboundSchema: z.ZodType<
  Replicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

/** @internal */
export type Replicated$Outbound = {
  Replicas?: number | undefined;
};

/** @internal */
export const Replicated$outboundSchema: z.ZodType<
  Replicated$Outbound,
  z.ZodTypeDef,
  Replicated
> = z.object({
  replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    replicas: "Replicas",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Replicated$ {
  /** @deprecated use `Replicated$inboundSchema` instead. */
  export const inboundSchema = Replicated$inboundSchema;
  /** @deprecated use `Replicated$outboundSchema` instead. */
  export const outboundSchema = Replicated$outboundSchema;
  /** @deprecated use `Replicated$Outbound` instead. */
  export type Outbound = Replicated$Outbound;
}

export function replicatedToJSON(replicated: Replicated): string {
  return JSON.stringify(Replicated$outboundSchema.parse(replicated));
}

export function replicatedFromJSON(
  jsonString: string,
): SafeParseResult<Replicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Replicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Replicated' from JSON`,
  );
}

/** @internal */
export const Global$inboundSchema: z.ZodType<Global, z.ZodTypeDef, unknown> = z
  .object({});

/** @internal */
export type Global$Outbound = {};

/** @internal */
export const Global$outboundSchema: z.ZodType<
  Global$Outbound,
  z.ZodTypeDef,
  Global
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Global$ {
  /** @deprecated use `Global$inboundSchema` instead. */
  export const inboundSchema = Global$inboundSchema;
  /** @deprecated use `Global$outboundSchema` instead. */
  export const outboundSchema = Global$outboundSchema;
  /** @deprecated use `Global$Outbound` instead. */
  export type Outbound = Global$Outbound;
}

export function globalToJSON(global: Global): string {
  return JSON.stringify(Global$outboundSchema.parse(global));
}

export function globalFromJSON(
  jsonString: string,
): SafeParseResult<Global, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Global$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Global' from JSON`,
  );
}

/** @internal */
export const ReplicatedJob$inboundSchema: z.ZodType<
  ReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

/** @internal */
export type ReplicatedJob$Outbound = {
  MaxConcurrent?: number | undefined;
  TotalCompletions?: number | undefined;
};

/** @internal */
export const ReplicatedJob$outboundSchema: z.ZodType<
  ReplicatedJob$Outbound,
  z.ZodTypeDef,
  ReplicatedJob
> = z.object({
  maxConcurrent: z.number().optional(),
  totalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    maxConcurrent: "MaxConcurrent",
    totalCompletions: "TotalCompletions",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReplicatedJob$ {
  /** @deprecated use `ReplicatedJob$inboundSchema` instead. */
  export const inboundSchema = ReplicatedJob$inboundSchema;
  /** @deprecated use `ReplicatedJob$outboundSchema` instead. */
  export const outboundSchema = ReplicatedJob$outboundSchema;
  /** @deprecated use `ReplicatedJob$Outbound` instead. */
  export type Outbound = ReplicatedJob$Outbound;
}

export function replicatedJobToJSON(replicatedJob: ReplicatedJob): string {
  return JSON.stringify(ReplicatedJob$outboundSchema.parse(replicatedJob));
}

export function replicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<ReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReplicatedJob' from JSON`,
  );
}

/** @internal */
export const GlobalJob$inboundSchema: z.ZodType<
  GlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type GlobalJob$Outbound = {};

/** @internal */
export const GlobalJob$outboundSchema: z.ZodType<
  GlobalJob$Outbound,
  z.ZodTypeDef,
  GlobalJob
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GlobalJob$ {
  /** @deprecated use `GlobalJob$inboundSchema` instead. */
  export const inboundSchema = GlobalJob$inboundSchema;
  /** @deprecated use `GlobalJob$outboundSchema` instead. */
  export const outboundSchema = GlobalJob$outboundSchema;
  /** @deprecated use `GlobalJob$Outbound` instead. */
  export type Outbound = GlobalJob$Outbound;
}

export function globalJobToJSON(globalJob: GlobalJob): string {
  return JSON.stringify(GlobalJob$outboundSchema.parse(globalJob));
}

export function globalJobFromJSON(
  jsonString: string,
): SafeParseResult<GlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GlobalJob' from JSON`,
  );
}

/** @internal */
export const ModeSwarm$inboundSchema: z.ZodType<
  ModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicated: z.lazy(() => Replicated$inboundSchema).optional(),
  Global: z.lazy(() => Global$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => ReplicatedJob$inboundSchema).optional(),
  GlobalJob: z.lazy(() => GlobalJob$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicated": "replicated",
    "Global": "global",
    "ReplicatedJob": "replicatedJob",
    "GlobalJob": "globalJob",
  });
});

/** @internal */
export type ModeSwarm$Outbound = {
  Replicated?: Replicated$Outbound | undefined;
  Global?: Global$Outbound | undefined;
  ReplicatedJob?: ReplicatedJob$Outbound | undefined;
  GlobalJob?: GlobalJob$Outbound | undefined;
};

/** @internal */
export const ModeSwarm$outboundSchema: z.ZodType<
  ModeSwarm$Outbound,
  z.ZodTypeDef,
  ModeSwarm
> = z.object({
  replicated: z.lazy(() => Replicated$outboundSchema).optional(),
  global: z.lazy(() => Global$outboundSchema).optional(),
  replicatedJob: z.lazy(() => ReplicatedJob$outboundSchema).optional(),
  globalJob: z.lazy(() => GlobalJob$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    replicated: "Replicated",
    global: "Global",
    replicatedJob: "ReplicatedJob",
    globalJob: "GlobalJob",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModeSwarm$ {
  /** @deprecated use `ModeSwarm$inboundSchema` instead. */
  export const inboundSchema = ModeSwarm$inboundSchema;
  /** @deprecated use `ModeSwarm$outboundSchema` instead. */
  export const outboundSchema = ModeSwarm$outboundSchema;
  /** @deprecated use `ModeSwarm$Outbound` instead. */
  export type Outbound = ModeSwarm$Outbound;
}

export function modeSwarmToJSON(modeSwarm: ModeSwarm): string {
  return JSON.stringify(ModeSwarm$outboundSchema.parse(modeSwarm));
}

export function modeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModeSwarm' from JSON`,
  );
}

/** @internal */
export const DriverOpts$inboundSchema: z.ZodType<
  DriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type DriverOpts$Outbound = {};

/** @internal */
export const DriverOpts$outboundSchema: z.ZodType<
  DriverOpts$Outbound,
  z.ZodTypeDef,
  DriverOpts
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DriverOpts$ {
  /** @deprecated use `DriverOpts$inboundSchema` instead. */
  export const inboundSchema = DriverOpts$inboundSchema;
  /** @deprecated use `DriverOpts$outboundSchema` instead. */
  export const outboundSchema = DriverOpts$outboundSchema;
  /** @deprecated use `DriverOpts$Outbound` instead. */
  export type Outbound = DriverOpts$Outbound;
}

export function driverOptsToJSON(driverOpts: DriverOpts): string {
  return JSON.stringify(DriverOpts$outboundSchema.parse(driverOpts));
}

export function driverOptsFromJSON(
  jsonString: string,
): SafeParseResult<DriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DriverOpts' from JSON`,
  );
}

/** @internal */
export const NetworkSwarm$inboundSchema: z.ZodType<
  NetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Target: z.string().optional(),
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => DriverOpts$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Target": "target",
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
  });
});

/** @internal */
export type NetworkSwarm$Outbound = {
  Target?: string | undefined;
  Aliases?: Array<string> | undefined;
  DriverOpts?: DriverOpts$Outbound | undefined;
};

/** @internal */
export const NetworkSwarm$outboundSchema: z.ZodType<
  NetworkSwarm$Outbound,
  z.ZodTypeDef,
  NetworkSwarm
> = z.object({
  target: z.string().optional(),
  aliases: z.array(z.string()).optional(),
  driverOpts: z.lazy(() => DriverOpts$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    target: "Target",
    aliases: "Aliases",
    driverOpts: "DriverOpts",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NetworkSwarm$ {
  /** @deprecated use `NetworkSwarm$inboundSchema` instead. */
  export const inboundSchema = NetworkSwarm$inboundSchema;
  /** @deprecated use `NetworkSwarm$outboundSchema` instead. */
  export const outboundSchema = NetworkSwarm$outboundSchema;
  /** @deprecated use `NetworkSwarm$Outbound` instead. */
  export type Outbound = NetworkSwarm$Outbound;
}

export function networkSwarmToJSON(networkSwarm: NetworkSwarm): string {
  return JSON.stringify(NetworkSwarm$outboundSchema.parse(networkSwarm));
}

export function networkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationUpdateApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationUpdateApplicationStatus
> = z.nativeEnum(ApplicationUpdateApplicationStatus);

/** @internal */
export const ApplicationUpdateApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof ApplicationUpdateApplicationStatus
> = ApplicationUpdateApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationUpdateApplicationStatus$ {
  /** @deprecated use `ApplicationUpdateApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = ApplicationUpdateApplicationStatus$inboundSchema;
  /** @deprecated use `ApplicationUpdateApplicationStatus$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationUpdateApplicationStatus$outboundSchema;
}

/** @internal */
export const ApplicationUpdateBuildType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationUpdateBuildType
> = z.nativeEnum(ApplicationUpdateBuildType);

/** @internal */
export const ApplicationUpdateBuildType$outboundSchema: z.ZodNativeEnum<
  typeof ApplicationUpdateBuildType
> = ApplicationUpdateBuildType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationUpdateBuildType$ {
  /** @deprecated use `ApplicationUpdateBuildType$inboundSchema` instead. */
  export const inboundSchema = ApplicationUpdateBuildType$inboundSchema;
  /** @deprecated use `ApplicationUpdateBuildType$outboundSchema` instead. */
  export const outboundSchema = ApplicationUpdateBuildType$outboundSchema;
}

/** @internal */
export const ApplicationUpdateRequest$inboundSchema: z.ZodType<
  ApplicationUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  buildArgs: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  title: z.nullable(z.string()).optional(),
  enabled: z.nullable(z.boolean()).optional(),
  subtitle: z.nullable(z.string()).optional(),
  command: z.nullable(z.string()).optional(),
  refreshToken: z.nullable(z.string()).optional(),
  sourceType: ApplicationUpdateSourceType$inboundSchema.optional(),
  repository: z.nullable(z.string()).optional(),
  owner: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  buildPath: z.nullable(z.string()).optional(),
  autoDeploy: z.nullable(z.boolean()).optional(),
  gitlabProjectId: z.nullable(z.number()).optional(),
  gitlabRepository: z.nullable(z.string()).optional(),
  gitlabOwner: z.nullable(z.string()).optional(),
  gitlabBranch: z.nullable(z.string()).optional(),
  gitlabBuildPath: z.nullable(z.string()).optional(),
  gitlabPathNamespace: z.nullable(z.string()).optional(),
  bitbucketRepository: z.nullable(z.string()).optional(),
  bitbucketOwner: z.nullable(z.string()).optional(),
  bitbucketBranch: z.nullable(z.string()).optional(),
  bitbucketBuildPath: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
  dockerImage: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  customGitBranch: z.nullable(z.string()).optional(),
  customGitBuildPath: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
  dockerfile: z.nullable(z.string()).optional(),
  dockerContextPath: z.nullable(z.string()).optional(),
  dockerBuildStage: z.nullable(z.string()).optional(),
  dropBuildPath: z.nullable(z.string()).optional(),
  healthCheckSwarm: z.nullable(z.lazy(() => HealthCheckSwarm$inboundSchema))
    .optional(),
  restartPolicySwarm: z.nullable(z.lazy(() => RestartPolicySwarm$inboundSchema))
    .optional(),
  placementSwarm: z.nullable(z.lazy(() => PlacementSwarm$inboundSchema))
    .optional(),
  updateConfigSwarm: z.nullable(z.lazy(() => UpdateConfigSwarm$inboundSchema))
    .optional(),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => RollbackConfigSwarm$inboundSchema),
  ).optional(),
  modeSwarm: z.nullable(z.lazy(() => ModeSwarm$inboundSchema)).optional(),
  labelsSwarm: z.nullable(z.record(z.string())).optional(),
  networkSwarm: z.nullable(z.array(z.lazy(() => NetworkSwarm$inboundSchema)))
    .optional(),
  replicas: z.number().optional(),
  applicationStatus: ApplicationUpdateApplicationStatus$inboundSchema
    .optional(),
  buildType: ApplicationUpdateBuildType$inboundSchema.optional(),
  publishDirectory: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  registryId: z.nullable(z.string()).optional(),
  projectId: z.string().optional(),
  githubId: z.nullable(z.string()).optional(),
  gitlabId: z.nullable(z.string()).optional(),
  bitbucketId: z.nullable(z.string()).optional(),
});

/** @internal */
export type ApplicationUpdateRequest$Outbound = {
  applicationId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  env?: string | null | undefined;
  buildArgs?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  title?: string | null | undefined;
  enabled?: boolean | null | undefined;
  subtitle?: string | null | undefined;
  command?: string | null | undefined;
  refreshToken?: string | null | undefined;
  sourceType?: string | undefined;
  repository?: string | null | undefined;
  owner?: string | null | undefined;
  branch?: string | null | undefined;
  buildPath?: string | null | undefined;
  autoDeploy?: boolean | null | undefined;
  gitlabProjectId?: number | null | undefined;
  gitlabRepository?: string | null | undefined;
  gitlabOwner?: string | null | undefined;
  gitlabBranch?: string | null | undefined;
  gitlabBuildPath?: string | null | undefined;
  gitlabPathNamespace?: string | null | undefined;
  bitbucketRepository?: string | null | undefined;
  bitbucketOwner?: string | null | undefined;
  bitbucketBranch?: string | null | undefined;
  bitbucketBuildPath?: string | null | undefined;
  username?: string | null | undefined;
  password?: string | null | undefined;
  dockerImage?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  customGitBranch?: string | null | undefined;
  customGitBuildPath?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
  dockerfile?: string | null | undefined;
  dockerContextPath?: string | null | undefined;
  dockerBuildStage?: string | null | undefined;
  dropBuildPath?: string | null | undefined;
  healthCheckSwarm?: HealthCheckSwarm$Outbound | null | undefined;
  restartPolicySwarm?: RestartPolicySwarm$Outbound | null | undefined;
  placementSwarm?: PlacementSwarm$Outbound | null | undefined;
  updateConfigSwarm?: UpdateConfigSwarm$Outbound | null | undefined;
  rollbackConfigSwarm?: RollbackConfigSwarm$Outbound | null | undefined;
  modeSwarm?: ModeSwarm$Outbound | null | undefined;
  labelsSwarm?: { [k: string]: string } | null | undefined;
  networkSwarm?: Array<NetworkSwarm$Outbound> | null | undefined;
  replicas?: number | undefined;
  applicationStatus?: string | undefined;
  buildType?: string | undefined;
  publishDirectory?: string | null | undefined;
  createdAt?: string | undefined;
  registryId?: string | null | undefined;
  projectId?: string | undefined;
  githubId?: string | null | undefined;
  gitlabId?: string | null | undefined;
  bitbucketId?: string | null | undefined;
};

/** @internal */
export const ApplicationUpdateRequest$outboundSchema: z.ZodType<
  ApplicationUpdateRequest$Outbound,
  z.ZodTypeDef,
  ApplicationUpdateRequest
> = z.object({
  applicationId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  buildArgs: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  title: z.nullable(z.string()).optional(),
  enabled: z.nullable(z.boolean()).optional(),
  subtitle: z.nullable(z.string()).optional(),
  command: z.nullable(z.string()).optional(),
  refreshToken: z.nullable(z.string()).optional(),
  sourceType: ApplicationUpdateSourceType$outboundSchema.optional(),
  repository: z.nullable(z.string()).optional(),
  owner: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  buildPath: z.nullable(z.string()).optional(),
  autoDeploy: z.nullable(z.boolean()).optional(),
  gitlabProjectId: z.nullable(z.number()).optional(),
  gitlabRepository: z.nullable(z.string()).optional(),
  gitlabOwner: z.nullable(z.string()).optional(),
  gitlabBranch: z.nullable(z.string()).optional(),
  gitlabBuildPath: z.nullable(z.string()).optional(),
  gitlabPathNamespace: z.nullable(z.string()).optional(),
  bitbucketRepository: z.nullable(z.string()).optional(),
  bitbucketOwner: z.nullable(z.string()).optional(),
  bitbucketBranch: z.nullable(z.string()).optional(),
  bitbucketBuildPath: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
  dockerImage: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  customGitBranch: z.nullable(z.string()).optional(),
  customGitBuildPath: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
  dockerfile: z.nullable(z.string()).optional(),
  dockerContextPath: z.nullable(z.string()).optional(),
  dockerBuildStage: z.nullable(z.string()).optional(),
  dropBuildPath: z.nullable(z.string()).optional(),
  healthCheckSwarm: z.nullable(z.lazy(() => HealthCheckSwarm$outboundSchema))
    .optional(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => RestartPolicySwarm$outboundSchema),
  ).optional(),
  placementSwarm: z.nullable(z.lazy(() => PlacementSwarm$outboundSchema))
    .optional(),
  updateConfigSwarm: z.nullable(z.lazy(() => UpdateConfigSwarm$outboundSchema))
    .optional(),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => RollbackConfigSwarm$outboundSchema),
  ).optional(),
  modeSwarm: z.nullable(z.lazy(() => ModeSwarm$outboundSchema)).optional(),
  labelsSwarm: z.nullable(z.record(z.string())).optional(),
  networkSwarm: z.nullable(z.array(z.lazy(() => NetworkSwarm$outboundSchema)))
    .optional(),
  replicas: z.number().optional(),
  applicationStatus: ApplicationUpdateApplicationStatus$outboundSchema
    .optional(),
  buildType: ApplicationUpdateBuildType$outboundSchema.optional(),
  publishDirectory: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  registryId: z.nullable(z.string()).optional(),
  projectId: z.string().optional(),
  githubId: z.nullable(z.string()).optional(),
  gitlabId: z.nullable(z.string()).optional(),
  bitbucketId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationUpdateRequest$ {
  /** @deprecated use `ApplicationUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationUpdateRequest$inboundSchema;
  /** @deprecated use `ApplicationUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationUpdateRequest$outboundSchema;
  /** @deprecated use `ApplicationUpdateRequest$Outbound` instead. */
  export type Outbound = ApplicationUpdateRequest$Outbound;
}

export function applicationUpdateRequestToJSON(
  applicationUpdateRequest: ApplicationUpdateRequest,
): string {
  return JSON.stringify(
    ApplicationUpdateRequest$outboundSchema.parse(applicationUpdateRequest),
  );
}

export function applicationUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationUpdateRequest' from JSON`,
  );
}
