/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationStopRequest = {
  applicationId: string;
};

/** @internal */
export const ApplicationStopRequest$inboundSchema: z.ZodType<
  ApplicationStopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
});

/** @internal */
export type ApplicationStopRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationStopRequest$outboundSchema: z.ZodType<
  ApplicationStopRequest$Outbound,
  z.ZodTypeDef,
  ApplicationStopRequest
> = z.object({
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationStopRequest$ {
  /** @deprecated use `ApplicationStopRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationStopRequest$inboundSchema;
  /** @deprecated use `ApplicationStopRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationStopRequest$outboundSchema;
  /** @deprecated use `ApplicationStopRequest$Outbound` instead. */
  export type Outbound = ApplicationStopRequest$Outbound;
}

export function applicationStopRequestToJSON(
  applicationStopRequest: ApplicationStopRequest,
): string {
  return JSON.stringify(
    ApplicationStopRequest$outboundSchema.parse(applicationStopRequest),
  );
}

export function applicationStopRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStopRequest' from JSON`,
  );
}
