/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationSaveBitbucketProviderRequest = {
  bitbucketBranch: string | null;
  bitbucketBuildPath: string | null;
  bitbucketOwner: string | null;
  bitbucketRepository: string | null;
  bitbucketId: string | null;
  applicationId: string;
};

/** @internal */
export const ApplicationSaveBitbucketProviderRequest$inboundSchema: z.ZodType<
  ApplicationSaveBitbucketProviderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  bitbucketBranch: z.nullable(z.string()),
  bitbucketBuildPath: z.nullable(z.string()),
  bitbucketOwner: z.nullable(z.string()),
  bitbucketRepository: z.nullable(z.string()),
  bitbucketId: z.nullable(z.string()),
  applicationId: z.string(),
});

/** @internal */
export type ApplicationSaveBitbucketProviderRequest$Outbound = {
  bitbucketBranch: string | null;
  bitbucketBuildPath: string | null;
  bitbucketOwner: string | null;
  bitbucketRepository: string | null;
  bitbucketId: string | null;
  applicationId: string;
};

/** @internal */
export const ApplicationSaveBitbucketProviderRequest$outboundSchema: z.ZodType<
  ApplicationSaveBitbucketProviderRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveBitbucketProviderRequest
> = z.object({
  bitbucketBranch: z.nullable(z.string()),
  bitbucketBuildPath: z.nullable(z.string()),
  bitbucketOwner: z.nullable(z.string()),
  bitbucketRepository: z.nullable(z.string()),
  bitbucketId: z.nullable(z.string()),
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveBitbucketProviderRequest$ {
  /** @deprecated use `ApplicationSaveBitbucketProviderRequest$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationSaveBitbucketProviderRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveBitbucketProviderRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveBitbucketProviderRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveBitbucketProviderRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveBitbucketProviderRequest$Outbound;
}

export function applicationSaveBitbucketProviderRequestToJSON(
  applicationSaveBitbucketProviderRequest:
    ApplicationSaveBitbucketProviderRequest,
): string {
  return JSON.stringify(
    ApplicationSaveBitbucketProviderRequest$outboundSchema.parse(
      applicationSaveBitbucketProviderRequest,
    ),
  );
}

export function applicationSaveBitbucketProviderRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ApplicationSaveBitbucketProviderRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationSaveBitbucketProviderRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApplicationSaveBitbucketProviderRequest' from JSON`,
  );
}
