/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationSaveDockerProviderRequest = {
  dockerImage?: string | null | undefined;
  applicationId: string;
  username?: string | null | undefined;
  password?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveDockerProviderRequest$inboundSchema: z.ZodType<
  ApplicationSaveDockerProviderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  dockerImage: z.nullable(z.string()).optional(),
  applicationId: z.string(),
  username: z.nullable(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
});

/** @internal */
export type ApplicationSaveDockerProviderRequest$Outbound = {
  dockerImage?: string | null | undefined;
  applicationId: string;
  username?: string | null | undefined;
  password?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveDockerProviderRequest$outboundSchema: z.ZodType<
  ApplicationSaveDockerProviderRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveDockerProviderRequest
> = z.object({
  dockerImage: z.nullable(z.string()).optional(),
  applicationId: z.string(),
  username: z.nullable(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveDockerProviderRequest$ {
  /** @deprecated use `ApplicationSaveDockerProviderRequest$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationSaveDockerProviderRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveDockerProviderRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveDockerProviderRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveDockerProviderRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveDockerProviderRequest$Outbound;
}

export function applicationSaveDockerProviderRequestToJSON(
  applicationSaveDockerProviderRequest: ApplicationSaveDockerProviderRequest,
): string {
  return JSON.stringify(
    ApplicationSaveDockerProviderRequest$outboundSchema.parse(
      applicationSaveDockerProviderRequest,
    ),
  );
}

export function applicationSaveDockerProviderRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationSaveDockerProviderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationSaveDockerProviderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationSaveDockerProviderRequest' from JSON`,
  );
}
