/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationDeleteRequest = {
  applicationId: string;
};

/** @internal */
export const ApplicationDeleteRequest$inboundSchema: z.ZodType<
  ApplicationDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
});

/** @internal */
export type ApplicationDeleteRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationDeleteRequest$outboundSchema: z.ZodType<
  ApplicationDeleteRequest$Outbound,
  z.ZodTypeDef,
  ApplicationDeleteRequest
> = z.object({
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationDeleteRequest$ {
  /** @deprecated use `ApplicationDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationDeleteRequest$inboundSchema;
  /** @deprecated use `ApplicationDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationDeleteRequest$outboundSchema;
  /** @deprecated use `ApplicationDeleteRequest$Outbound` instead. */
  export type Outbound = ApplicationDeleteRequest$Outbound;
}

export function applicationDeleteRequestToJSON(
  applicationDeleteRequest: ApplicationDeleteRequest,
): string {
  return JSON.stringify(
    ApplicationDeleteRequest$outboundSchema.parse(applicationDeleteRequest),
  );
}

export function applicationDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationDeleteRequest' from JSON`,
  );
}
