/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationSaveGitlabProviderRequest = {
  applicationId: string;
  gitlabBranch: string | null;
  gitlabBuildPath: string | null;
  gitlabOwner: string | null;
  gitlabRepository: string | null;
  gitlabId: string | null;
  gitlabProjectId: number | null;
  gitlabPathNamespace: string | null;
};

/** @internal */
export const ApplicationSaveGitlabProviderRequest$inboundSchema: z.ZodType<
  ApplicationSaveGitlabProviderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  gitlabBranch: z.nullable(z.string()),
  gitlabBuildPath: z.nullable(z.string()),
  gitlabOwner: z.nullable(z.string()),
  gitlabRepository: z.nullable(z.string()),
  gitlabId: z.nullable(z.string()),
  gitlabProjectId: z.nullable(z.number()),
  gitlabPathNamespace: z.nullable(z.string()),
});

/** @internal */
export type ApplicationSaveGitlabProviderRequest$Outbound = {
  applicationId: string;
  gitlabBranch: string | null;
  gitlabBuildPath: string | null;
  gitlabOwner: string | null;
  gitlabRepository: string | null;
  gitlabId: string | null;
  gitlabProjectId: number | null;
  gitlabPathNamespace: string | null;
};

/** @internal */
export const ApplicationSaveGitlabProviderRequest$outboundSchema: z.ZodType<
  ApplicationSaveGitlabProviderRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveGitlabProviderRequest
> = z.object({
  applicationId: z.string(),
  gitlabBranch: z.nullable(z.string()),
  gitlabBuildPath: z.nullable(z.string()),
  gitlabOwner: z.nullable(z.string()),
  gitlabRepository: z.nullable(z.string()),
  gitlabId: z.nullable(z.string()),
  gitlabProjectId: z.nullable(z.number()),
  gitlabPathNamespace: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveGitlabProviderRequest$ {
  /** @deprecated use `ApplicationSaveGitlabProviderRequest$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationSaveGitlabProviderRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveGitlabProviderRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveGitlabProviderRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveGitlabProviderRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveGitlabProviderRequest$Outbound;
}

export function applicationSaveGitlabProviderRequestToJSON(
  applicationSaveGitlabProviderRequest: ApplicationSaveGitlabProviderRequest,
): string {
  return JSON.stringify(
    ApplicationSaveGitlabProviderRequest$outboundSchema.parse(
      applicationSaveGitlabProviderRequest,
    ),
  );
}

export function applicationSaveGitlabProviderRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationSaveGitlabProviderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationSaveGitlabProviderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationSaveGitlabProviderRequest' from JSON`,
  );
}
