/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationCreateRequest = {
  name: string;
  appName?: string | undefined;
  description?: string | null | undefined;
  projectId: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const ApplicationCreateRequest$inboundSchema: z.ZodType<
  ApplicationCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  projectId: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

/** @internal */
export type ApplicationCreateRequest$Outbound = {
  name: string;
  appName?: string | undefined;
  description?: string | null | undefined;
  projectId: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const ApplicationCreateRequest$outboundSchema: z.ZodType<
  ApplicationCreateRequest$Outbound,
  z.ZodTypeDef,
  ApplicationCreateRequest
> = z.object({
  name: z.string(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  projectId: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationCreateRequest$ {
  /** @deprecated use `ApplicationCreateRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationCreateRequest$inboundSchema;
  /** @deprecated use `ApplicationCreateRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationCreateRequest$outboundSchema;
  /** @deprecated use `ApplicationCreateRequest$Outbound` instead. */
  export type Outbound = ApplicationCreateRequest$Outbound;
}

export function applicationCreateRequestToJSON(
  applicationCreateRequest: ApplicationCreateRequest,
): string {
  return JSON.stringify(
    ApplicationCreateRequest$outboundSchema.parse(applicationCreateRequest),
  );
}

export function applicationCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationCreateRequest' from JSON`,
  );
}
