/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationSaveEnvironmentRequest = {
  applicationId: string;
  env?: string | null | undefined;
  buildArgs?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveEnvironmentRequest$inboundSchema: z.ZodType<
  ApplicationSaveEnvironmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  env: z.nullable(z.string()).optional(),
  buildArgs: z.nullable(z.string()).optional(),
});

/** @internal */
export type ApplicationSaveEnvironmentRequest$Outbound = {
  applicationId: string;
  env?: string | null | undefined;
  buildArgs?: string | null | undefined;
};

/** @internal */
export const ApplicationSaveEnvironmentRequest$outboundSchema: z.ZodType<
  ApplicationSaveEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  ApplicationSaveEnvironmentRequest
> = z.object({
  applicationId: z.string(),
  env: z.nullable(z.string()).optional(),
  buildArgs: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSaveEnvironmentRequest$ {
  /** @deprecated use `ApplicationSaveEnvironmentRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationSaveEnvironmentRequest$inboundSchema;
  /** @deprecated use `ApplicationSaveEnvironmentRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationSaveEnvironmentRequest$outboundSchema;
  /** @deprecated use `ApplicationSaveEnvironmentRequest$Outbound` instead. */
  export type Outbound = ApplicationSaveEnvironmentRequest$Outbound;
}

export function applicationSaveEnvironmentRequestToJSON(
  applicationSaveEnvironmentRequest: ApplicationSaveEnvironmentRequest,
): string {
  return JSON.stringify(
    ApplicationSaveEnvironmentRequest$outboundSchema.parse(
      applicationSaveEnvironmentRequest,
    ),
  );
}

export function applicationSaveEnvironmentRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationSaveEnvironmentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationSaveEnvironmentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationSaveEnvironmentRequest' from JSON`,
  );
}
