/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationReloadRequest = {
  appName: string;
  applicationId: string;
};

/** @internal */
export const ApplicationReloadRequest$inboundSchema: z.ZodType<
  ApplicationReloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationId: z.string(),
});

/** @internal */
export type ApplicationReloadRequest$Outbound = {
  appName: string;
  applicationId: string;
};

/** @internal */
export const ApplicationReloadRequest$outboundSchema: z.ZodType<
  ApplicationReloadRequest$Outbound,
  z.ZodTypeDef,
  ApplicationReloadRequest
> = z.object({
  appName: z.string(),
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationReloadRequest$ {
  /** @deprecated use `ApplicationReloadRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationReloadRequest$inboundSchema;
  /** @deprecated use `ApplicationReloadRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationReloadRequest$outboundSchema;
  /** @deprecated use `ApplicationReloadRequest$Outbound` instead. */
  export type Outbound = ApplicationReloadRequest$Outbound;
}

export function applicationReloadRequestToJSON(
  applicationReloadRequest: ApplicationReloadRequest,
): string {
  return JSON.stringify(
    ApplicationReloadRequest$outboundSchema.parse(applicationReloadRequest),
  );
}

export function applicationReloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationReloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationReloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationReloadRequest' from JSON`,
  );
}
