/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationOneRequest = {
  applicationId: string;
};

/** @internal */
export const ApplicationOneRequest$inboundSchema: z.ZodType<
  ApplicationOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
});

/** @internal */
export type ApplicationOneRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationOneRequest$outboundSchema: z.ZodType<
  ApplicationOneRequest$Outbound,
  z.ZodTypeDef,
  ApplicationOneRequest
> = z.object({
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationOneRequest$ {
  /** @deprecated use `ApplicationOneRequest$inboundSchema` instead. */
  export const inboundSchema = ApplicationOneRequest$inboundSchema;
  /** @deprecated use `ApplicationOneRequest$outboundSchema` instead. */
  export const outboundSchema = ApplicationOneRequest$outboundSchema;
  /** @deprecated use `ApplicationOneRequest$Outbound` instead. */
  export type Outbound = ApplicationOneRequest$Outbound;
}

export function applicationOneRequestToJSON(
  applicationOneRequest: ApplicationOneRequest,
): string {
  return JSON.stringify(
    ApplicationOneRequest$outboundSchema.parse(applicationOneRequest),
  );
}

export function applicationOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationOneRequest' from JSON`,
  );
}
