/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationReadAppMonitoringRequest = {
  appName: string;
};

/** @internal */
export const ApplicationReadAppMonitoringRequest$inboundSchema: z.ZodType<
  ApplicationReadAppMonitoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
});

/** @internal */
export type ApplicationReadAppMonitoringRequest$Outbound = {
  appName: string;
};

/** @internal */
export const ApplicationReadAppMonitoringRequest$outboundSchema: z.ZodType<
  ApplicationReadAppMonitoringRequest$Outbound,
  z.ZodTypeDef,
  ApplicationReadAppMonitoringRequest
> = z.object({
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationReadAppMonitoringRequest$ {
  /** @deprecated use `ApplicationReadAppMonitoringRequest$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationReadAppMonitoringRequest$inboundSchema;
  /** @deprecated use `ApplicationReadAppMonitoringRequest$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationReadAppMonitoringRequest$outboundSchema;
  /** @deprecated use `ApplicationReadAppMonitoringRequest$Outbound` instead. */
  export type Outbound = ApplicationReadAppMonitoringRequest$Outbound;
}

export function applicationReadAppMonitoringRequestToJSON(
  applicationReadAppMonitoringRequest: ApplicationReadAppMonitoringRequest,
): string {
  return JSON.stringify(
    ApplicationReadAppMonitoringRequest$outboundSchema.parse(
      applicationReadAppMonitoringRequest,
    ),
  );
}

export function applicationReadAppMonitoringRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationReadAppMonitoringRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationReadAppMonitoringRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationReadAppMonitoringRequest' from JSON`,
  );
}
