/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthVerify2FASetupRequest = {
  pin: string;
  secret: string;
};

/** @internal */
export const AuthVerify2FASetupRequest$inboundSchema: z.ZodType<
  AuthVerify2FASetupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pin: z.string(),
  secret: z.string(),
});

/** @internal */
export type AuthVerify2FASetupRequest$Outbound = {
  pin: string;
  secret: string;
};

/** @internal */
export const AuthVerify2FASetupRequest$outboundSchema: z.ZodType<
  AuthVerify2FASetupRequest$Outbound,
  z.ZodTypeDef,
  AuthVerify2FASetupRequest
> = z.object({
  pin: z.string(),
  secret: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthVerify2FASetupRequest$ {
  /** @deprecated use `AuthVerify2FASetupRequest$inboundSchema` instead. */
  export const inboundSchema = AuthVerify2FASetupRequest$inboundSchema;
  /** @deprecated use `AuthVerify2FASetupRequest$outboundSchema` instead. */
  export const outboundSchema = AuthVerify2FASetupRequest$outboundSchema;
  /** @deprecated use `AuthVerify2FASetupRequest$Outbound` instead. */
  export type Outbound = AuthVerify2FASetupRequest$Outbound;
}

export function authVerify2FASetupRequestToJSON(
  authVerify2FASetupRequest: AuthVerify2FASetupRequest,
): string {
  return JSON.stringify(
    AuthVerify2FASetupRequest$outboundSchema.parse(authVerify2FASetupRequest),
  );
}

export function authVerify2FASetupRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthVerify2FASetupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthVerify2FASetupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthVerify2FASetupRequest' from JSON`,
  );
}
