/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthVerifyLogin2FARequest = {
  pin: string;
  id: string;
};

/** @internal */
export const AuthVerifyLogin2FARequest$inboundSchema: z.ZodType<
  AuthVerifyLogin2FARequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pin: z.string(),
  id: z.string(),
});

/** @internal */
export type AuthVerifyLogin2FARequest$Outbound = {
  pin: string;
  id: string;
};

/** @internal */
export const AuthVerifyLogin2FARequest$outboundSchema: z.ZodType<
  AuthVerifyLogin2FARequest$Outbound,
  z.ZodTypeDef,
  AuthVerifyLogin2FARequest
> = z.object({
  pin: z.string(),
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthVerifyLogin2FARequest$ {
  /** @deprecated use `AuthVerifyLogin2FARequest$inboundSchema` instead. */
  export const inboundSchema = AuthVerifyLogin2FARequest$inboundSchema;
  /** @deprecated use `AuthVerifyLogin2FARequest$outboundSchema` instead. */
  export const outboundSchema = AuthVerifyLogin2FARequest$outboundSchema;
  /** @deprecated use `AuthVerifyLogin2FARequest$Outbound` instead. */
  export type Outbound = AuthVerifyLogin2FARequest$Outbound;
}

export function authVerifyLogin2FARequestToJSON(
  authVerifyLogin2FARequest: AuthVerifyLogin2FARequest,
): string {
  return JSON.stringify(
    AuthVerifyLogin2FARequest$outboundSchema.parse(authVerifyLogin2FARequest),
  );
}

export function authVerifyLogin2FARequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthVerifyLogin2FARequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthVerifyLogin2FARequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthVerifyLogin2FARequest' from JSON`,
  );
}
