/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthSendResetPasswordEmailRequest = {
  email: string;
};

/** @internal */
export const AuthSendResetPasswordEmailRequest$inboundSchema: z.ZodType<
  AuthSendResetPasswordEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
});

/** @internal */
export type AuthSendResetPasswordEmailRequest$Outbound = {
  email: string;
};

/** @internal */
export const AuthSendResetPasswordEmailRequest$outboundSchema: z.ZodType<
  AuthSendResetPasswordEmailRequest$Outbound,
  z.ZodTypeDef,
  AuthSendResetPasswordEmailRequest
> = z.object({
  email: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthSendResetPasswordEmailRequest$ {
  /** @deprecated use `AuthSendResetPasswordEmailRequest$inboundSchema` instead. */
  export const inboundSchema = AuthSendResetPasswordEmailRequest$inboundSchema;
  /** @deprecated use `AuthSendResetPasswordEmailRequest$outboundSchema` instead. */
  export const outboundSchema =
    AuthSendResetPasswordEmailRequest$outboundSchema;
  /** @deprecated use `AuthSendResetPasswordEmailRequest$Outbound` instead. */
  export type Outbound = AuthSendResetPasswordEmailRequest$Outbound;
}

export function authSendResetPasswordEmailRequestToJSON(
  authSendResetPasswordEmailRequest: AuthSendResetPasswordEmailRequest,
): string {
  return JSON.stringify(
    AuthSendResetPasswordEmailRequest$outboundSchema.parse(
      authSendResetPasswordEmailRequest,
    ),
  );
}

export function authSendResetPasswordEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthSendResetPasswordEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthSendResetPasswordEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthSendResetPasswordEmailRequest' from JSON`,
  );
}
