/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthLoginRequest = {
  email: string;
  password: string;
};

/** @internal */
export const AuthLoginRequest$inboundSchema: z.ZodType<
  AuthLoginRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  password: z.string(),
});

/** @internal */
export type AuthLoginRequest$Outbound = {
  email: string;
  password: string;
};

/** @internal */
export const AuthLoginRequest$outboundSchema: z.ZodType<
  AuthLoginRequest$Outbound,
  z.ZodTypeDef,
  AuthLoginRequest
> = z.object({
  email: z.string(),
  password: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthLoginRequest$ {
  /** @deprecated use `AuthLoginRequest$inboundSchema` instead. */
  export const inboundSchema = AuthLoginRequest$inboundSchema;
  /** @deprecated use `AuthLoginRequest$outboundSchema` instead. */
  export const outboundSchema = AuthLoginRequest$outboundSchema;
  /** @deprecated use `AuthLoginRequest$Outbound` instead. */
  export type Outbound = AuthLoginRequest$Outbound;
}

export function authLoginRequestToJSON(
  authLoginRequest: AuthLoginRequest,
): string {
  return JSON.stringify(
    AuthLoginRequest$outboundSchema.parse(authLoginRequest),
  );
}

export function authLoginRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthLoginRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthLoginRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthLoginRequest' from JSON`,
  );
}
