/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthOneRequest = {
  id: string;
};

/** @internal */
export const AuthOneRequest$inboundSchema: z.ZodType<
  AuthOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type AuthOneRequest$Outbound = {
  id: string;
};

/** @internal */
export const AuthOneRequest$outboundSchema: z.ZodType<
  AuthOneRequest$Outbound,
  z.ZodTypeDef,
  AuthOneRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthOneRequest$ {
  /** @deprecated use `AuthOneRequest$inboundSchema` instead. */
  export const inboundSchema = AuthOneRequest$inboundSchema;
  /** @deprecated use `AuthOneRequest$outboundSchema` instead. */
  export const outboundSchema = AuthOneRequest$outboundSchema;
  /** @deprecated use `AuthOneRequest$Outbound` instead. */
  export type Outbound = AuthOneRequest$Outbound;
}

export function authOneRequestToJSON(authOneRequest: AuthOneRequest): string {
  return JSON.stringify(AuthOneRequest$outboundSchema.parse(authOneRequest));
}

export function authOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthOneRequest' from JSON`,
  );
}
