/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Rol = {
  Admin: "admin",
  User: "user",
} as const;
export type Rol = ClosedEnum<typeof Rol>;

export type AuthUpdateRequest = {
  id?: string | undefined;
  email: string | null;
  password: string | null;
  rol?: Rol | undefined;
  image?: string | undefined;
  secret?: string | null | undefined;
  token?: string | null | undefined;
  is2FAEnabled?: boolean | undefined;
  createdAt?: string | undefined;
  resetPasswordToken?: string | null | undefined;
  resetPasswordExpiresAt?: string | null | undefined;
  confirmationToken?: string | null | undefined;
  confirmationExpiresAt?: string | null | undefined;
};

/** @internal */
export const Rol$inboundSchema: z.ZodNativeEnum<typeof Rol> = z.nativeEnum(Rol);

/** @internal */
export const Rol$outboundSchema: z.ZodNativeEnum<typeof Rol> =
  Rol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Rol$ {
  /** @deprecated use `Rol$inboundSchema` instead. */
  export const inboundSchema = Rol$inboundSchema;
  /** @deprecated use `Rol$outboundSchema` instead. */
  export const outboundSchema = Rol$outboundSchema;
}

/** @internal */
export const AuthUpdateRequest$inboundSchema: z.ZodType<
  AuthUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  email: z.nullable(z.string()),
  password: z.nullable(z.string()),
  rol: Rol$inboundSchema.optional(),
  image: z.string().optional(),
  secret: z.nullable(z.string()).optional(),
  token: z.nullable(z.string()).optional(),
  is2FAEnabled: z.boolean().optional(),
  createdAt: z.string().optional(),
  resetPasswordToken: z.nullable(z.string()).optional(),
  resetPasswordExpiresAt: z.nullable(z.string()).optional(),
  confirmationToken: z.nullable(z.string()).optional(),
  confirmationExpiresAt: z.nullable(z.string()).optional(),
});

/** @internal */
export type AuthUpdateRequest$Outbound = {
  id?: string | undefined;
  email: string | null;
  password: string | null;
  rol?: string | undefined;
  image?: string | undefined;
  secret?: string | null | undefined;
  token?: string | null | undefined;
  is2FAEnabled?: boolean | undefined;
  createdAt?: string | undefined;
  resetPasswordToken?: string | null | undefined;
  resetPasswordExpiresAt?: string | null | undefined;
  confirmationToken?: string | null | undefined;
  confirmationExpiresAt?: string | null | undefined;
};

/** @internal */
export const AuthUpdateRequest$outboundSchema: z.ZodType<
  AuthUpdateRequest$Outbound,
  z.ZodTypeDef,
  AuthUpdateRequest
> = z.object({
  id: z.string().optional(),
  email: z.nullable(z.string()),
  password: z.nullable(z.string()),
  rol: Rol$outboundSchema.optional(),
  image: z.string().optional(),
  secret: z.nullable(z.string()).optional(),
  token: z.nullable(z.string()).optional(),
  is2FAEnabled: z.boolean().optional(),
  createdAt: z.string().optional(),
  resetPasswordToken: z.nullable(z.string()).optional(),
  resetPasswordExpiresAt: z.nullable(z.string()).optional(),
  confirmationToken: z.nullable(z.string()).optional(),
  confirmationExpiresAt: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthUpdateRequest$ {
  /** @deprecated use `AuthUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = AuthUpdateRequest$inboundSchema;
  /** @deprecated use `AuthUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = AuthUpdateRequest$outboundSchema;
  /** @deprecated use `AuthUpdateRequest$Outbound` instead. */
  export type Outbound = AuthUpdateRequest$Outbound;
}

export function authUpdateRequestToJSON(
  authUpdateRequest: AuthUpdateRequest,
): string {
  return JSON.stringify(
    AuthUpdateRequest$outboundSchema.parse(authUpdateRequest),
  );
}

export function authUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthUpdateRequest' from JSON`,
  );
}
