/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthCreateUserRequest = {
  password: string;
  id: string;
  token: string;
};

/** @internal */
export const AuthCreateUserRequest$inboundSchema: z.ZodType<
  AuthCreateUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  password: z.string(),
  id: z.string(),
  token: z.string(),
});

/** @internal */
export type AuthCreateUserRequest$Outbound = {
  password: string;
  id: string;
  token: string;
};

/** @internal */
export const AuthCreateUserRequest$outboundSchema: z.ZodType<
  AuthCreateUserRequest$Outbound,
  z.ZodTypeDef,
  AuthCreateUserRequest
> = z.object({
  password: z.string(),
  id: z.string(),
  token: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthCreateUserRequest$ {
  /** @deprecated use `AuthCreateUserRequest$inboundSchema` instead. */
  export const inboundSchema = AuthCreateUserRequest$inboundSchema;
  /** @deprecated use `AuthCreateUserRequest$outboundSchema` instead. */
  export const outboundSchema = AuthCreateUserRequest$outboundSchema;
  /** @deprecated use `AuthCreateUserRequest$Outbound` instead. */
  export type Outbound = AuthCreateUserRequest$Outbound;
}

export function authCreateUserRequestToJSON(
  authCreateUserRequest: AuthCreateUserRequest,
): string {
  return JSON.stringify(
    AuthCreateUserRequest$outboundSchema.parse(authCreateUserRequest),
  );
}

export function authCreateUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthCreateUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthCreateUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthCreateUserRequest' from JSON`,
  );
}
