/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthConfirmEmailRequest = {
  confirmationToken: string;
};

/** @internal */
export const AuthConfirmEmailRequest$inboundSchema: z.ZodType<
  AuthConfirmEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  confirmationToken: z.string(),
});

/** @internal */
export type AuthConfirmEmailRequest$Outbound = {
  confirmationToken: string;
};

/** @internal */
export const AuthConfirmEmailRequest$outboundSchema: z.ZodType<
  AuthConfirmEmailRequest$Outbound,
  z.ZodTypeDef,
  AuthConfirmEmailRequest
> = z.object({
  confirmationToken: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthConfirmEmailRequest$ {
  /** @deprecated use `AuthConfirmEmailRequest$inboundSchema` instead. */
  export const inboundSchema = AuthConfirmEmailRequest$inboundSchema;
  /** @deprecated use `AuthConfirmEmailRequest$outboundSchema` instead. */
  export const outboundSchema = AuthConfirmEmailRequest$outboundSchema;
  /** @deprecated use `AuthConfirmEmailRequest$Outbound` instead. */
  export type Outbound = AuthConfirmEmailRequest$Outbound;
}

export function authConfirmEmailRequestToJSON(
  authConfirmEmailRequest: AuthConfirmEmailRequest,
): string {
  return JSON.stringify(
    AuthConfirmEmailRequest$outboundSchema.parse(authConfirmEmailRequest),
  );
}

export function authConfirmEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthConfirmEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthConfirmEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthConfirmEmailRequest' from JSON`,
  );
}
