/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
} as const;
export type DatabaseType = ClosedEnum<typeof DatabaseType>;

export type BackupCreateRequest = {
  schedule: string;
  enabled?: boolean | null | undefined;
  prefix: string;
  destinationId: string;
  database: string;
  mariadbId?: string | null | undefined;
  mysqlId?: string | null | undefined;
  postgresId?: string | null | undefined;
  mongoId?: string | null | undefined;
  databaseType: DatabaseType;
};

/** @internal */
export const DatabaseType$inboundSchema: z.ZodNativeEnum<typeof DatabaseType> =
  z.nativeEnum(DatabaseType);

/** @internal */
export const DatabaseType$outboundSchema: z.ZodNativeEnum<typeof DatabaseType> =
  DatabaseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabaseType$ {
  /** @deprecated use `DatabaseType$inboundSchema` instead. */
  export const inboundSchema = DatabaseType$inboundSchema;
  /** @deprecated use `DatabaseType$outboundSchema` instead. */
  export const outboundSchema = DatabaseType$outboundSchema;
}

/** @internal */
export const BackupCreateRequest$inboundSchema: z.ZodType<
  BackupCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  schedule: z.string(),
  enabled: z.nullable(z.boolean()).optional(),
  prefix: z.string(),
  destinationId: z.string(),
  database: z.string(),
  mariadbId: z.nullable(z.string()).optional(),
  mysqlId: z.nullable(z.string()).optional(),
  postgresId: z.nullable(z.string()).optional(),
  mongoId: z.nullable(z.string()).optional(),
  databaseType: DatabaseType$inboundSchema,
});

/** @internal */
export type BackupCreateRequest$Outbound = {
  schedule: string;
  enabled?: boolean | null | undefined;
  prefix: string;
  destinationId: string;
  database: string;
  mariadbId?: string | null | undefined;
  mysqlId?: string | null | undefined;
  postgresId?: string | null | undefined;
  mongoId?: string | null | undefined;
  databaseType: string;
};

/** @internal */
export const BackupCreateRequest$outboundSchema: z.ZodType<
  BackupCreateRequest$Outbound,
  z.ZodTypeDef,
  BackupCreateRequest
> = z.object({
  schedule: z.string(),
  enabled: z.nullable(z.boolean()).optional(),
  prefix: z.string(),
  destinationId: z.string(),
  database: z.string(),
  mariadbId: z.nullable(z.string()).optional(),
  mysqlId: z.nullable(z.string()).optional(),
  postgresId: z.nullable(z.string()).optional(),
  mongoId: z.nullable(z.string()).optional(),
  databaseType: DatabaseType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BackupCreateRequest$ {
  /** @deprecated use `BackupCreateRequest$inboundSchema` instead. */
  export const inboundSchema = BackupCreateRequest$inboundSchema;
  /** @deprecated use `BackupCreateRequest$outboundSchema` instead. */
  export const outboundSchema = BackupCreateRequest$outboundSchema;
  /** @deprecated use `BackupCreateRequest$Outbound` instead. */
  export type Outbound = BackupCreateRequest$Outbound;
}

export function backupCreateRequestToJSON(
  backupCreateRequest: BackupCreateRequest,
): string {
  return JSON.stringify(
    BackupCreateRequest$outboundSchema.parse(backupCreateRequest),
  );
}

export function backupCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<BackupCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BackupCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackupCreateRequest' from JSON`,
  );
}
