/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BackupUpdateRequest = {
  schedule: string;
  enabled?: boolean | null | undefined;
  prefix: string;
  backupId: string;
  destinationId: string;
  database: string;
};

/** @internal */
export const BackupUpdateRequest$inboundSchema: z.ZodType<
  BackupUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  schedule: z.string(),
  enabled: z.nullable(z.boolean()).optional(),
  prefix: z.string(),
  backupId: z.string(),
  destinationId: z.string(),
  database: z.string(),
});

/** @internal */
export type BackupUpdateRequest$Outbound = {
  schedule: string;
  enabled?: boolean | null | undefined;
  prefix: string;
  backupId: string;
  destinationId: string;
  database: string;
};

/** @internal */
export const BackupUpdateRequest$outboundSchema: z.ZodType<
  BackupUpdateRequest$Outbound,
  z.ZodTypeDef,
  BackupUpdateRequest
> = z.object({
  schedule: z.string(),
  enabled: z.nullable(z.boolean()).optional(),
  prefix: z.string(),
  backupId: z.string(),
  destinationId: z.string(),
  database: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BackupUpdateRequest$ {
  /** @deprecated use `BackupUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = BackupUpdateRequest$inboundSchema;
  /** @deprecated use `BackupUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = BackupUpdateRequest$outboundSchema;
  /** @deprecated use `BackupUpdateRequest$Outbound` instead. */
  export type Outbound = BackupUpdateRequest$Outbound;
}

export function backupUpdateRequestToJSON(
  backupUpdateRequest: BackupUpdateRequest,
): string {
  return JSON.stringify(
    BackupUpdateRequest$outboundSchema.parse(backupUpdateRequest),
  );
}

export function backupUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<BackupUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BackupUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackupUpdateRequest' from JSON`,
  );
}
