/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BitbucketUpdateRequest = {
  bitbucketId: string;
  bitbucketUsername?: string | undefined;
  appPassword?: string | null | undefined;
  bitbucketWorkspaceName?: string | undefined;
  gitProviderId: string;
  name: string;
  adminId?: string | undefined;
};

/** @internal */
export const BitbucketUpdateRequest$inboundSchema: z.ZodType<
  BitbucketUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  bitbucketId: z.string(),
  bitbucketUsername: z.string().optional(),
  appPassword: z.nullable(z.string()).optional(),
  bitbucketWorkspaceName: z.string().optional(),
  gitProviderId: z.string(),
  name: z.string(),
  adminId: z.string().optional(),
});

/** @internal */
export type BitbucketUpdateRequest$Outbound = {
  bitbucketId: string;
  bitbucketUsername?: string | undefined;
  appPassword?: string | null | undefined;
  bitbucketWorkspaceName?: string | undefined;
  gitProviderId: string;
  name: string;
  adminId?: string | undefined;
};

/** @internal */
export const BitbucketUpdateRequest$outboundSchema: z.ZodType<
  BitbucketUpdateRequest$Outbound,
  z.ZodTypeDef,
  BitbucketUpdateRequest
> = z.object({
  bitbucketId: z.string(),
  bitbucketUsername: z.string().optional(),
  appPassword: z.nullable(z.string()).optional(),
  bitbucketWorkspaceName: z.string().optional(),
  gitProviderId: z.string(),
  name: z.string(),
  adminId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BitbucketUpdateRequest$ {
  /** @deprecated use `BitbucketUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = BitbucketUpdateRequest$inboundSchema;
  /** @deprecated use `BitbucketUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = BitbucketUpdateRequest$outboundSchema;
  /** @deprecated use `BitbucketUpdateRequest$Outbound` instead. */
  export type Outbound = BitbucketUpdateRequest$Outbound;
}

export function bitbucketUpdateRequestToJSON(
  bitbucketUpdateRequest: BitbucketUpdateRequest,
): string {
  return JSON.stringify(
    BitbucketUpdateRequest$outboundSchema.parse(bitbucketUpdateRequest),
  );
}

export function bitbucketUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketUpdateRequest' from JSON`,
  );
}
