/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BitbucketOneRequest = {
  bitbucketId: string;
};

/** @internal */
export const BitbucketOneRequest$inboundSchema: z.ZodType<
  BitbucketOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  bitbucketId: z.string(),
});

/** @internal */
export type BitbucketOneRequest$Outbound = {
  bitbucketId: string;
};

/** @internal */
export const BitbucketOneRequest$outboundSchema: z.ZodType<
  BitbucketOneRequest$Outbound,
  z.ZodTypeDef,
  BitbucketOneRequest
> = z.object({
  bitbucketId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BitbucketOneRequest$ {
  /** @deprecated use `BitbucketOneRequest$inboundSchema` instead. */
  export const inboundSchema = BitbucketOneRequest$inboundSchema;
  /** @deprecated use `BitbucketOneRequest$outboundSchema` instead. */
  export const outboundSchema = BitbucketOneRequest$outboundSchema;
  /** @deprecated use `BitbucketOneRequest$Outbound` instead. */
  export type Outbound = BitbucketOneRequest$Outbound;
}

export function bitbucketOneRequestToJSON(
  bitbucketOneRequest: BitbucketOneRequest,
): string {
  return JSON.stringify(
    BitbucketOneRequest$outboundSchema.parse(bitbucketOneRequest),
  );
}

export function bitbucketOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketOneRequest' from JSON`,
  );
}
