/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CertificatesOneRequest = {
  certificateId: string;
};

/** @internal */
export const CertificatesOneRequest$inboundSchema: z.ZodType<
  CertificatesOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  certificateId: z.string(),
});

/** @internal */
export type CertificatesOneRequest$Outbound = {
  certificateId: string;
};

/** @internal */
export const CertificatesOneRequest$outboundSchema: z.ZodType<
  CertificatesOneRequest$Outbound,
  z.ZodTypeDef,
  CertificatesOneRequest
> = z.object({
  certificateId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CertificatesOneRequest$ {
  /** @deprecated use `CertificatesOneRequest$inboundSchema` instead. */
  export const inboundSchema = CertificatesOneRequest$inboundSchema;
  /** @deprecated use `CertificatesOneRequest$outboundSchema` instead. */
  export const outboundSchema = CertificatesOneRequest$outboundSchema;
  /** @deprecated use `CertificatesOneRequest$Outbound` instead. */
  export type Outbound = CertificatesOneRequest$Outbound;
}

export function certificatesOneRequestToJSON(
  certificatesOneRequest: CertificatesOneRequest,
): string {
  return JSON.stringify(
    CertificatesOneRequest$outboundSchema.parse(certificatesOneRequest),
  );
}

export function certificatesOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<CertificatesOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CertificatesOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CertificatesOneRequest' from JSON`,
  );
}
