/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CertificatesRemoveRequest = {
  certificateId: string;
};

/** @internal */
export const CertificatesRemoveRequest$inboundSchema: z.ZodType<
  CertificatesRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  certificateId: z.string(),
});

/** @internal */
export type CertificatesRemoveRequest$Outbound = {
  certificateId: string;
};

/** @internal */
export const CertificatesRemoveRequest$outboundSchema: z.ZodType<
  CertificatesRemoveRequest$Outbound,
  z.ZodTypeDef,
  CertificatesRemoveRequest
> = z.object({
  certificateId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CertificatesRemoveRequest$ {
  /** @deprecated use `CertificatesRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = CertificatesRemoveRequest$inboundSchema;
  /** @deprecated use `CertificatesRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = CertificatesRemoveRequest$outboundSchema;
  /** @deprecated use `CertificatesRemoveRequest$Outbound` instead. */
  export type Outbound = CertificatesRemoveRequest$Outbound;
}

export function certificatesRemoveRequestToJSON(
  certificatesRemoveRequest: CertificatesRemoveRequest,
): string {
  return JSON.stringify(
    CertificatesRemoveRequest$outboundSchema.parse(certificatesRemoveRequest),
  );
}

export function certificatesRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<CertificatesRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CertificatesRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CertificatesRemoveRequest' from JSON`,
  );
}
