/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ComposeUpdateSourceType = {
  Git: "git",
  Github: "github",
  Gitlab: "gitlab",
  Bitbucket: "bitbucket",
  Raw: "raw",
} as const;
export type ComposeUpdateSourceType = ClosedEnum<
  typeof ComposeUpdateSourceType
>;

export const ComposeUpdateComposeType = {
  DockerCompose: "docker-compose",
  Stack: "stack",
} as const;
export type ComposeUpdateComposeType = ClosedEnum<
  typeof ComposeUpdateComposeType
>;

export const ComposeStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type ComposeStatus = ClosedEnum<typeof ComposeStatus>;

export type ComposeUpdateRequest = {
  composeId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  env?: string | null | undefined;
  composeFile?: string | undefined;
  refreshToken?: string | null | undefined;
  sourceType?: ComposeUpdateSourceType | undefined;
  composeType?: ComposeUpdateComposeType | undefined;
  repository?: string | null | undefined;
  owner?: string | null | undefined;
  branch?: string | null | undefined;
  autoDeploy?: boolean | null | undefined;
  gitlabProjectId?: number | null | undefined;
  gitlabRepository?: string | null | undefined;
  gitlabOwner?: string | null | undefined;
  gitlabBranch?: string | null | undefined;
  gitlabPathNamespace?: string | null | undefined;
  bitbucketRepository?: string | null | undefined;
  bitbucketOwner?: string | null | undefined;
  bitbucketBranch?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  customGitBranch?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
  command?: string | undefined;
  composePath?: string | undefined;
  suffix?: string | undefined;
  randomize?: boolean | undefined;
  composeStatus?: ComposeStatus | undefined;
  projectId?: string | undefined;
  createdAt?: string | undefined;
  githubId?: string | null | undefined;
  gitlabId?: string | null | undefined;
  bitbucketId?: string | null | undefined;
};

/** @internal */
export const ComposeUpdateSourceType$inboundSchema: z.ZodNativeEnum<
  typeof ComposeUpdateSourceType
> = z.nativeEnum(ComposeUpdateSourceType);

/** @internal */
export const ComposeUpdateSourceType$outboundSchema: z.ZodNativeEnum<
  typeof ComposeUpdateSourceType
> = ComposeUpdateSourceType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComposeUpdateSourceType$ {
  /** @deprecated use `ComposeUpdateSourceType$inboundSchema` instead. */
  export const inboundSchema = ComposeUpdateSourceType$inboundSchema;
  /** @deprecated use `ComposeUpdateSourceType$outboundSchema` instead. */
  export const outboundSchema = ComposeUpdateSourceType$outboundSchema;
}

/** @internal */
export const ComposeUpdateComposeType$inboundSchema: z.ZodNativeEnum<
  typeof ComposeUpdateComposeType
> = z.nativeEnum(ComposeUpdateComposeType);

/** @internal */
export const ComposeUpdateComposeType$outboundSchema: z.ZodNativeEnum<
  typeof ComposeUpdateComposeType
> = ComposeUpdateComposeType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComposeUpdateComposeType$ {
  /** @deprecated use `ComposeUpdateComposeType$inboundSchema` instead. */
  export const inboundSchema = ComposeUpdateComposeType$inboundSchema;
  /** @deprecated use `ComposeUpdateComposeType$outboundSchema` instead. */
  export const outboundSchema = ComposeUpdateComposeType$outboundSchema;
}

/** @internal */
export const ComposeStatus$inboundSchema: z.ZodNativeEnum<
  typeof ComposeStatus
> = z.nativeEnum(ComposeStatus);

/** @internal */
export const ComposeStatus$outboundSchema: z.ZodNativeEnum<
  typeof ComposeStatus
> = ComposeStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComposeStatus$ {
  /** @deprecated use `ComposeStatus$inboundSchema` instead. */
  export const inboundSchema = ComposeStatus$inboundSchema;
  /** @deprecated use `ComposeStatus$outboundSchema` instead. */
  export const outboundSchema = ComposeStatus$outboundSchema;
}

/** @internal */
export const ComposeUpdateRequest$inboundSchema: z.ZodType<
  ComposeUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  composeId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  composeFile: z.string().optional(),
  refreshToken: z.nullable(z.string()).optional(),
  sourceType: ComposeUpdateSourceType$inboundSchema.optional(),
  composeType: ComposeUpdateComposeType$inboundSchema.optional(),
  repository: z.nullable(z.string()).optional(),
  owner: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  autoDeploy: z.nullable(z.boolean()).optional(),
  gitlabProjectId: z.nullable(z.number()).optional(),
  gitlabRepository: z.nullable(z.string()).optional(),
  gitlabOwner: z.nullable(z.string()).optional(),
  gitlabBranch: z.nullable(z.string()).optional(),
  gitlabPathNamespace: z.nullable(z.string()).optional(),
  bitbucketRepository: z.nullable(z.string()).optional(),
  bitbucketOwner: z.nullable(z.string()).optional(),
  bitbucketBranch: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  customGitBranch: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
  command: z.string().optional(),
  composePath: z.string().optional(),
  suffix: z.string().optional(),
  randomize: z.boolean().optional(),
  composeStatus: ComposeStatus$inboundSchema.optional(),
  projectId: z.string().optional(),
  createdAt: z.string().optional(),
  githubId: z.nullable(z.string()).optional(),
  gitlabId: z.nullable(z.string()).optional(),
  bitbucketId: z.nullable(z.string()).optional(),
});

/** @internal */
export type ComposeUpdateRequest$Outbound = {
  composeId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  env?: string | null | undefined;
  composeFile?: string | undefined;
  refreshToken?: string | null | undefined;
  sourceType?: string | undefined;
  composeType?: string | undefined;
  repository?: string | null | undefined;
  owner?: string | null | undefined;
  branch?: string | null | undefined;
  autoDeploy?: boolean | null | undefined;
  gitlabProjectId?: number | null | undefined;
  gitlabRepository?: string | null | undefined;
  gitlabOwner?: string | null | undefined;
  gitlabBranch?: string | null | undefined;
  gitlabPathNamespace?: string | null | undefined;
  bitbucketRepository?: string | null | undefined;
  bitbucketOwner?: string | null | undefined;
  bitbucketBranch?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  customGitBranch?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
  command?: string | undefined;
  composePath?: string | undefined;
  suffix?: string | undefined;
  randomize?: boolean | undefined;
  composeStatus?: string | undefined;
  projectId?: string | undefined;
  createdAt?: string | undefined;
  githubId?: string | null | undefined;
  gitlabId?: string | null | undefined;
  bitbucketId?: string | null | undefined;
};

/** @internal */
export const ComposeUpdateRequest$outboundSchema: z.ZodType<
  ComposeUpdateRequest$Outbound,
  z.ZodTypeDef,
  ComposeUpdateRequest
> = z.object({
  composeId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  composeFile: z.string().optional(),
  refreshToken: z.nullable(z.string()).optional(),
  sourceType: ComposeUpdateSourceType$outboundSchema.optional(),
  composeType: ComposeUpdateComposeType$outboundSchema.optional(),
  repository: z.nullable(z.string()).optional(),
  owner: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  autoDeploy: z.nullable(z.boolean()).optional(),
  gitlabProjectId: z.nullable(z.number()).optional(),
  gitlabRepository: z.nullable(z.string()).optional(),
  gitlabOwner: z.nullable(z.string()).optional(),
  gitlabBranch: z.nullable(z.string()).optional(),
  gitlabPathNamespace: z.nullable(z.string()).optional(),
  bitbucketRepository: z.nullable(z.string()).optional(),
  bitbucketOwner: z.nullable(z.string()).optional(),
  bitbucketBranch: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  customGitBranch: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
  command: z.string().optional(),
  composePath: z.string().optional(),
  suffix: z.string().optional(),
  randomize: z.boolean().optional(),
  composeStatus: ComposeStatus$outboundSchema.optional(),
  projectId: z.string().optional(),
  createdAt: z.string().optional(),
  githubId: z.nullable(z.string()).optional(),
  gitlabId: z.nullable(z.string()).optional(),
  bitbucketId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComposeUpdateRequest$ {
  /** @deprecated use `ComposeUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = ComposeUpdateRequest$inboundSchema;
  /** @deprecated use `ComposeUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = ComposeUpdateRequest$outboundSchema;
  /** @deprecated use `ComposeUpdateRequest$Outbound` instead. */
  export type Outbound = ComposeUpdateRequest$Outbound;
}

export function composeUpdateRequestToJSON(
  composeUpdateRequest: ComposeUpdateRequest,
): string {
  return JSON.stringify(
    ComposeUpdateRequest$outboundSchema.parse(composeUpdateRequest),
  );
}

export function composeUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ComposeUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ComposeUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComposeUpdateRequest' from JSON`,
  );
}
