/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentAllRequest = {
  applicationId: string;
};

/** @internal */
export const DeploymentAllRequest$inboundSchema: z.ZodType<
  DeploymentAllRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
});

/** @internal */
export type DeploymentAllRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const DeploymentAllRequest$outboundSchema: z.ZodType<
  DeploymentAllRequest$Outbound,
  z.ZodTypeDef,
  DeploymentAllRequest
> = z.object({
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeploymentAllRequest$ {
  /** @deprecated use `DeploymentAllRequest$inboundSchema` instead. */
  export const inboundSchema = DeploymentAllRequest$inboundSchema;
  /** @deprecated use `DeploymentAllRequest$outboundSchema` instead. */
  export const outboundSchema = DeploymentAllRequest$outboundSchema;
  /** @deprecated use `DeploymentAllRequest$Outbound` instead. */
  export type Outbound = DeploymentAllRequest$Outbound;
}

export function deploymentAllRequestToJSON(
  deploymentAllRequest: DeploymentAllRequest,
): string {
  return JSON.stringify(
    DeploymentAllRequest$outboundSchema.parse(deploymentAllRequest),
  );
}

export function deploymentAllRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentAllRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentAllRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentAllRequest' from JSON`,
  );
}
