/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentAllByServerRequest = {
  serverId: string;
};

/** @internal */
export const DeploymentAllByServerRequest$inboundSchema: z.ZodType<
  DeploymentAllByServerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serverId: z.string(),
});

/** @internal */
export type DeploymentAllByServerRequest$Outbound = {
  serverId: string;
};

/** @internal */
export const DeploymentAllByServerRequest$outboundSchema: z.ZodType<
  DeploymentAllByServerRequest$Outbound,
  z.ZodTypeDef,
  DeploymentAllByServerRequest
> = z.object({
  serverId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeploymentAllByServerRequest$ {
  /** @deprecated use `DeploymentAllByServerRequest$inboundSchema` instead. */
  export const inboundSchema = DeploymentAllByServerRequest$inboundSchema;
  /** @deprecated use `DeploymentAllByServerRequest$outboundSchema` instead. */
  export const outboundSchema = DeploymentAllByServerRequest$outboundSchema;
  /** @deprecated use `DeploymentAllByServerRequest$Outbound` instead. */
  export type Outbound = DeploymentAllByServerRequest$Outbound;
}

export function deploymentAllByServerRequestToJSON(
  deploymentAllByServerRequest: DeploymentAllByServerRequest,
): string {
  return JSON.stringify(
    DeploymentAllByServerRequest$outboundSchema.parse(
      deploymentAllByServerRequest,
    ),
  );
}

export function deploymentAllByServerRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentAllByServerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentAllByServerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentAllByServerRequest' from JSON`,
  );
}
