/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DomainUpdateCertificateType = {
  Letsencrypt: "letsencrypt",
  None: "none",
} as const;
export type DomainUpdateCertificateType = ClosedEnum<
  typeof DomainUpdateCertificateType
>;

export const DomainUpdateDomainType = {
  Compose: "compose",
  Application: "application",
} as const;
export type DomainUpdateDomainType = ClosedEnum<typeof DomainUpdateDomainType>;

export type DomainUpdateRequest = {
  host: string;
  path?: string | null | undefined;
  port?: number | null | undefined;
  https?: boolean | undefined;
  certificateType?: DomainUpdateCertificateType | undefined;
  serviceName?: string | null | undefined;
  domainType?: DomainUpdateDomainType | null | undefined;
  domainId: string;
};

/** @internal */
export const DomainUpdateCertificateType$inboundSchema: z.ZodNativeEnum<
  typeof DomainUpdateCertificateType
> = z.nativeEnum(DomainUpdateCertificateType);

/** @internal */
export const DomainUpdateCertificateType$outboundSchema: z.ZodNativeEnum<
  typeof DomainUpdateCertificateType
> = DomainUpdateCertificateType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DomainUpdateCertificateType$ {
  /** @deprecated use `DomainUpdateCertificateType$inboundSchema` instead. */
  export const inboundSchema = DomainUpdateCertificateType$inboundSchema;
  /** @deprecated use `DomainUpdateCertificateType$outboundSchema` instead. */
  export const outboundSchema = DomainUpdateCertificateType$outboundSchema;
}

/** @internal */
export const DomainUpdateDomainType$inboundSchema: z.ZodNativeEnum<
  typeof DomainUpdateDomainType
> = z.nativeEnum(DomainUpdateDomainType);

/** @internal */
export const DomainUpdateDomainType$outboundSchema: z.ZodNativeEnum<
  typeof DomainUpdateDomainType
> = DomainUpdateDomainType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DomainUpdateDomainType$ {
  /** @deprecated use `DomainUpdateDomainType$inboundSchema` instead. */
  export const inboundSchema = DomainUpdateDomainType$inboundSchema;
  /** @deprecated use `DomainUpdateDomainType$outboundSchema` instead. */
  export const outboundSchema = DomainUpdateDomainType$outboundSchema;
}

/** @internal */
export const DomainUpdateRequest$inboundSchema: z.ZodType<
  DomainUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  host: z.string(),
  path: z.nullable(z.string()).optional(),
  port: z.nullable(z.number()).optional(),
  https: z.boolean().optional(),
  certificateType: DomainUpdateCertificateType$inboundSchema.optional(),
  serviceName: z.nullable(z.string()).optional(),
  domainType: z.nullable(DomainUpdateDomainType$inboundSchema).optional(),
  domainId: z.string(),
});

/** @internal */
export type DomainUpdateRequest$Outbound = {
  host: string;
  path?: string | null | undefined;
  port?: number | null | undefined;
  https?: boolean | undefined;
  certificateType?: string | undefined;
  serviceName?: string | null | undefined;
  domainType?: string | null | undefined;
  domainId: string;
};

/** @internal */
export const DomainUpdateRequest$outboundSchema: z.ZodType<
  DomainUpdateRequest$Outbound,
  z.ZodTypeDef,
  DomainUpdateRequest
> = z.object({
  host: z.string(),
  path: z.nullable(z.string()).optional(),
  port: z.nullable(z.number()).optional(),
  https: z.boolean().optional(),
  certificateType: DomainUpdateCertificateType$outboundSchema.optional(),
  serviceName: z.nullable(z.string()).optional(),
  domainType: z.nullable(DomainUpdateDomainType$outboundSchema).optional(),
  domainId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DomainUpdateRequest$ {
  /** @deprecated use `DomainUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = DomainUpdateRequest$inboundSchema;
  /** @deprecated use `DomainUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = DomainUpdateRequest$outboundSchema;
  /** @deprecated use `DomainUpdateRequest$Outbound` instead. */
  export type Outbound = DomainUpdateRequest$Outbound;
}

export function domainUpdateRequestToJSON(
  domainUpdateRequest: DomainUpdateRequest,
): string {
  return JSON.stringify(
    DomainUpdateRequest$outboundSchema.parse(domainUpdateRequest),
  );
}

export function domainUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<DomainUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainUpdateRequest' from JSON`,
  );
}
