/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DomainByApplicationIdRequest = {
  applicationId: string;
};

/** @internal */
export const DomainByApplicationIdRequest$inboundSchema: z.ZodType<
  DomainByApplicationIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
});

/** @internal */
export type DomainByApplicationIdRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const DomainByApplicationIdRequest$outboundSchema: z.ZodType<
  DomainByApplicationIdRequest$Outbound,
  z.ZodTypeDef,
  DomainByApplicationIdRequest
> = z.object({
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DomainByApplicationIdRequest$ {
  /** @deprecated use `DomainByApplicationIdRequest$inboundSchema` instead. */
  export const inboundSchema = DomainByApplicationIdRequest$inboundSchema;
  /** @deprecated use `DomainByApplicationIdRequest$outboundSchema` instead. */
  export const outboundSchema = DomainByApplicationIdRequest$outboundSchema;
  /** @deprecated use `DomainByApplicationIdRequest$Outbound` instead. */
  export type Outbound = DomainByApplicationIdRequest$Outbound;
}

export function domainByApplicationIdRequestToJSON(
  domainByApplicationIdRequest: DomainByApplicationIdRequest,
): string {
  return JSON.stringify(
    DomainByApplicationIdRequest$outboundSchema.parse(
      domainByApplicationIdRequest,
    ),
  );
}

export function domainByApplicationIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DomainByApplicationIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainByApplicationIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainByApplicationIdRequest' from JSON`,
  );
}
