/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GithubOneRequest = {
  githubId: string;
};

/** @internal */
export const GithubOneRequest$inboundSchema: z.ZodType<
  GithubOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  githubId: z.string(),
});

/** @internal */
export type GithubOneRequest$Outbound = {
  githubId: string;
};

/** @internal */
export const GithubOneRequest$outboundSchema: z.ZodType<
  GithubOneRequest$Outbound,
  z.ZodTypeDef,
  GithubOneRequest
> = z.object({
  githubId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubOneRequest$ {
  /** @deprecated use `GithubOneRequest$inboundSchema` instead. */
  export const inboundSchema = GithubOneRequest$inboundSchema;
  /** @deprecated use `GithubOneRequest$outboundSchema` instead. */
  export const outboundSchema = GithubOneRequest$outboundSchema;
  /** @deprecated use `GithubOneRequest$Outbound` instead. */
  export type Outbound = GithubOneRequest$Outbound;
}

export function githubOneRequestToJSON(
  githubOneRequest: GithubOneRequest,
): string {
  return JSON.stringify(
    GithubOneRequest$outboundSchema.parse(githubOneRequest),
  );
}

export function githubOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<GithubOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubOneRequest' from JSON`,
  );
}
