/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GithubUpdateRequest = {
  githubId: string;
  githubAppName?: string | null | undefined;
  githubAppId?: number | null | undefined;
  githubClientId?: string | null | undefined;
  githubClientSecret?: string | null | undefined;
  githubInstallationId?: string | null | undefined;
  githubPrivateKey?: string | null | undefined;
  githubWebhookSecret?: string | null | undefined;
  gitProviderId: string;
  name: string;
};

/** @internal */
export const GithubUpdateRequest$inboundSchema: z.ZodType<
  GithubUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  githubId: z.string(),
  githubAppName: z.nullable(z.string()).optional(),
  githubAppId: z.nullable(z.number()).optional(),
  githubClientId: z.nullable(z.string()).optional(),
  githubClientSecret: z.nullable(z.string()).optional(),
  githubInstallationId: z.nullable(z.string()).optional(),
  githubPrivateKey: z.nullable(z.string()).optional(),
  githubWebhookSecret: z.nullable(z.string()).optional(),
  gitProviderId: z.string(),
  name: z.string(),
});

/** @internal */
export type GithubUpdateRequest$Outbound = {
  githubId: string;
  githubAppName?: string | null | undefined;
  githubAppId?: number | null | undefined;
  githubClientId?: string | null | undefined;
  githubClientSecret?: string | null | undefined;
  githubInstallationId?: string | null | undefined;
  githubPrivateKey?: string | null | undefined;
  githubWebhookSecret?: string | null | undefined;
  gitProviderId: string;
  name: string;
};

/** @internal */
export const GithubUpdateRequest$outboundSchema: z.ZodType<
  GithubUpdateRequest$Outbound,
  z.ZodTypeDef,
  GithubUpdateRequest
> = z.object({
  githubId: z.string(),
  githubAppName: z.nullable(z.string()).optional(),
  githubAppId: z.nullable(z.number()).optional(),
  githubClientId: z.nullable(z.string()).optional(),
  githubClientSecret: z.nullable(z.string()).optional(),
  githubInstallationId: z.nullable(z.string()).optional(),
  githubPrivateKey: z.nullable(z.string()).optional(),
  githubWebhookSecret: z.nullable(z.string()).optional(),
  gitProviderId: z.string(),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubUpdateRequest$ {
  /** @deprecated use `GithubUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = GithubUpdateRequest$inboundSchema;
  /** @deprecated use `GithubUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = GithubUpdateRequest$outboundSchema;
  /** @deprecated use `GithubUpdateRequest$Outbound` instead. */
  export type Outbound = GithubUpdateRequest$Outbound;
}

export function githubUpdateRequestToJSON(
  githubUpdateRequest: GithubUpdateRequest,
): string {
  return JSON.stringify(
    GithubUpdateRequest$outboundSchema.parse(githubUpdateRequest),
  );
}

export function githubUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<GithubUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubUpdateRequest' from JSON`,
  );
}
