/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GitlabTestConnectionRequest = {
  gitlabId?: string | undefined;
  groupName?: string | undefined;
};

/** @internal */
export const GitlabTestConnectionRequest$inboundSchema: z.ZodType<
  GitlabTestConnectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitlabId: z.string().optional(),
  groupName: z.string().optional(),
});

/** @internal */
export type GitlabTestConnectionRequest$Outbound = {
  gitlabId?: string | undefined;
  groupName?: string | undefined;
};

/** @internal */
export const GitlabTestConnectionRequest$outboundSchema: z.ZodType<
  GitlabTestConnectionRequest$Outbound,
  z.ZodTypeDef,
  GitlabTestConnectionRequest
> = z.object({
  gitlabId: z.string().optional(),
  groupName: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GitlabTestConnectionRequest$ {
  /** @deprecated use `GitlabTestConnectionRequest$inboundSchema` instead. */
  export const inboundSchema = GitlabTestConnectionRequest$inboundSchema;
  /** @deprecated use `GitlabTestConnectionRequest$outboundSchema` instead. */
  export const outboundSchema = GitlabTestConnectionRequest$outboundSchema;
  /** @deprecated use `GitlabTestConnectionRequest$Outbound` instead. */
  export type Outbound = GitlabTestConnectionRequest$Outbound;
}

export function gitlabTestConnectionRequestToJSON(
  gitlabTestConnectionRequest: GitlabTestConnectionRequest,
): string {
  return JSON.stringify(
    GitlabTestConnectionRequest$outboundSchema.parse(
      gitlabTestConnectionRequest,
    ),
  );
}

export function gitlabTestConnectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GitlabTestConnectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitlabTestConnectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitlabTestConnectionRequest' from JSON`,
  );
}
