/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GitlabUpdateRequest = {
  gitlabId: string;
  applicationId?: string | undefined;
  redirectUri?: string | undefined;
  secret?: string | undefined;
  accessToken?: string | null | undefined;
  refreshToken?: string | null | undefined;
  groupName?: string | undefined;
  expiresAt?: number | null | undefined;
  gitProviderId: string;
  name: string;
};

/** @internal */
export const GitlabUpdateRequest$inboundSchema: z.ZodType<
  GitlabUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitlabId: z.string(),
  applicationId: z.string().optional(),
  redirectUri: z.string().optional(),
  secret: z.string().optional(),
  accessToken: z.nullable(z.string()).optional(),
  refreshToken: z.nullable(z.string()).optional(),
  groupName: z.string().optional(),
  expiresAt: z.nullable(z.number()).optional(),
  gitProviderId: z.string(),
  name: z.string(),
});

/** @internal */
export type GitlabUpdateRequest$Outbound = {
  gitlabId: string;
  applicationId?: string | undefined;
  redirectUri?: string | undefined;
  secret?: string | undefined;
  accessToken?: string | null | undefined;
  refreshToken?: string | null | undefined;
  groupName?: string | undefined;
  expiresAt?: number | null | undefined;
  gitProviderId: string;
  name: string;
};

/** @internal */
export const GitlabUpdateRequest$outboundSchema: z.ZodType<
  GitlabUpdateRequest$Outbound,
  z.ZodTypeDef,
  GitlabUpdateRequest
> = z.object({
  gitlabId: z.string(),
  applicationId: z.string().optional(),
  redirectUri: z.string().optional(),
  secret: z.string().optional(),
  accessToken: z.nullable(z.string()).optional(),
  refreshToken: z.nullable(z.string()).optional(),
  groupName: z.string().optional(),
  expiresAt: z.nullable(z.number()).optional(),
  gitProviderId: z.string(),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GitlabUpdateRequest$ {
  /** @deprecated use `GitlabUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = GitlabUpdateRequest$inboundSchema;
  /** @deprecated use `GitlabUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = GitlabUpdateRequest$outboundSchema;
  /** @deprecated use `GitlabUpdateRequest$Outbound` instead. */
  export type Outbound = GitlabUpdateRequest$Outbound;
}

export function gitlabUpdateRequestToJSON(
  gitlabUpdateRequest: GitlabUpdateRequest,
): string {
  return JSON.stringify(
    GitlabUpdateRequest$outboundSchema.parse(gitlabUpdateRequest),
  );
}

export function gitlabUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<GitlabUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitlabUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitlabUpdateRequest' from JSON`,
  );
}
