/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GitlabCreateRequest = {
  gitlabId?: string | undefined;
  applicationId?: string | undefined;
  redirectUri?: string | undefined;
  secret?: string | undefined;
  accessToken?: string | null | undefined;
  refreshToken?: string | null | undefined;
  groupName?: string | undefined;
  expiresAt?: number | null | undefined;
  gitProviderId?: string | undefined;
  authId: string;
  name: string;
};

/** @internal */
export const GitlabCreateRequest$inboundSchema: z.ZodType<
  GitlabCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitlabId: z.string().optional(),
  applicationId: z.string().optional(),
  redirectUri: z.string().optional(),
  secret: z.string().optional(),
  accessToken: z.nullable(z.string()).optional(),
  refreshToken: z.nullable(z.string()).optional(),
  groupName: z.string().optional(),
  expiresAt: z.nullable(z.number()).optional(),
  gitProviderId: z.string().optional(),
  authId: z.string(),
  name: z.string(),
});

/** @internal */
export type GitlabCreateRequest$Outbound = {
  gitlabId?: string | undefined;
  applicationId?: string | undefined;
  redirectUri?: string | undefined;
  secret?: string | undefined;
  accessToken?: string | null | undefined;
  refreshToken?: string | null | undefined;
  groupName?: string | undefined;
  expiresAt?: number | null | undefined;
  gitProviderId?: string | undefined;
  authId: string;
  name: string;
};

/** @internal */
export const GitlabCreateRequest$outboundSchema: z.ZodType<
  GitlabCreateRequest$Outbound,
  z.ZodTypeDef,
  GitlabCreateRequest
> = z.object({
  gitlabId: z.string().optional(),
  applicationId: z.string().optional(),
  redirectUri: z.string().optional(),
  secret: z.string().optional(),
  accessToken: z.nullable(z.string()).optional(),
  refreshToken: z.nullable(z.string()).optional(),
  groupName: z.string().optional(),
  expiresAt: z.nullable(z.number()).optional(),
  gitProviderId: z.string().optional(),
  authId: z.string(),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GitlabCreateRequest$ {
  /** @deprecated use `GitlabCreateRequest$inboundSchema` instead. */
  export const inboundSchema = GitlabCreateRequest$inboundSchema;
  /** @deprecated use `GitlabCreateRequest$outboundSchema` instead. */
  export const outboundSchema = GitlabCreateRequest$outboundSchema;
  /** @deprecated use `GitlabCreateRequest$Outbound` instead. */
  export type Outbound = GitlabCreateRequest$Outbound;
}

export function gitlabCreateRequestToJSON(
  gitlabCreateRequest: GitlabCreateRequest,
): string {
  return JSON.stringify(
    GitlabCreateRequest$outboundSchema.parse(gitlabCreateRequest),
  );
}

export function gitlabCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<GitlabCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitlabCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitlabCreateRequest' from JSON`,
  );
}
