/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GitlabOneRequest = {
  gitlabId: string;
};

/** @internal */
export const GitlabOneRequest$inboundSchema: z.ZodType<
  GitlabOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitlabId: z.string(),
});

/** @internal */
export type GitlabOneRequest$Outbound = {
  gitlabId: string;
};

/** @internal */
export const GitlabOneRequest$outboundSchema: z.ZodType<
  GitlabOneRequest$Outbound,
  z.ZodTypeDef,
  GitlabOneRequest
> = z.object({
  gitlabId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GitlabOneRequest$ {
  /** @deprecated use `GitlabOneRequest$inboundSchema` instead. */
  export const inboundSchema = GitlabOneRequest$inboundSchema;
  /** @deprecated use `GitlabOneRequest$outboundSchema` instead. */
  export const outboundSchema = GitlabOneRequest$outboundSchema;
  /** @deprecated use `GitlabOneRequest$Outbound` instead. */
  export type Outbound = GitlabOneRequest$Outbound;
}

export function gitlabOneRequestToJSON(
  gitlabOneRequest: GitlabOneRequest,
): string {
  return JSON.stringify(
    GitlabOneRequest$outboundSchema.parse(gitlabOneRequest),
  );
}

export function gitlabOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<GitlabOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitlabOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitlabOneRequest' from JSON`,
  );
}
