/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GitProviderRemoveRequest = {
  gitProviderId: string;
};

/** @internal */
export const GitProviderRemoveRequest$inboundSchema: z.ZodType<
  GitProviderRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitProviderId: z.string(),
});

/** @internal */
export type GitProviderRemoveRequest$Outbound = {
  gitProviderId: string;
};

/** @internal */
export const GitProviderRemoveRequest$outboundSchema: z.ZodType<
  GitProviderRemoveRequest$Outbound,
  z.ZodTypeDef,
  GitProviderRemoveRequest
> = z.object({
  gitProviderId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GitProviderRemoveRequest$ {
  /** @deprecated use `GitProviderRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = GitProviderRemoveRequest$inboundSchema;
  /** @deprecated use `GitProviderRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = GitProviderRemoveRequest$outboundSchema;
  /** @deprecated use `GitProviderRemoveRequest$Outbound` instead. */
  export type Outbound = GitProviderRemoveRequest$Outbound;
}

export function gitProviderRemoveRequestToJSON(
  gitProviderRemoveRequest: GitProviderRemoveRequest,
): string {
  return JSON.stringify(
    GitProviderRemoveRequest$outboundSchema.parse(gitProviderRemoveRequest),
  );
}

export function gitProviderRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<GitProviderRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitProviderRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitProviderRemoveRequest' from JSON`,
  );
}
