/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbStartRequest = {
  mariadbId: string;
};

/** @internal */
export const MariadbStartRequest$inboundSchema: z.ZodType<
  MariadbStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
});

/** @internal */
export type MariadbStartRequest$Outbound = {
  mariadbId: string;
};

/** @internal */
export const MariadbStartRequest$outboundSchema: z.ZodType<
  MariadbStartRequest$Outbound,
  z.ZodTypeDef,
  MariadbStartRequest
> = z.object({
  mariadbId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbStartRequest$ {
  /** @deprecated use `MariadbStartRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbStartRequest$inboundSchema;
  /** @deprecated use `MariadbStartRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbStartRequest$outboundSchema;
  /** @deprecated use `MariadbStartRequest$Outbound` instead. */
  export type Outbound = MariadbStartRequest$Outbound;
}

export function mariadbStartRequestToJSON(
  mariadbStartRequest: MariadbStartRequest,
): string {
  return JSON.stringify(
    MariadbStartRequest$outboundSchema.parse(mariadbStartRequest),
  );
}

export function mariadbStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbStartRequest' from JSON`,
  );
}
