/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbOneRequest = {
  mariadbId: string;
};

/** @internal */
export const MariadbOneRequest$inboundSchema: z.ZodType<
  MariadbOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
});

/** @internal */
export type MariadbOneRequest$Outbound = {
  mariadbId: string;
};

/** @internal */
export const MariadbOneRequest$outboundSchema: z.ZodType<
  MariadbOneRequest$Outbound,
  z.ZodTypeDef,
  MariadbOneRequest
> = z.object({
  mariadbId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbOneRequest$ {
  /** @deprecated use `MariadbOneRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbOneRequest$inboundSchema;
  /** @deprecated use `MariadbOneRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbOneRequest$outboundSchema;
  /** @deprecated use `MariadbOneRequest$Outbound` instead. */
  export type Outbound = MariadbOneRequest$Outbound;
}

export function mariadbOneRequestToJSON(
  mariadbOneRequest: MariadbOneRequest,
): string {
  return JSON.stringify(
    MariadbOneRequest$outboundSchema.parse(mariadbOneRequest),
  );
}

export function mariadbOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbOneRequest' from JSON`,
  );
}
