/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbReloadRequest = {
  mariadbId: string;
  appName: string;
};

/** @internal */
export const MariadbReloadRequest$inboundSchema: z.ZodType<
  MariadbReloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
  appName: z.string(),
});

/** @internal */
export type MariadbReloadRequest$Outbound = {
  mariadbId: string;
  appName: string;
};

/** @internal */
export const MariadbReloadRequest$outboundSchema: z.ZodType<
  MariadbReloadRequest$Outbound,
  z.ZodTypeDef,
  MariadbReloadRequest
> = z.object({
  mariadbId: z.string(),
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbReloadRequest$ {
  /** @deprecated use `MariadbReloadRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbReloadRequest$inboundSchema;
  /** @deprecated use `MariadbReloadRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbReloadRequest$outboundSchema;
  /** @deprecated use `MariadbReloadRequest$Outbound` instead. */
  export type Outbound = MariadbReloadRequest$Outbound;
}

export function mariadbReloadRequestToJSON(
  mariadbReloadRequest: MariadbReloadRequest,
): string {
  return JSON.stringify(
    MariadbReloadRequest$outboundSchema.parse(mariadbReloadRequest),
  );
}

export function mariadbReloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbReloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbReloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbReloadRequest' from JSON`,
  );
}
