/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MariadbChangeStatusApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MariadbChangeStatusApplicationStatus = ClosedEnum<
  typeof MariadbChangeStatusApplicationStatus
>;

export type MariadbChangeStatusRequest = {
  mariadbId: string;
  applicationStatus: MariadbChangeStatusApplicationStatus;
};

/** @internal */
export const MariadbChangeStatusApplicationStatus$inboundSchema:
  z.ZodNativeEnum<typeof MariadbChangeStatusApplicationStatus> = z.nativeEnum(
    MariadbChangeStatusApplicationStatus,
  );

/** @internal */
export const MariadbChangeStatusApplicationStatus$outboundSchema:
  z.ZodNativeEnum<typeof MariadbChangeStatusApplicationStatus> =
    MariadbChangeStatusApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbChangeStatusApplicationStatus$ {
  /** @deprecated use `MariadbChangeStatusApplicationStatus$inboundSchema` instead. */
  export const inboundSchema =
    MariadbChangeStatusApplicationStatus$inboundSchema;
  /** @deprecated use `MariadbChangeStatusApplicationStatus$outboundSchema` instead. */
  export const outboundSchema =
    MariadbChangeStatusApplicationStatus$outboundSchema;
}

/** @internal */
export const MariadbChangeStatusRequest$inboundSchema: z.ZodType<
  MariadbChangeStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
  applicationStatus: MariadbChangeStatusApplicationStatus$inboundSchema,
});

/** @internal */
export type MariadbChangeStatusRequest$Outbound = {
  mariadbId: string;
  applicationStatus: string;
};

/** @internal */
export const MariadbChangeStatusRequest$outboundSchema: z.ZodType<
  MariadbChangeStatusRequest$Outbound,
  z.ZodTypeDef,
  MariadbChangeStatusRequest
> = z.object({
  mariadbId: z.string(),
  applicationStatus: MariadbChangeStatusApplicationStatus$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbChangeStatusRequest$ {
  /** @deprecated use `MariadbChangeStatusRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbChangeStatusRequest$inboundSchema;
  /** @deprecated use `MariadbChangeStatusRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbChangeStatusRequest$outboundSchema;
  /** @deprecated use `MariadbChangeStatusRequest$Outbound` instead. */
  export type Outbound = MariadbChangeStatusRequest$Outbound;
}

export function mariadbChangeStatusRequestToJSON(
  mariadbChangeStatusRequest: MariadbChangeStatusRequest,
): string {
  return JSON.stringify(
    MariadbChangeStatusRequest$outboundSchema.parse(mariadbChangeStatusRequest),
  );
}

export function mariadbChangeStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbChangeStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbChangeStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbChangeStatusRequest' from JSON`,
  );
}
