/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbSaveExternalPortRequest = {
  mariadbId: string;
  externalPort: number | null;
};

/** @internal */
export const MariadbSaveExternalPortRequest$inboundSchema: z.ZodType<
  MariadbSaveExternalPortRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
  externalPort: z.nullable(z.number()),
});

/** @internal */
export type MariadbSaveExternalPortRequest$Outbound = {
  mariadbId: string;
  externalPort: number | null;
};

/** @internal */
export const MariadbSaveExternalPortRequest$outboundSchema: z.ZodType<
  MariadbSaveExternalPortRequest$Outbound,
  z.ZodTypeDef,
  MariadbSaveExternalPortRequest
> = z.object({
  mariadbId: z.string(),
  externalPort: z.nullable(z.number()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbSaveExternalPortRequest$ {
  /** @deprecated use `MariadbSaveExternalPortRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbSaveExternalPortRequest$inboundSchema;
  /** @deprecated use `MariadbSaveExternalPortRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbSaveExternalPortRequest$outboundSchema;
  /** @deprecated use `MariadbSaveExternalPortRequest$Outbound` instead. */
  export type Outbound = MariadbSaveExternalPortRequest$Outbound;
}

export function mariadbSaveExternalPortRequestToJSON(
  mariadbSaveExternalPortRequest: MariadbSaveExternalPortRequest,
): string {
  return JSON.stringify(
    MariadbSaveExternalPortRequest$outboundSchema.parse(
      mariadbSaveExternalPortRequest,
    ),
  );
}

export function mariadbSaveExternalPortRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbSaveExternalPortRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbSaveExternalPortRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbSaveExternalPortRequest' from JSON`,
  );
}
