/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbStopRequest = {
  mariadbId: string;
};

/** @internal */
export const MariadbStopRequest$inboundSchema: z.ZodType<
  MariadbStopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
});

/** @internal */
export type MariadbStopRequest$Outbound = {
  mariadbId: string;
};

/** @internal */
export const MariadbStopRequest$outboundSchema: z.ZodType<
  MariadbStopRequest$Outbound,
  z.ZodTypeDef,
  MariadbStopRequest
> = z.object({
  mariadbId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbStopRequest$ {
  /** @deprecated use `MariadbStopRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbStopRequest$inboundSchema;
  /** @deprecated use `MariadbStopRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbStopRequest$outboundSchema;
  /** @deprecated use `MariadbStopRequest$Outbound` instead. */
  export type Outbound = MariadbStopRequest$Outbound;
}

export function mariadbStopRequestToJSON(
  mariadbStopRequest: MariadbStopRequest,
): string {
  return JSON.stringify(
    MariadbStopRequest$outboundSchema.parse(mariadbStopRequest),
  );
}

export function mariadbStopRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbStopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbStopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbStopRequest' from JSON`,
  );
}
