/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbCreateRequest = {
  name: string;
  appName: string;
  dockerImage?: string | undefined;
  databaseRootPassword: string;
  projectId: string;
  description?: string | null | undefined;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const MariadbCreateRequest$inboundSchema: z.ZodType<
  MariadbCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  appName: z.string(),
  dockerImage: z.string().default("mariadb:6"),
  databaseRootPassword: z.string(),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  databaseName: z.string(),
  databaseUser: z.string(),
  databasePassword: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

/** @internal */
export type MariadbCreateRequest$Outbound = {
  name: string;
  appName: string;
  dockerImage: string;
  databaseRootPassword: string;
  projectId: string;
  description?: string | null | undefined;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const MariadbCreateRequest$outboundSchema: z.ZodType<
  MariadbCreateRequest$Outbound,
  z.ZodTypeDef,
  MariadbCreateRequest
> = z.object({
  name: z.string(),
  appName: z.string(),
  dockerImage: z.string().default("mariadb:6"),
  databaseRootPassword: z.string(),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  databaseName: z.string(),
  databaseUser: z.string(),
  databasePassword: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbCreateRequest$ {
  /** @deprecated use `MariadbCreateRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbCreateRequest$inboundSchema;
  /** @deprecated use `MariadbCreateRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbCreateRequest$outboundSchema;
  /** @deprecated use `MariadbCreateRequest$Outbound` instead. */
  export type Outbound = MariadbCreateRequest$Outbound;
}

export function mariadbCreateRequestToJSON(
  mariadbCreateRequest: MariadbCreateRequest,
): string {
  return JSON.stringify(
    MariadbCreateRequest$outboundSchema.parse(mariadbCreateRequest),
  );
}

export function mariadbCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbCreateRequest' from JSON`,
  );
}
