/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbDeployRequest = {
  mariadbId: string;
};

/** @internal */
export const MariadbDeployRequest$inboundSchema: z.ZodType<
  MariadbDeployRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
});

/** @internal */
export type MariadbDeployRequest$Outbound = {
  mariadbId: string;
};

/** @internal */
export const MariadbDeployRequest$outboundSchema: z.ZodType<
  MariadbDeployRequest$Outbound,
  z.ZodTypeDef,
  MariadbDeployRequest
> = z.object({
  mariadbId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbDeployRequest$ {
  /** @deprecated use `MariadbDeployRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbDeployRequest$inboundSchema;
  /** @deprecated use `MariadbDeployRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbDeployRequest$outboundSchema;
  /** @deprecated use `MariadbDeployRequest$Outbound` instead. */
  export type Outbound = MariadbDeployRequest$Outbound;
}

export function mariadbDeployRequestToJSON(
  mariadbDeployRequest: MariadbDeployRequest,
): string {
  return JSON.stringify(
    MariadbDeployRequest$outboundSchema.parse(mariadbDeployRequest),
  );
}

export function mariadbDeployRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbDeployRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbDeployRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbDeployRequest' from JSON`,
  );
}
