/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MariadbRemoveRequest = {
  mariadbId: string;
};

/** @internal */
export const MariadbRemoveRequest$inboundSchema: z.ZodType<
  MariadbRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadbId: z.string(),
});

/** @internal */
export type MariadbRemoveRequest$Outbound = {
  mariadbId: string;
};

/** @internal */
export const MariadbRemoveRequest$outboundSchema: z.ZodType<
  MariadbRemoveRequest$Outbound,
  z.ZodTypeDef,
  MariadbRemoveRequest
> = z.object({
  mariadbId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MariadbRemoveRequest$ {
  /** @deprecated use `MariadbRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = MariadbRemoveRequest$inboundSchema;
  /** @deprecated use `MariadbRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = MariadbRemoveRequest$outboundSchema;
  /** @deprecated use `MariadbRemoveRequest$Outbound` instead. */
  export type Outbound = MariadbRemoveRequest$Outbound;
}

export function mariadbRemoveRequestToJSON(
  mariadbRemoveRequest: MariadbRemoveRequest,
): string {
  return JSON.stringify(
    MariadbRemoveRequest$outboundSchema.parse(mariadbRemoveRequest),
  );
}

export function mariadbRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<MariadbRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbRemoveRequest' from JSON`,
  );
}
