/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoSaveExternalPortRequest = {
  mongoId: string;
  externalPort: number | null;
};

/** @internal */
export const MongoSaveExternalPortRequest$inboundSchema: z.ZodType<
  MongoSaveExternalPortRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
  externalPort: z.nullable(z.number()),
});

/** @internal */
export type MongoSaveExternalPortRequest$Outbound = {
  mongoId: string;
  externalPort: number | null;
};

/** @internal */
export const MongoSaveExternalPortRequest$outboundSchema: z.ZodType<
  MongoSaveExternalPortRequest$Outbound,
  z.ZodTypeDef,
  MongoSaveExternalPortRequest
> = z.object({
  mongoId: z.string(),
  externalPort: z.nullable(z.number()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoSaveExternalPortRequest$ {
  /** @deprecated use `MongoSaveExternalPortRequest$inboundSchema` instead. */
  export const inboundSchema = MongoSaveExternalPortRequest$inboundSchema;
  /** @deprecated use `MongoSaveExternalPortRequest$outboundSchema` instead. */
  export const outboundSchema = MongoSaveExternalPortRequest$outboundSchema;
  /** @deprecated use `MongoSaveExternalPortRequest$Outbound` instead. */
  export type Outbound = MongoSaveExternalPortRequest$Outbound;
}

export function mongoSaveExternalPortRequestToJSON(
  mongoSaveExternalPortRequest: MongoSaveExternalPortRequest,
): string {
  return JSON.stringify(
    MongoSaveExternalPortRequest$outboundSchema.parse(
      mongoSaveExternalPortRequest,
    ),
  );
}

export function mongoSaveExternalPortRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortRequest' from JSON`,
  );
}
