/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MongoChangeStatusApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoChangeStatusApplicationStatus = ClosedEnum<
  typeof MongoChangeStatusApplicationStatus
>;

export type MongoChangeStatusRequest = {
  mongoId: string;
  applicationStatus: MongoChangeStatusApplicationStatus;
};

/** @internal */
export const MongoChangeStatusApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusApplicationStatus
> = z.nativeEnum(MongoChangeStatusApplicationStatus);

/** @internal */
export const MongoChangeStatusApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusApplicationStatus
> = MongoChangeStatusApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoChangeStatusApplicationStatus$ {
  /** @deprecated use `MongoChangeStatusApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = MongoChangeStatusApplicationStatus$inboundSchema;
  /** @deprecated use `MongoChangeStatusApplicationStatus$outboundSchema` instead. */
  export const outboundSchema =
    MongoChangeStatusApplicationStatus$outboundSchema;
}

/** @internal */
export const MongoChangeStatusRequest$inboundSchema: z.ZodType<
  MongoChangeStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
  applicationStatus: MongoChangeStatusApplicationStatus$inboundSchema,
});

/** @internal */
export type MongoChangeStatusRequest$Outbound = {
  mongoId: string;
  applicationStatus: string;
};

/** @internal */
export const MongoChangeStatusRequest$outboundSchema: z.ZodType<
  MongoChangeStatusRequest$Outbound,
  z.ZodTypeDef,
  MongoChangeStatusRequest
> = z.object({
  mongoId: z.string(),
  applicationStatus: MongoChangeStatusApplicationStatus$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoChangeStatusRequest$ {
  /** @deprecated use `MongoChangeStatusRequest$inboundSchema` instead. */
  export const inboundSchema = MongoChangeStatusRequest$inboundSchema;
  /** @deprecated use `MongoChangeStatusRequest$outboundSchema` instead. */
  export const outboundSchema = MongoChangeStatusRequest$outboundSchema;
  /** @deprecated use `MongoChangeStatusRequest$Outbound` instead. */
  export type Outbound = MongoChangeStatusRequest$Outbound;
}

export function mongoChangeStatusRequestToJSON(
  mongoChangeStatusRequest: MongoChangeStatusRequest,
): string {
  return JSON.stringify(
    MongoChangeStatusRequest$outboundSchema.parse(mongoChangeStatusRequest),
  );
}

export function mongoChangeStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusRequest' from JSON`,
  );
}
