/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoStartRequest = {
  mongoId: string;
};

/** @internal */
export const MongoStartRequest$inboundSchema: z.ZodType<
  MongoStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
});

/** @internal */
export type MongoStartRequest$Outbound = {
  mongoId: string;
};

/** @internal */
export const MongoStartRequest$outboundSchema: z.ZodType<
  MongoStartRequest$Outbound,
  z.ZodTypeDef,
  MongoStartRequest
> = z.object({
  mongoId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoStartRequest$ {
  /** @deprecated use `MongoStartRequest$inboundSchema` instead. */
  export const inboundSchema = MongoStartRequest$inboundSchema;
  /** @deprecated use `MongoStartRequest$outboundSchema` instead. */
  export const outboundSchema = MongoStartRequest$outboundSchema;
  /** @deprecated use `MongoStartRequest$Outbound` instead. */
  export type Outbound = MongoStartRequest$Outbound;
}

export function mongoStartRequestToJSON(
  mongoStartRequest: MongoStartRequest,
): string {
  return JSON.stringify(
    MongoStartRequest$outboundSchema.parse(mongoStartRequest),
  );
}

export function mongoStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoStartRequest' from JSON`,
  );
}
