/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoRemoveRequest = {
  mongoId: string;
};

/** @internal */
export const MongoRemoveRequest$inboundSchema: z.ZodType<
  MongoRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
});

/** @internal */
export type MongoRemoveRequest$Outbound = {
  mongoId: string;
};

/** @internal */
export const MongoRemoveRequest$outboundSchema: z.ZodType<
  MongoRemoveRequest$Outbound,
  z.ZodTypeDef,
  MongoRemoveRequest
> = z.object({
  mongoId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveRequest$ {
  /** @deprecated use `MongoRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveRequest$inboundSchema;
  /** @deprecated use `MongoRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveRequest$outboundSchema;
  /** @deprecated use `MongoRemoveRequest$Outbound` instead. */
  export type Outbound = MongoRemoveRequest$Outbound;
}

export function mongoRemoveRequestToJSON(
  mongoRemoveRequest: MongoRemoveRequest,
): string {
  return JSON.stringify(
    MongoRemoveRequest$outboundSchema.parse(mongoRemoveRequest),
  );
}

export function mongoRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveRequest' from JSON`,
  );
}
