/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoOneRequest = {
  mongoId: string;
};

/** @internal */
export const MongoOneRequest$inboundSchema: z.ZodType<
  MongoOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
});

/** @internal */
export type MongoOneRequest$Outbound = {
  mongoId: string;
};

/** @internal */
export const MongoOneRequest$outboundSchema: z.ZodType<
  MongoOneRequest$Outbound,
  z.ZodTypeDef,
  MongoOneRequest
> = z.object({
  mongoId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoOneRequest$ {
  /** @deprecated use `MongoOneRequest$inboundSchema` instead. */
  export const inboundSchema = MongoOneRequest$inboundSchema;
  /** @deprecated use `MongoOneRequest$outboundSchema` instead. */
  export const outboundSchema = MongoOneRequest$outboundSchema;
  /** @deprecated use `MongoOneRequest$Outbound` instead. */
  export type Outbound = MongoOneRequest$Outbound;
}

export function mongoOneRequestToJSON(
  mongoOneRequest: MongoOneRequest,
): string {
  return JSON.stringify(MongoOneRequest$outboundSchema.parse(mongoOneRequest));
}

export function mongoOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoOneRequest' from JSON`,
  );
}
