/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoStopRequest = {
  mongoId: string;
};

/** @internal */
export const MongoStopRequest$inboundSchema: z.ZodType<
  MongoStopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
});

/** @internal */
export type MongoStopRequest$Outbound = {
  mongoId: string;
};

/** @internal */
export const MongoStopRequest$outboundSchema: z.ZodType<
  MongoStopRequest$Outbound,
  z.ZodTypeDef,
  MongoStopRequest
> = z.object({
  mongoId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoStopRequest$ {
  /** @deprecated use `MongoStopRequest$inboundSchema` instead. */
  export const inboundSchema = MongoStopRequest$inboundSchema;
  /** @deprecated use `MongoStopRequest$outboundSchema` instead. */
  export const outboundSchema = MongoStopRequest$outboundSchema;
  /** @deprecated use `MongoStopRequest$Outbound` instead. */
  export type Outbound = MongoStopRequest$Outbound;
}

export function mongoStopRequestToJSON(
  mongoStopRequest: MongoStopRequest,
): string {
  return JSON.stringify(
    MongoStopRequest$outboundSchema.parse(mongoStopRequest),
  );
}

export function mongoStopRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoStopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoStopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoStopRequest' from JSON`,
  );
}
