/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoSaveEnvironmentRequest = {
  mongoId: string;
  env?: string | null | undefined;
};

/** @internal */
export const MongoSaveEnvironmentRequest$inboundSchema: z.ZodType<
  MongoSaveEnvironmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
  env: z.nullable(z.string()).optional(),
});

/** @internal */
export type MongoSaveEnvironmentRequest$Outbound = {
  mongoId: string;
  env?: string | null | undefined;
};

/** @internal */
export const MongoSaveEnvironmentRequest$outboundSchema: z.ZodType<
  MongoSaveEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  MongoSaveEnvironmentRequest
> = z.object({
  mongoId: z.string(),
  env: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoSaveEnvironmentRequest$ {
  /** @deprecated use `MongoSaveEnvironmentRequest$inboundSchema` instead. */
  export const inboundSchema = MongoSaveEnvironmentRequest$inboundSchema;
  /** @deprecated use `MongoSaveEnvironmentRequest$outboundSchema` instead. */
  export const outboundSchema = MongoSaveEnvironmentRequest$outboundSchema;
  /** @deprecated use `MongoSaveEnvironmentRequest$Outbound` instead. */
  export type Outbound = MongoSaveEnvironmentRequest$Outbound;
}

export function mongoSaveEnvironmentRequestToJSON(
  mongoSaveEnvironmentRequest: MongoSaveEnvironmentRequest,
): string {
  return JSON.stringify(
    MongoSaveEnvironmentRequest$outboundSchema.parse(
      mongoSaveEnvironmentRequest,
    ),
  );
}

export function mongoSaveEnvironmentRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveEnvironmentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveEnvironmentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveEnvironmentRequest' from JSON`,
  );
}
