/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MongoUpdateApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoUpdateApplicationStatus = ClosedEnum<
  typeof MongoUpdateApplicationStatus
>;

export type MongoUpdateRequest = {
  mongoId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  databaseUser?: string | undefined;
  databasePassword?: string | undefined;
  dockerImage?: string | undefined;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  externalPort?: number | null | undefined;
  applicationStatus?: MongoUpdateApplicationStatus | undefined;
  createdAt?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const MongoUpdateApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoUpdateApplicationStatus
> = z.nativeEnum(MongoUpdateApplicationStatus);

/** @internal */
export const MongoUpdateApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof MongoUpdateApplicationStatus
> = MongoUpdateApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoUpdateApplicationStatus$ {
  /** @deprecated use `MongoUpdateApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = MongoUpdateApplicationStatus$inboundSchema;
  /** @deprecated use `MongoUpdateApplicationStatus$outboundSchema` instead. */
  export const outboundSchema = MongoUpdateApplicationStatus$outboundSchema;
}

/** @internal */
export const MongoUpdateRequest$inboundSchema: z.ZodType<
  MongoUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  databaseUser: z.string().optional(),
  databasePassword: z.string().optional(),
  dockerImage: z.string().default("mongo:15"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  applicationStatus: MongoUpdateApplicationStatus$inboundSchema.optional(),
  createdAt: z.string().optional(),
  projectId: z.string().optional(),
});

/** @internal */
export type MongoUpdateRequest$Outbound = {
  mongoId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  databaseUser?: string | undefined;
  databasePassword?: string | undefined;
  dockerImage: string;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  externalPort?: number | null | undefined;
  applicationStatus?: string | undefined;
  createdAt?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const MongoUpdateRequest$outboundSchema: z.ZodType<
  MongoUpdateRequest$Outbound,
  z.ZodTypeDef,
  MongoUpdateRequest
> = z.object({
  mongoId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  databaseUser: z.string().optional(),
  databasePassword: z.string().optional(),
  dockerImage: z.string().default("mongo:15"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  applicationStatus: MongoUpdateApplicationStatus$outboundSchema.optional(),
  createdAt: z.string().optional(),
  projectId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoUpdateRequest$ {
  /** @deprecated use `MongoUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = MongoUpdateRequest$inboundSchema;
  /** @deprecated use `MongoUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = MongoUpdateRequest$outboundSchema;
  /** @deprecated use `MongoUpdateRequest$Outbound` instead. */
  export type Outbound = MongoUpdateRequest$Outbound;
}

export function mongoUpdateRequestToJSON(
  mongoUpdateRequest: MongoUpdateRequest,
): string {
  return JSON.stringify(
    MongoUpdateRequest$outboundSchema.parse(mongoUpdateRequest),
  );
}

export function mongoUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoUpdateRequest' from JSON`,
  );
}
