/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MongoReloadRequest = {
  mongoId: string;
  appName: string;
};

/** @internal */
export const MongoReloadRequest$inboundSchema: z.ZodType<
  MongoReloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
  appName: z.string(),
});

/** @internal */
export type MongoReloadRequest$Outbound = {
  mongoId: string;
  appName: string;
};

/** @internal */
export const MongoReloadRequest$outboundSchema: z.ZodType<
  MongoReloadRequest$Outbound,
  z.ZodTypeDef,
  MongoReloadRequest
> = z.object({
  mongoId: z.string(),
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoReloadRequest$ {
  /** @deprecated use `MongoReloadRequest$inboundSchema` instead. */
  export const inboundSchema = MongoReloadRequest$inboundSchema;
  /** @deprecated use `MongoReloadRequest$outboundSchema` instead. */
  export const outboundSchema = MongoReloadRequest$outboundSchema;
  /** @deprecated use `MongoReloadRequest$Outbound` instead. */
  export type Outbound = MongoReloadRequest$Outbound;
}

export function mongoReloadRequestToJSON(
  mongoReloadRequest: MongoReloadRequest,
): string {
  return JSON.stringify(
    MongoReloadRequest$outboundSchema.parse(mongoReloadRequest),
  );
}

export function mongoReloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoReloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoReloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoReloadRequest' from JSON`,
  );
}
