/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlStartRequest = {
  mysqlId: string;
};

/** @internal */
export const MysqlStartRequest$inboundSchema: z.ZodType<
  MysqlStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
});

/** @internal */
export type MysqlStartRequest$Outbound = {
  mysqlId: string;
};

/** @internal */
export const MysqlStartRequest$outboundSchema: z.ZodType<
  MysqlStartRequest$Outbound,
  z.ZodTypeDef,
  MysqlStartRequest
> = z.object({
  mysqlId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlStartRequest$ {
  /** @deprecated use `MysqlStartRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlStartRequest$inboundSchema;
  /** @deprecated use `MysqlStartRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlStartRequest$outboundSchema;
  /** @deprecated use `MysqlStartRequest$Outbound` instead. */
  export type Outbound = MysqlStartRequest$Outbound;
}

export function mysqlStartRequestToJSON(
  mysqlStartRequest: MysqlStartRequest,
): string {
  return JSON.stringify(
    MysqlStartRequest$outboundSchema.parse(mysqlStartRequest),
  );
}

export function mysqlStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlStartRequest' from JSON`,
  );
}
