/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlOneRequest = {
  mysqlId: string;
};

/** @internal */
export const MysqlOneRequest$inboundSchema: z.ZodType<
  MysqlOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
});

/** @internal */
export type MysqlOneRequest$Outbound = {
  mysqlId: string;
};

/** @internal */
export const MysqlOneRequest$outboundSchema: z.ZodType<
  MysqlOneRequest$Outbound,
  z.ZodTypeDef,
  MysqlOneRequest
> = z.object({
  mysqlId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlOneRequest$ {
  /** @deprecated use `MysqlOneRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlOneRequest$inboundSchema;
  /** @deprecated use `MysqlOneRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlOneRequest$outboundSchema;
  /** @deprecated use `MysqlOneRequest$Outbound` instead. */
  export type Outbound = MysqlOneRequest$Outbound;
}

export function mysqlOneRequestToJSON(
  mysqlOneRequest: MysqlOneRequest,
): string {
  return JSON.stringify(MysqlOneRequest$outboundSchema.parse(mysqlOneRequest));
}

export function mysqlOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlOneRequest' from JSON`,
  );
}
