/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlReloadRequest = {
  mysqlId: string;
  appName: string;
};

/** @internal */
export const MysqlReloadRequest$inboundSchema: z.ZodType<
  MysqlReloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
  appName: z.string(),
});

/** @internal */
export type MysqlReloadRequest$Outbound = {
  mysqlId: string;
  appName: string;
};

/** @internal */
export const MysqlReloadRequest$outboundSchema: z.ZodType<
  MysqlReloadRequest$Outbound,
  z.ZodTypeDef,
  MysqlReloadRequest
> = z.object({
  mysqlId: z.string(),
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlReloadRequest$ {
  /** @deprecated use `MysqlReloadRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlReloadRequest$inboundSchema;
  /** @deprecated use `MysqlReloadRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlReloadRequest$outboundSchema;
  /** @deprecated use `MysqlReloadRequest$Outbound` instead. */
  export type Outbound = MysqlReloadRequest$Outbound;
}

export function mysqlReloadRequestToJSON(
  mysqlReloadRequest: MysqlReloadRequest,
): string {
  return JSON.stringify(
    MysqlReloadRequest$outboundSchema.parse(mysqlReloadRequest),
  );
}

export function mysqlReloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlReloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlReloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlReloadRequest' from JSON`,
  );
}
