/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MysqlUpdateApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MysqlUpdateApplicationStatus = ClosedEnum<
  typeof MysqlUpdateApplicationStatus
>;

export type MysqlUpdateRequest = {
  mysqlId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  databaseName?: string | undefined;
  databaseUser?: string | undefined;
  databasePassword?: string | undefined;
  databaseRootPassword?: string | undefined;
  dockerImage?: string | undefined;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  externalPort?: number | null | undefined;
  applicationStatus?: MysqlUpdateApplicationStatus | undefined;
  createdAt?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const MysqlUpdateApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MysqlUpdateApplicationStatus
> = z.nativeEnum(MysqlUpdateApplicationStatus);

/** @internal */
export const MysqlUpdateApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof MysqlUpdateApplicationStatus
> = MysqlUpdateApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlUpdateApplicationStatus$ {
  /** @deprecated use `MysqlUpdateApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = MysqlUpdateApplicationStatus$inboundSchema;
  /** @deprecated use `MysqlUpdateApplicationStatus$outboundSchema` instead. */
  export const outboundSchema = MysqlUpdateApplicationStatus$outboundSchema;
}

/** @internal */
export const MysqlUpdateRequest$inboundSchema: z.ZodType<
  MysqlUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  databaseName: z.string().optional(),
  databaseUser: z.string().optional(),
  databasePassword: z.string().optional(),
  databaseRootPassword: z.string().optional(),
  dockerImage: z.string().default("mysql:8"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  applicationStatus: MysqlUpdateApplicationStatus$inboundSchema.optional(),
  createdAt: z.string().optional(),
  projectId: z.string().optional(),
});

/** @internal */
export type MysqlUpdateRequest$Outbound = {
  mysqlId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  databaseName?: string | undefined;
  databaseUser?: string | undefined;
  databasePassword?: string | undefined;
  databaseRootPassword?: string | undefined;
  dockerImage: string;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  externalPort?: number | null | undefined;
  applicationStatus?: string | undefined;
  createdAt?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const MysqlUpdateRequest$outboundSchema: z.ZodType<
  MysqlUpdateRequest$Outbound,
  z.ZodTypeDef,
  MysqlUpdateRequest
> = z.object({
  mysqlId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  databaseName: z.string().optional(),
  databaseUser: z.string().optional(),
  databasePassword: z.string().optional(),
  databaseRootPassword: z.string().optional(),
  dockerImage: z.string().default("mysql:8"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  applicationStatus: MysqlUpdateApplicationStatus$outboundSchema.optional(),
  createdAt: z.string().optional(),
  projectId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlUpdateRequest$ {
  /** @deprecated use `MysqlUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlUpdateRequest$inboundSchema;
  /** @deprecated use `MysqlUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlUpdateRequest$outboundSchema;
  /** @deprecated use `MysqlUpdateRequest$Outbound` instead. */
  export type Outbound = MysqlUpdateRequest$Outbound;
}

export function mysqlUpdateRequestToJSON(
  mysqlUpdateRequest: MysqlUpdateRequest,
): string {
  return JSON.stringify(
    MysqlUpdateRequest$outboundSchema.parse(mysqlUpdateRequest),
  );
}

export function mysqlUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlUpdateRequest' from JSON`,
  );
}
