/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlSaveExternalPortRequest = {
  mysqlId: string;
  externalPort: number | null;
};

/** @internal */
export const MysqlSaveExternalPortRequest$inboundSchema: z.ZodType<
  MysqlSaveExternalPortRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
  externalPort: z.nullable(z.number()),
});

/** @internal */
export type MysqlSaveExternalPortRequest$Outbound = {
  mysqlId: string;
  externalPort: number | null;
};

/** @internal */
export const MysqlSaveExternalPortRequest$outboundSchema: z.ZodType<
  MysqlSaveExternalPortRequest$Outbound,
  z.ZodTypeDef,
  MysqlSaveExternalPortRequest
> = z.object({
  mysqlId: z.string(),
  externalPort: z.nullable(z.number()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlSaveExternalPortRequest$ {
  /** @deprecated use `MysqlSaveExternalPortRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlSaveExternalPortRequest$inboundSchema;
  /** @deprecated use `MysqlSaveExternalPortRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlSaveExternalPortRequest$outboundSchema;
  /** @deprecated use `MysqlSaveExternalPortRequest$Outbound` instead. */
  export type Outbound = MysqlSaveExternalPortRequest$Outbound;
}

export function mysqlSaveExternalPortRequestToJSON(
  mysqlSaveExternalPortRequest: MysqlSaveExternalPortRequest,
): string {
  return JSON.stringify(
    MysqlSaveExternalPortRequest$outboundSchema.parse(
      mysqlSaveExternalPortRequest,
    ),
  );
}

export function mysqlSaveExternalPortRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlSaveExternalPortRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlSaveExternalPortRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlSaveExternalPortRequest' from JSON`,
  );
}
