/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlCreateRequest = {
  name: string;
  appName: string;
  dockerImage?: string | undefined;
  projectId: string;
  description?: string | null | undefined;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  databaseRootPassword: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const MysqlCreateRequest$inboundSchema: z.ZodType<
  MysqlCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  appName: z.string(),
  dockerImage: z.string().default("mysql:8"),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  databaseName: z.string(),
  databaseUser: z.string(),
  databasePassword: z.string(),
  databaseRootPassword: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

/** @internal */
export type MysqlCreateRequest$Outbound = {
  name: string;
  appName: string;
  dockerImage: string;
  projectId: string;
  description?: string | null | undefined;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  databaseRootPassword: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const MysqlCreateRequest$outboundSchema: z.ZodType<
  MysqlCreateRequest$Outbound,
  z.ZodTypeDef,
  MysqlCreateRequest
> = z.object({
  name: z.string(),
  appName: z.string(),
  dockerImage: z.string().default("mysql:8"),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  databaseName: z.string(),
  databaseUser: z.string(),
  databasePassword: z.string(),
  databaseRootPassword: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlCreateRequest$ {
  /** @deprecated use `MysqlCreateRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlCreateRequest$inboundSchema;
  /** @deprecated use `MysqlCreateRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlCreateRequest$outboundSchema;
  /** @deprecated use `MysqlCreateRequest$Outbound` instead. */
  export type Outbound = MysqlCreateRequest$Outbound;
}

export function mysqlCreateRequestToJSON(
  mysqlCreateRequest: MysqlCreateRequest,
): string {
  return JSON.stringify(
    MysqlCreateRequest$outboundSchema.parse(mysqlCreateRequest),
  );
}

export function mysqlCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlCreateRequest' from JSON`,
  );
}
