/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlRemoveRequest = {
  mysqlId: string;
};

/** @internal */
export const MysqlRemoveRequest$inboundSchema: z.ZodType<
  MysqlRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
});

/** @internal */
export type MysqlRemoveRequest$Outbound = {
  mysqlId: string;
};

/** @internal */
export const MysqlRemoveRequest$outboundSchema: z.ZodType<
  MysqlRemoveRequest$Outbound,
  z.ZodTypeDef,
  MysqlRemoveRequest
> = z.object({
  mysqlId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlRemoveRequest$ {
  /** @deprecated use `MysqlRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlRemoveRequest$inboundSchema;
  /** @deprecated use `MysqlRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlRemoveRequest$outboundSchema;
  /** @deprecated use `MysqlRemoveRequest$Outbound` instead. */
  export type Outbound = MysqlRemoveRequest$Outbound;
}

export function mysqlRemoveRequestToJSON(
  mysqlRemoveRequest: MysqlRemoveRequest,
): string {
  return JSON.stringify(
    MysqlRemoveRequest$outboundSchema.parse(mysqlRemoveRequest),
  );
}

export function mysqlRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlRemoveRequest' from JSON`,
  );
}
