/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlSaveEnvironmentRequest = {
  mysqlId: string;
  env?: string | null | undefined;
};

/** @internal */
export const MysqlSaveEnvironmentRequest$inboundSchema: z.ZodType<
  MysqlSaveEnvironmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
  env: z.nullable(z.string()).optional(),
});

/** @internal */
export type MysqlSaveEnvironmentRequest$Outbound = {
  mysqlId: string;
  env?: string | null | undefined;
};

/** @internal */
export const MysqlSaveEnvironmentRequest$outboundSchema: z.ZodType<
  MysqlSaveEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  MysqlSaveEnvironmentRequest
> = z.object({
  mysqlId: z.string(),
  env: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlSaveEnvironmentRequest$ {
  /** @deprecated use `MysqlSaveEnvironmentRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlSaveEnvironmentRequest$inboundSchema;
  /** @deprecated use `MysqlSaveEnvironmentRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlSaveEnvironmentRequest$outboundSchema;
  /** @deprecated use `MysqlSaveEnvironmentRequest$Outbound` instead. */
  export type Outbound = MysqlSaveEnvironmentRequest$Outbound;
}

export function mysqlSaveEnvironmentRequestToJSON(
  mysqlSaveEnvironmentRequest: MysqlSaveEnvironmentRequest,
): string {
  return JSON.stringify(
    MysqlSaveEnvironmentRequest$outboundSchema.parse(
      mysqlSaveEnvironmentRequest,
    ),
  );
}

export function mysqlSaveEnvironmentRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlSaveEnvironmentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlSaveEnvironmentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlSaveEnvironmentRequest' from JSON`,
  );
}
