/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MysqlStopRequest = {
  mysqlId: string;
};

/** @internal */
export const MysqlStopRequest$inboundSchema: z.ZodType<
  MysqlStopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mysqlId: z.string(),
});

/** @internal */
export type MysqlStopRequest$Outbound = {
  mysqlId: string;
};

/** @internal */
export const MysqlStopRequest$outboundSchema: z.ZodType<
  MysqlStopRequest$Outbound,
  z.ZodTypeDef,
  MysqlStopRequest
> = z.object({
  mysqlId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MysqlStopRequest$ {
  /** @deprecated use `MysqlStopRequest$inboundSchema` instead. */
  export const inboundSchema = MysqlStopRequest$inboundSchema;
  /** @deprecated use `MysqlStopRequest$outboundSchema` instead. */
  export const outboundSchema = MysqlStopRequest$outboundSchema;
  /** @deprecated use `MysqlStopRequest$Outbound` instead. */
  export type Outbound = MysqlStopRequest$Outbound;
}

export function mysqlStopRequestToJSON(
  mysqlStopRequest: MysqlStopRequest,
): string {
  return JSON.stringify(
    MysqlStopRequest$outboundSchema.parse(mysqlStopRequest),
  );
}

export function mysqlStopRequestFromJSON(
  jsonString: string,
): SafeParseResult<MysqlStopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlStopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlStopRequest' from JSON`,
  );
}
