/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationUpdateEmailRequest = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  smtpServer?: string | undefined;
  smtpPort?: number | undefined;
  username?: string | undefined;
  password?: string | undefined;
  fromAddress?: string | undefined;
  toAddresses?: Array<string> | undefined;
  notificationId: string;
  emailId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateEmailRequest$inboundSchema: z.ZodType<
  NotificationUpdateEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  smtpServer: z.string().optional(),
  smtpPort: z.number().optional(),
  username: z.string().optional(),
  password: z.string().optional(),
  fromAddress: z.string().optional(),
  toAddresses: z.array(z.string()).optional(),
  notificationId: z.string(),
  emailId: z.string(),
  adminId: z.string().optional(),
});

/** @internal */
export type NotificationUpdateEmailRequest$Outbound = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  smtpServer?: string | undefined;
  smtpPort?: number | undefined;
  username?: string | undefined;
  password?: string | undefined;
  fromAddress?: string | undefined;
  toAddresses?: Array<string> | undefined;
  notificationId: string;
  emailId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateEmailRequest$outboundSchema: z.ZodType<
  NotificationUpdateEmailRequest$Outbound,
  z.ZodTypeDef,
  NotificationUpdateEmailRequest
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  smtpServer: z.string().optional(),
  smtpPort: z.number().optional(),
  username: z.string().optional(),
  password: z.string().optional(),
  fromAddress: z.string().optional(),
  toAddresses: z.array(z.string()).optional(),
  notificationId: z.string(),
  emailId: z.string(),
  adminId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationUpdateEmailRequest$ {
  /** @deprecated use `NotificationUpdateEmailRequest$inboundSchema` instead. */
  export const inboundSchema = NotificationUpdateEmailRequest$inboundSchema;
  /** @deprecated use `NotificationUpdateEmailRequest$outboundSchema` instead. */
  export const outboundSchema = NotificationUpdateEmailRequest$outboundSchema;
  /** @deprecated use `NotificationUpdateEmailRequest$Outbound` instead. */
  export type Outbound = NotificationUpdateEmailRequest$Outbound;
}

export function notificationUpdateEmailRequestToJSON(
  notificationUpdateEmailRequest: NotificationUpdateEmailRequest,
): string {
  return JSON.stringify(
    NotificationUpdateEmailRequest$outboundSchema.parse(
      notificationUpdateEmailRequest,
    ),
  );
}

export function notificationUpdateEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationUpdateEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationUpdateEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationUpdateEmailRequest' from JSON`,
  );
}
