/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationUpdateDiscordRequest = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  webhookUrl?: string | undefined;
  notificationId: string;
  discordId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateDiscordRequest$inboundSchema: z.ZodType<
  NotificationUpdateDiscordRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  webhookUrl: z.string().optional(),
  notificationId: z.string(),
  discordId: z.string(),
  adminId: z.string().optional(),
});

/** @internal */
export type NotificationUpdateDiscordRequest$Outbound = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  webhookUrl?: string | undefined;
  notificationId: string;
  discordId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateDiscordRequest$outboundSchema: z.ZodType<
  NotificationUpdateDiscordRequest$Outbound,
  z.ZodTypeDef,
  NotificationUpdateDiscordRequest
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  webhookUrl: z.string().optional(),
  notificationId: z.string(),
  discordId: z.string(),
  adminId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationUpdateDiscordRequest$ {
  /** @deprecated use `NotificationUpdateDiscordRequest$inboundSchema` instead. */
  export const inboundSchema = NotificationUpdateDiscordRequest$inboundSchema;
  /** @deprecated use `NotificationUpdateDiscordRequest$outboundSchema` instead. */
  export const outboundSchema = NotificationUpdateDiscordRequest$outboundSchema;
  /** @deprecated use `NotificationUpdateDiscordRequest$Outbound` instead. */
  export type Outbound = NotificationUpdateDiscordRequest$Outbound;
}

export function notificationUpdateDiscordRequestToJSON(
  notificationUpdateDiscordRequest: NotificationUpdateDiscordRequest,
): string {
  return JSON.stringify(
    NotificationUpdateDiscordRequest$outboundSchema.parse(
      notificationUpdateDiscordRequest,
    ),
  );
}

export function notificationUpdateDiscordRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationUpdateDiscordRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationUpdateDiscordRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationUpdateDiscordRequest' from JSON`,
  );
}
