/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationTestEmailConnectionRequest = {
  smtpServer: string;
  smtpPort: number;
  username: string;
  password: string;
  toAddresses: Array<string>;
  fromAddress: string;
};

/** @internal */
export const NotificationTestEmailConnectionRequest$inboundSchema: z.ZodType<
  NotificationTestEmailConnectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  smtpServer: z.string(),
  smtpPort: z.number(),
  username: z.string(),
  password: z.string(),
  toAddresses: z.array(z.string()),
  fromAddress: z.string(),
});

/** @internal */
export type NotificationTestEmailConnectionRequest$Outbound = {
  smtpServer: string;
  smtpPort: number;
  username: string;
  password: string;
  toAddresses: Array<string>;
  fromAddress: string;
};

/** @internal */
export const NotificationTestEmailConnectionRequest$outboundSchema: z.ZodType<
  NotificationTestEmailConnectionRequest$Outbound,
  z.ZodTypeDef,
  NotificationTestEmailConnectionRequest
> = z.object({
  smtpServer: z.string(),
  smtpPort: z.number(),
  username: z.string(),
  password: z.string(),
  toAddresses: z.array(z.string()),
  fromAddress: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationTestEmailConnectionRequest$ {
  /** @deprecated use `NotificationTestEmailConnectionRequest$inboundSchema` instead. */
  export const inboundSchema =
    NotificationTestEmailConnectionRequest$inboundSchema;
  /** @deprecated use `NotificationTestEmailConnectionRequest$outboundSchema` instead. */
  export const outboundSchema =
    NotificationTestEmailConnectionRequest$outboundSchema;
  /** @deprecated use `NotificationTestEmailConnectionRequest$Outbound` instead. */
  export type Outbound = NotificationTestEmailConnectionRequest$Outbound;
}

export function notificationTestEmailConnectionRequestToJSON(
  notificationTestEmailConnectionRequest:
    NotificationTestEmailConnectionRequest,
): string {
  return JSON.stringify(
    NotificationTestEmailConnectionRequest$outboundSchema.parse(
      notificationTestEmailConnectionRequest,
    ),
  );
}

export function notificationTestEmailConnectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationTestEmailConnectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NotificationTestEmailConnectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationTestEmailConnectionRequest' from JSON`,
  );
}
