/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationUpdateTelegramRequest = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  botToken?: string | undefined;
  chatId?: string | undefined;
  notificationId: string;
  telegramId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateTelegramRequest$inboundSchema: z.ZodType<
  NotificationUpdateTelegramRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  botToken: z.string().optional(),
  chatId: z.string().optional(),
  notificationId: z.string(),
  telegramId: z.string(),
  adminId: z.string().optional(),
});

/** @internal */
export type NotificationUpdateTelegramRequest$Outbound = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  botToken?: string | undefined;
  chatId?: string | undefined;
  notificationId: string;
  telegramId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateTelegramRequest$outboundSchema: z.ZodType<
  NotificationUpdateTelegramRequest$Outbound,
  z.ZodTypeDef,
  NotificationUpdateTelegramRequest
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  botToken: z.string().optional(),
  chatId: z.string().optional(),
  notificationId: z.string(),
  telegramId: z.string(),
  adminId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationUpdateTelegramRequest$ {
  /** @deprecated use `NotificationUpdateTelegramRequest$inboundSchema` instead. */
  export const inboundSchema = NotificationUpdateTelegramRequest$inboundSchema;
  /** @deprecated use `NotificationUpdateTelegramRequest$outboundSchema` instead. */
  export const outboundSchema =
    NotificationUpdateTelegramRequest$outboundSchema;
  /** @deprecated use `NotificationUpdateTelegramRequest$Outbound` instead. */
  export type Outbound = NotificationUpdateTelegramRequest$Outbound;
}

export function notificationUpdateTelegramRequestToJSON(
  notificationUpdateTelegramRequest: NotificationUpdateTelegramRequest,
): string {
  return JSON.stringify(
    NotificationUpdateTelegramRequest$outboundSchema.parse(
      notificationUpdateTelegramRequest,
    ),
  );
}

export function notificationUpdateTelegramRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationUpdateTelegramRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationUpdateTelegramRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationUpdateTelegramRequest' from JSON`,
  );
}
