/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationUpdateSlackRequest = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  webhookUrl?: string | undefined;
  channel?: string | undefined;
  notificationId: string;
  slackId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateSlackRequest$inboundSchema: z.ZodType<
  NotificationUpdateSlackRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  webhookUrl: z.string().optional(),
  channel: z.string().optional(),
  notificationId: z.string(),
  slackId: z.string(),
  adminId: z.string().optional(),
});

/** @internal */
export type NotificationUpdateSlackRequest$Outbound = {
  appBuildError?: boolean | undefined;
  databaseBackup?: boolean | undefined;
  dokployRestart?: boolean | undefined;
  name?: string | undefined;
  appDeploy?: boolean | undefined;
  dockerCleanup?: boolean | undefined;
  webhookUrl?: string | undefined;
  channel?: string | undefined;
  notificationId: string;
  slackId: string;
  adminId?: string | undefined;
};

/** @internal */
export const NotificationUpdateSlackRequest$outboundSchema: z.ZodType<
  NotificationUpdateSlackRequest$Outbound,
  z.ZodTypeDef,
  NotificationUpdateSlackRequest
> = z.object({
  appBuildError: z.boolean().optional(),
  databaseBackup: z.boolean().optional(),
  dokployRestart: z.boolean().optional(),
  name: z.string().optional(),
  appDeploy: z.boolean().optional(),
  dockerCleanup: z.boolean().optional(),
  webhookUrl: z.string().optional(),
  channel: z.string().optional(),
  notificationId: z.string(),
  slackId: z.string(),
  adminId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationUpdateSlackRequest$ {
  /** @deprecated use `NotificationUpdateSlackRequest$inboundSchema` instead. */
  export const inboundSchema = NotificationUpdateSlackRequest$inboundSchema;
  /** @deprecated use `NotificationUpdateSlackRequest$outboundSchema` instead. */
  export const outboundSchema = NotificationUpdateSlackRequest$outboundSchema;
  /** @deprecated use `NotificationUpdateSlackRequest$Outbound` instead. */
  export type Outbound = NotificationUpdateSlackRequest$Outbound;
}

export function notificationUpdateSlackRequestToJSON(
  notificationUpdateSlackRequest: NotificationUpdateSlackRequest,
): string {
  return JSON.stringify(
    NotificationUpdateSlackRequest$outboundSchema.parse(
      notificationUpdateSlackRequest,
    ),
  );
}

export function notificationUpdateSlackRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationUpdateSlackRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationUpdateSlackRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationUpdateSlackRequest' from JSON`,
  );
}
