/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationCreateEmailRequest = {
  appBuildError: boolean;
  databaseBackup: boolean;
  dokployRestart: boolean;
  name: string;
  appDeploy: boolean;
  dockerCleanup: boolean;
  smtpServer: string;
  smtpPort: number;
  username: string;
  password: string;
  fromAddress: string;
  toAddresses: Array<string>;
};

/** @internal */
export const NotificationCreateEmailRequest$inboundSchema: z.ZodType<
  NotificationCreateEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appBuildError: z.boolean(),
  databaseBackup: z.boolean(),
  dokployRestart: z.boolean(),
  name: z.string(),
  appDeploy: z.boolean(),
  dockerCleanup: z.boolean(),
  smtpServer: z.string(),
  smtpPort: z.number(),
  username: z.string(),
  password: z.string(),
  fromAddress: z.string(),
  toAddresses: z.array(z.string()),
});

/** @internal */
export type NotificationCreateEmailRequest$Outbound = {
  appBuildError: boolean;
  databaseBackup: boolean;
  dokployRestart: boolean;
  name: string;
  appDeploy: boolean;
  dockerCleanup: boolean;
  smtpServer: string;
  smtpPort: number;
  username: string;
  password: string;
  fromAddress: string;
  toAddresses: Array<string>;
};

/** @internal */
export const NotificationCreateEmailRequest$outboundSchema: z.ZodType<
  NotificationCreateEmailRequest$Outbound,
  z.ZodTypeDef,
  NotificationCreateEmailRequest
> = z.object({
  appBuildError: z.boolean(),
  databaseBackup: z.boolean(),
  dokployRestart: z.boolean(),
  name: z.string(),
  appDeploy: z.boolean(),
  dockerCleanup: z.boolean(),
  smtpServer: z.string(),
  smtpPort: z.number(),
  username: z.string(),
  password: z.string(),
  fromAddress: z.string(),
  toAddresses: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationCreateEmailRequest$ {
  /** @deprecated use `NotificationCreateEmailRequest$inboundSchema` instead. */
  export const inboundSchema = NotificationCreateEmailRequest$inboundSchema;
  /** @deprecated use `NotificationCreateEmailRequest$outboundSchema` instead. */
  export const outboundSchema = NotificationCreateEmailRequest$outboundSchema;
  /** @deprecated use `NotificationCreateEmailRequest$Outbound` instead. */
  export type Outbound = NotificationCreateEmailRequest$Outbound;
}

export function notificationCreateEmailRequestToJSON(
  notificationCreateEmailRequest: NotificationCreateEmailRequest,
): string {
  return JSON.stringify(
    NotificationCreateEmailRequest$outboundSchema.parse(
      notificationCreateEmailRequest,
    ),
  );
}

export function notificationCreateEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationCreateEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationCreateEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationCreateEmailRequest' from JSON`,
  );
}
