/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationCreateTelegramRequest = {
  appBuildError: boolean;
  databaseBackup: boolean;
  dokployRestart: boolean;
  name: string;
  appDeploy: boolean;
  dockerCleanup: boolean;
  botToken: string;
  chatId: string;
};

/** @internal */
export const NotificationCreateTelegramRequest$inboundSchema: z.ZodType<
  NotificationCreateTelegramRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  appBuildError: z.boolean(),
  databaseBackup: z.boolean(),
  dokployRestart: z.boolean(),
  name: z.string(),
  appDeploy: z.boolean(),
  dockerCleanup: z.boolean(),
  botToken: z.string(),
  chatId: z.string(),
});

/** @internal */
export type NotificationCreateTelegramRequest$Outbound = {
  appBuildError: boolean;
  databaseBackup: boolean;
  dokployRestart: boolean;
  name: string;
  appDeploy: boolean;
  dockerCleanup: boolean;
  botToken: string;
  chatId: string;
};

/** @internal */
export const NotificationCreateTelegramRequest$outboundSchema: z.ZodType<
  NotificationCreateTelegramRequest$Outbound,
  z.ZodTypeDef,
  NotificationCreateTelegramRequest
> = z.object({
  appBuildError: z.boolean(),
  databaseBackup: z.boolean(),
  dokployRestart: z.boolean(),
  name: z.string(),
  appDeploy: z.boolean(),
  dockerCleanup: z.boolean(),
  botToken: z.string(),
  chatId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationCreateTelegramRequest$ {
  /** @deprecated use `NotificationCreateTelegramRequest$inboundSchema` instead. */
  export const inboundSchema = NotificationCreateTelegramRequest$inboundSchema;
  /** @deprecated use `NotificationCreateTelegramRequest$outboundSchema` instead. */
  export const outboundSchema =
    NotificationCreateTelegramRequest$outboundSchema;
  /** @deprecated use `NotificationCreateTelegramRequest$Outbound` instead. */
  export type Outbound = NotificationCreateTelegramRequest$Outbound;
}

export function notificationCreateTelegramRequestToJSON(
  notificationCreateTelegramRequest: NotificationCreateTelegramRequest,
): string {
  return JSON.stringify(
    NotificationCreateTelegramRequest$outboundSchema.parse(
      notificationCreateTelegramRequest,
    ),
  );
}

export function notificationCreateTelegramRequestFromJSON(
  jsonString: string,
): SafeParseResult<NotificationCreateTelegramRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationCreateTelegramRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationCreateTelegramRequest' from JSON`,
  );
}
