/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PortDeleteRequest = {
  portId: string;
};

/** @internal */
export const PortDeleteRequest$inboundSchema: z.ZodType<
  PortDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  portId: z.string(),
});

/** @internal */
export type PortDeleteRequest$Outbound = {
  portId: string;
};

/** @internal */
export const PortDeleteRequest$outboundSchema: z.ZodType<
  PortDeleteRequest$Outbound,
  z.ZodTypeDef,
  PortDeleteRequest
> = z.object({
  portId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PortDeleteRequest$ {
  /** @deprecated use `PortDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = PortDeleteRequest$inboundSchema;
  /** @deprecated use `PortDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = PortDeleteRequest$outboundSchema;
  /** @deprecated use `PortDeleteRequest$Outbound` instead. */
  export type Outbound = PortDeleteRequest$Outbound;
}

export function portDeleteRequestToJSON(
  portDeleteRequest: PortDeleteRequest,
): string {
  return JSON.stringify(
    PortDeleteRequest$outboundSchema.parse(portDeleteRequest),
  );
}

export function portDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<PortDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortDeleteRequest' from JSON`,
  );
}
