/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PortCreateProtocol = {
  Tcp: "tcp",
  Udp: "udp",
} as const;
export type PortCreateProtocol = ClosedEnum<typeof PortCreateProtocol>;

export type PortCreateRequest = {
  publishedPort: number;
  targetPort: number;
  protocol?: PortCreateProtocol | undefined;
  applicationId: string;
};

/** @internal */
export const PortCreateProtocol$inboundSchema: z.ZodNativeEnum<
  typeof PortCreateProtocol
> = z.nativeEnum(PortCreateProtocol);

/** @internal */
export const PortCreateProtocol$outboundSchema: z.ZodNativeEnum<
  typeof PortCreateProtocol
> = PortCreateProtocol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PortCreateProtocol$ {
  /** @deprecated use `PortCreateProtocol$inboundSchema` instead. */
  export const inboundSchema = PortCreateProtocol$inboundSchema;
  /** @deprecated use `PortCreateProtocol$outboundSchema` instead. */
  export const outboundSchema = PortCreateProtocol$outboundSchema;
}

/** @internal */
export const PortCreateRequest$inboundSchema: z.ZodType<
  PortCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  publishedPort: z.number(),
  targetPort: z.number(),
  protocol: PortCreateProtocol$inboundSchema.default("tcp"),
  applicationId: z.string(),
});

/** @internal */
export type PortCreateRequest$Outbound = {
  publishedPort: number;
  targetPort: number;
  protocol: string;
  applicationId: string;
};

/** @internal */
export const PortCreateRequest$outboundSchema: z.ZodType<
  PortCreateRequest$Outbound,
  z.ZodTypeDef,
  PortCreateRequest
> = z.object({
  publishedPort: z.number(),
  targetPort: z.number(),
  protocol: PortCreateProtocol$outboundSchema.default("tcp"),
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PortCreateRequest$ {
  /** @deprecated use `PortCreateRequest$inboundSchema` instead. */
  export const inboundSchema = PortCreateRequest$inboundSchema;
  /** @deprecated use `PortCreateRequest$outboundSchema` instead. */
  export const outboundSchema = PortCreateRequest$outboundSchema;
  /** @deprecated use `PortCreateRequest$Outbound` instead. */
  export type Outbound = PortCreateRequest$Outbound;
}

export function portCreateRequestToJSON(
  portCreateRequest: PortCreateRequest,
): string {
  return JSON.stringify(
    PortCreateRequest$outboundSchema.parse(portCreateRequest),
  );
}

export function portCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PortCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortCreateRequest' from JSON`,
  );
}
