/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PortUpdateProtocol = {
  Tcp: "tcp",
  Udp: "udp",
} as const;
export type PortUpdateProtocol = ClosedEnum<typeof PortUpdateProtocol>;

export type PortUpdateRequest = {
  portId: string;
  publishedPort: number;
  targetPort: number;
  protocol?: PortUpdateProtocol | undefined;
};

/** @internal */
export const PortUpdateProtocol$inboundSchema: z.ZodNativeEnum<
  typeof PortUpdateProtocol
> = z.nativeEnum(PortUpdateProtocol);

/** @internal */
export const PortUpdateProtocol$outboundSchema: z.ZodNativeEnum<
  typeof PortUpdateProtocol
> = PortUpdateProtocol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PortUpdateProtocol$ {
  /** @deprecated use `PortUpdateProtocol$inboundSchema` instead. */
  export const inboundSchema = PortUpdateProtocol$inboundSchema;
  /** @deprecated use `PortUpdateProtocol$outboundSchema` instead. */
  export const outboundSchema = PortUpdateProtocol$outboundSchema;
}

/** @internal */
export const PortUpdateRequest$inboundSchema: z.ZodType<
  PortUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  portId: z.string(),
  publishedPort: z.number(),
  targetPort: z.number(),
  protocol: PortUpdateProtocol$inboundSchema.default("tcp"),
});

/** @internal */
export type PortUpdateRequest$Outbound = {
  portId: string;
  publishedPort: number;
  targetPort: number;
  protocol: string;
};

/** @internal */
export const PortUpdateRequest$outboundSchema: z.ZodType<
  PortUpdateRequest$Outbound,
  z.ZodTypeDef,
  PortUpdateRequest
> = z.object({
  portId: z.string(),
  publishedPort: z.number(),
  targetPort: z.number(),
  protocol: PortUpdateProtocol$outboundSchema.default("tcp"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PortUpdateRequest$ {
  /** @deprecated use `PortUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = PortUpdateRequest$inboundSchema;
  /** @deprecated use `PortUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = PortUpdateRequest$outboundSchema;
  /** @deprecated use `PortUpdateRequest$Outbound` instead. */
  export type Outbound = PortUpdateRequest$Outbound;
}

export function portUpdateRequestToJSON(
  portUpdateRequest: PortUpdateRequest,
): string {
  return JSON.stringify(
    PortUpdateRequest$outboundSchema.parse(portUpdateRequest),
  );
}

export function portUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PortUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortUpdateRequest' from JSON`,
  );
}
