/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PortOneRequest = {
  portId: string;
};

/** @internal */
export const PortOneRequest$inboundSchema: z.ZodType<
  PortOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  portId: z.string(),
});

/** @internal */
export type PortOneRequest$Outbound = {
  portId: string;
};

/** @internal */
export const PortOneRequest$outboundSchema: z.ZodType<
  PortOneRequest$Outbound,
  z.ZodTypeDef,
  PortOneRequest
> = z.object({
  portId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PortOneRequest$ {
  /** @deprecated use `PortOneRequest$inboundSchema` instead. */
  export const inboundSchema = PortOneRequest$inboundSchema;
  /** @deprecated use `PortOneRequest$outboundSchema` instead. */
  export const outboundSchema = PortOneRequest$outboundSchema;
  /** @deprecated use `PortOneRequest$Outbound` instead. */
  export type Outbound = PortOneRequest$Outbound;
}

export function portOneRequestToJSON(portOneRequest: PortOneRequest): string {
  return JSON.stringify(PortOneRequest$outboundSchema.parse(portOneRequest));
}

export function portOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<PortOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortOneRequest' from JSON`,
  );
}
