/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresDeployRequest = {
  postgresId: string;
};

/** @internal */
export const PostgresDeployRequest$inboundSchema: z.ZodType<
  PostgresDeployRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
});

/** @internal */
export type PostgresDeployRequest$Outbound = {
  postgresId: string;
};

/** @internal */
export const PostgresDeployRequest$outboundSchema: z.ZodType<
  PostgresDeployRequest$Outbound,
  z.ZodTypeDef,
  PostgresDeployRequest
> = z.object({
  postgresId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresDeployRequest$ {
  /** @deprecated use `PostgresDeployRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresDeployRequest$inboundSchema;
  /** @deprecated use `PostgresDeployRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresDeployRequest$outboundSchema;
  /** @deprecated use `PostgresDeployRequest$Outbound` instead. */
  export type Outbound = PostgresDeployRequest$Outbound;
}

export function postgresDeployRequestToJSON(
  postgresDeployRequest: PostgresDeployRequest,
): string {
  return JSON.stringify(
    PostgresDeployRequest$outboundSchema.parse(postgresDeployRequest),
  );
}

export function postgresDeployRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployRequest' from JSON`,
  );
}
