/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresRemoveRequest = {
  postgresId: string;
};

/** @internal */
export const PostgresRemoveRequest$inboundSchema: z.ZodType<
  PostgresRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
});

/** @internal */
export type PostgresRemoveRequest$Outbound = {
  postgresId: string;
};

/** @internal */
export const PostgresRemoveRequest$outboundSchema: z.ZodType<
  PostgresRemoveRequest$Outbound,
  z.ZodTypeDef,
  PostgresRemoveRequest
> = z.object({
  postgresId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresRemoveRequest$ {
  /** @deprecated use `PostgresRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresRemoveRequest$inboundSchema;
  /** @deprecated use `PostgresRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresRemoveRequest$outboundSchema;
  /** @deprecated use `PostgresRemoveRequest$Outbound` instead. */
  export type Outbound = PostgresRemoveRequest$Outbound;
}

export function postgresRemoveRequestToJSON(
  postgresRemoveRequest: PostgresRemoveRequest,
): string {
  return JSON.stringify(
    PostgresRemoveRequest$outboundSchema.parse(postgresRemoveRequest),
  );
}

export function postgresRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresRemoveRequest' from JSON`,
  );
}
