/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresCreateRequest = {
  name: string;
  appName: string;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  dockerImage?: string | undefined;
  projectId: string;
  description?: string | null | undefined;
  serverId?: string | null | undefined;
};

/** @internal */
export const PostgresCreateRequest$inboundSchema: z.ZodType<
  PostgresCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  appName: z.string(),
  databaseName: z.string(),
  databaseUser: z.string(),
  databasePassword: z.string(),
  dockerImage: z.string().default("postgres:15"),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  serverId: z.nullable(z.string()).optional(),
});

/** @internal */
export type PostgresCreateRequest$Outbound = {
  name: string;
  appName: string;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  dockerImage: string;
  projectId: string;
  description?: string | null | undefined;
  serverId?: string | null | undefined;
};

/** @internal */
export const PostgresCreateRequest$outboundSchema: z.ZodType<
  PostgresCreateRequest$Outbound,
  z.ZodTypeDef,
  PostgresCreateRequest
> = z.object({
  name: z.string(),
  appName: z.string(),
  databaseName: z.string(),
  databaseUser: z.string(),
  databasePassword: z.string(),
  dockerImage: z.string().default("postgres:15"),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  serverId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresCreateRequest$ {
  /** @deprecated use `PostgresCreateRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresCreateRequest$inboundSchema;
  /** @deprecated use `PostgresCreateRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresCreateRequest$outboundSchema;
  /** @deprecated use `PostgresCreateRequest$Outbound` instead. */
  export type Outbound = PostgresCreateRequest$Outbound;
}

export function postgresCreateRequestToJSON(
  postgresCreateRequest: PostgresCreateRequest,
): string {
  return JSON.stringify(
    PostgresCreateRequest$outboundSchema.parse(postgresCreateRequest),
  );
}

export function postgresCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresCreateRequest' from JSON`,
  );
}
