/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PostgresUpdateApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type PostgresUpdateApplicationStatus = ClosedEnum<
  typeof PostgresUpdateApplicationStatus
>;

export type PostgresUpdateRequest = {
  postgresId: string;
  name?: string | undefined;
  appName?: string | undefined;
  databaseName?: string | undefined;
  databaseUser?: string | undefined;
  databasePassword?: string | undefined;
  description?: string | null | undefined;
  dockerImage?: string | undefined;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  externalPort?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  applicationStatus?: PostgresUpdateApplicationStatus | undefined;
  createdAt?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const PostgresUpdateApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof PostgresUpdateApplicationStatus
> = z.nativeEnum(PostgresUpdateApplicationStatus);

/** @internal */
export const PostgresUpdateApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof PostgresUpdateApplicationStatus
> = PostgresUpdateApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresUpdateApplicationStatus$ {
  /** @deprecated use `PostgresUpdateApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = PostgresUpdateApplicationStatus$inboundSchema;
  /** @deprecated use `PostgresUpdateApplicationStatus$outboundSchema` instead. */
  export const outboundSchema = PostgresUpdateApplicationStatus$outboundSchema;
}

/** @internal */
export const PostgresUpdateRequest$inboundSchema: z.ZodType<
  PostgresUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  databaseName: z.string().optional(),
  databaseUser: z.string().optional(),
  databasePassword: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  dockerImage: z.string().default("postgres:15"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  applicationStatus: PostgresUpdateApplicationStatus$inboundSchema.optional(),
  createdAt: z.string().optional(),
  projectId: z.string().optional(),
});

/** @internal */
export type PostgresUpdateRequest$Outbound = {
  postgresId: string;
  name?: string | undefined;
  appName?: string | undefined;
  databaseName?: string | undefined;
  databaseUser?: string | undefined;
  databasePassword?: string | undefined;
  description?: string | null | undefined;
  dockerImage: string;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  externalPort?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  applicationStatus?: string | undefined;
  createdAt?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const PostgresUpdateRequest$outboundSchema: z.ZodType<
  PostgresUpdateRequest$Outbound,
  z.ZodTypeDef,
  PostgresUpdateRequest
> = z.object({
  postgresId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  databaseName: z.string().optional(),
  databaseUser: z.string().optional(),
  databasePassword: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  dockerImage: z.string().default("postgres:15"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  applicationStatus: PostgresUpdateApplicationStatus$outboundSchema.optional(),
  createdAt: z.string().optional(),
  projectId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresUpdateRequest$ {
  /** @deprecated use `PostgresUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresUpdateRequest$inboundSchema;
  /** @deprecated use `PostgresUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresUpdateRequest$outboundSchema;
  /** @deprecated use `PostgresUpdateRequest$Outbound` instead. */
  export type Outbound = PostgresUpdateRequest$Outbound;
}

export function postgresUpdateRequestToJSON(
  postgresUpdateRequest: PostgresUpdateRequest,
): string {
  return JSON.stringify(
    PostgresUpdateRequest$outboundSchema.parse(postgresUpdateRequest),
  );
}

export function postgresUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresUpdateRequest' from JSON`,
  );
}
