/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PostgresChangeStatusApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type PostgresChangeStatusApplicationStatus = ClosedEnum<
  typeof PostgresChangeStatusApplicationStatus
>;

export type PostgresChangeStatusRequest = {
  postgresId: string;
  applicationStatus: PostgresChangeStatusApplicationStatus;
};

/** @internal */
export const PostgresChangeStatusApplicationStatus$inboundSchema:
  z.ZodNativeEnum<typeof PostgresChangeStatusApplicationStatus> = z.nativeEnum(
    PostgresChangeStatusApplicationStatus,
  );

/** @internal */
export const PostgresChangeStatusApplicationStatus$outboundSchema:
  z.ZodNativeEnum<typeof PostgresChangeStatusApplicationStatus> =
    PostgresChangeStatusApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresChangeStatusApplicationStatus$ {
  /** @deprecated use `PostgresChangeStatusApplicationStatus$inboundSchema` instead. */
  export const inboundSchema =
    PostgresChangeStatusApplicationStatus$inboundSchema;
  /** @deprecated use `PostgresChangeStatusApplicationStatus$outboundSchema` instead. */
  export const outboundSchema =
    PostgresChangeStatusApplicationStatus$outboundSchema;
}

/** @internal */
export const PostgresChangeStatusRequest$inboundSchema: z.ZodType<
  PostgresChangeStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
  applicationStatus: PostgresChangeStatusApplicationStatus$inboundSchema,
});

/** @internal */
export type PostgresChangeStatusRequest$Outbound = {
  postgresId: string;
  applicationStatus: string;
};

/** @internal */
export const PostgresChangeStatusRequest$outboundSchema: z.ZodType<
  PostgresChangeStatusRequest$Outbound,
  z.ZodTypeDef,
  PostgresChangeStatusRequest
> = z.object({
  postgresId: z.string(),
  applicationStatus: PostgresChangeStatusApplicationStatus$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresChangeStatusRequest$ {
  /** @deprecated use `PostgresChangeStatusRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresChangeStatusRequest$inboundSchema;
  /** @deprecated use `PostgresChangeStatusRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresChangeStatusRequest$outboundSchema;
  /** @deprecated use `PostgresChangeStatusRequest$Outbound` instead. */
  export type Outbound = PostgresChangeStatusRequest$Outbound;
}

export function postgresChangeStatusRequestToJSON(
  postgresChangeStatusRequest: PostgresChangeStatusRequest,
): string {
  return JSON.stringify(
    PostgresChangeStatusRequest$outboundSchema.parse(
      postgresChangeStatusRequest,
    ),
  );
}

export function postgresChangeStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusRequest' from JSON`,
  );
}
