/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresStartRequest = {
  postgresId: string;
};

/** @internal */
export const PostgresStartRequest$inboundSchema: z.ZodType<
  PostgresStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
});

/** @internal */
export type PostgresStartRequest$Outbound = {
  postgresId: string;
};

/** @internal */
export const PostgresStartRequest$outboundSchema: z.ZodType<
  PostgresStartRequest$Outbound,
  z.ZodTypeDef,
  PostgresStartRequest
> = z.object({
  postgresId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresStartRequest$ {
  /** @deprecated use `PostgresStartRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresStartRequest$inboundSchema;
  /** @deprecated use `PostgresStartRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresStartRequest$outboundSchema;
  /** @deprecated use `PostgresStartRequest$Outbound` instead. */
  export type Outbound = PostgresStartRequest$Outbound;
}

export function postgresStartRequestToJSON(
  postgresStartRequest: PostgresStartRequest,
): string {
  return JSON.stringify(
    PostgresStartRequest$outboundSchema.parse(postgresStartRequest),
  );
}

export function postgresStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresStartRequest' from JSON`,
  );
}
