/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresReloadRequest = {
  postgresId: string;
  appName: string;
};

/** @internal */
export const PostgresReloadRequest$inboundSchema: z.ZodType<
  PostgresReloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
  appName: z.string(),
});

/** @internal */
export type PostgresReloadRequest$Outbound = {
  postgresId: string;
  appName: string;
};

/** @internal */
export const PostgresReloadRequest$outboundSchema: z.ZodType<
  PostgresReloadRequest$Outbound,
  z.ZodTypeDef,
  PostgresReloadRequest
> = z.object({
  postgresId: z.string(),
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresReloadRequest$ {
  /** @deprecated use `PostgresReloadRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresReloadRequest$inboundSchema;
  /** @deprecated use `PostgresReloadRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresReloadRequest$outboundSchema;
  /** @deprecated use `PostgresReloadRequest$Outbound` instead. */
  export type Outbound = PostgresReloadRequest$Outbound;
}

export function postgresReloadRequestToJSON(
  postgresReloadRequest: PostgresReloadRequest,
): string {
  return JSON.stringify(
    PostgresReloadRequest$outboundSchema.parse(postgresReloadRequest),
  );
}

export function postgresReloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresReloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresReloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresReloadRequest' from JSON`,
  );
}
