/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresOneRequest = {
  postgresId: string;
};

/** @internal */
export const PostgresOneRequest$inboundSchema: z.ZodType<
  PostgresOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
});

/** @internal */
export type PostgresOneRequest$Outbound = {
  postgresId: string;
};

/** @internal */
export const PostgresOneRequest$outboundSchema: z.ZodType<
  PostgresOneRequest$Outbound,
  z.ZodTypeDef,
  PostgresOneRequest
> = z.object({
  postgresId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresOneRequest$ {
  /** @deprecated use `PostgresOneRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresOneRequest$inboundSchema;
  /** @deprecated use `PostgresOneRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresOneRequest$outboundSchema;
  /** @deprecated use `PostgresOneRequest$Outbound` instead. */
  export type Outbound = PostgresOneRequest$Outbound;
}

export function postgresOneRequestToJSON(
  postgresOneRequest: PostgresOneRequest,
): string {
  return JSON.stringify(
    PostgresOneRequest$outboundSchema.parse(postgresOneRequest),
  );
}

export function postgresOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresOneRequest' from JSON`,
  );
}
