/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostgresStopRequest = {
  postgresId: string;
};

/** @internal */
export const PostgresStopRequest$inboundSchema: z.ZodType<
  PostgresStopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgresId: z.string(),
});

/** @internal */
export type PostgresStopRequest$Outbound = {
  postgresId: string;
};

/** @internal */
export const PostgresStopRequest$outboundSchema: z.ZodType<
  PostgresStopRequest$Outbound,
  z.ZodTypeDef,
  PostgresStopRequest
> = z.object({
  postgresId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostgresStopRequest$ {
  /** @deprecated use `PostgresStopRequest$inboundSchema` instead. */
  export const inboundSchema = PostgresStopRequest$inboundSchema;
  /** @deprecated use `PostgresStopRequest$outboundSchema` instead. */
  export const outboundSchema = PostgresStopRequest$outboundSchema;
  /** @deprecated use `PostgresStopRequest$Outbound` instead. */
  export type Outbound = PostgresStopRequest$Outbound;
}

export function postgresStopRequestToJSON(
  postgresStopRequest: PostgresStopRequest,
): string {
  return JSON.stringify(
    PostgresStopRequest$outboundSchema.parse(postgresStopRequest),
  );
}

export function postgresStopRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostgresStopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresStopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresStopRequest' from JSON`,
  );
}
