/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ProjectOneRequest = {
  projectId: string;
};

/** @internal */
export const ProjectOneRequest$inboundSchema: z.ZodType<
  ProjectOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectId: z.string(),
});

/** @internal */
export type ProjectOneRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const ProjectOneRequest$outboundSchema: z.ZodType<
  ProjectOneRequest$Outbound,
  z.ZodTypeDef,
  ProjectOneRequest
> = z.object({
  projectId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectOneRequest$ {
  /** @deprecated use `ProjectOneRequest$inboundSchema` instead. */
  export const inboundSchema = ProjectOneRequest$inboundSchema;
  /** @deprecated use `ProjectOneRequest$outboundSchema` instead. */
  export const outboundSchema = ProjectOneRequest$outboundSchema;
  /** @deprecated use `ProjectOneRequest$Outbound` instead. */
  export type Outbound = ProjectOneRequest$Outbound;
}

export function projectOneRequestToJSON(
  projectOneRequest: ProjectOneRequest,
): string {
  return JSON.stringify(
    ProjectOneRequest$outboundSchema.parse(projectOneRequest),
  );
}

export function projectOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<ProjectOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProjectOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProjectOneRequest' from JSON`,
  );
}
