/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ProjectRemoveRequest = {
  projectId: string;
};

/** @internal */
export const ProjectRemoveRequest$inboundSchema: z.ZodType<
  ProjectRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectId: z.string(),
});

/** @internal */
export type ProjectRemoveRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const ProjectRemoveRequest$outboundSchema: z.ZodType<
  ProjectRemoveRequest$Outbound,
  z.ZodTypeDef,
  ProjectRemoveRequest
> = z.object({
  projectId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectRemoveRequest$ {
  /** @deprecated use `ProjectRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = ProjectRemoveRequest$inboundSchema;
  /** @deprecated use `ProjectRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = ProjectRemoveRequest$outboundSchema;
  /** @deprecated use `ProjectRemoveRequest$Outbound` instead. */
  export type Outbound = ProjectRemoveRequest$Outbound;
}

export function projectRemoveRequestToJSON(
  projectRemoveRequest: ProjectRemoveRequest,
): string {
  return JSON.stringify(
    ProjectRemoveRequest$outboundSchema.parse(projectRemoveRequest),
  );
}

export function projectRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<ProjectRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProjectRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProjectRemoveRequest' from JSON`,
  );
}
