/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisReloadRequest = {
  redisId: string;
  appName: string;
};

/** @internal */
export const RedisReloadRequest$inboundSchema: z.ZodType<
  RedisReloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
  appName: z.string(),
});

/** @internal */
export type RedisReloadRequest$Outbound = {
  redisId: string;
  appName: string;
};

/** @internal */
export const RedisReloadRequest$outboundSchema: z.ZodType<
  RedisReloadRequest$Outbound,
  z.ZodTypeDef,
  RedisReloadRequest
> = z.object({
  redisId: z.string(),
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisReloadRequest$ {
  /** @deprecated use `RedisReloadRequest$inboundSchema` instead. */
  export const inboundSchema = RedisReloadRequest$inboundSchema;
  /** @deprecated use `RedisReloadRequest$outboundSchema` instead. */
  export const outboundSchema = RedisReloadRequest$outboundSchema;
  /** @deprecated use `RedisReloadRequest$Outbound` instead. */
  export type Outbound = RedisReloadRequest$Outbound;
}

export function redisReloadRequestToJSON(
  redisReloadRequest: RedisReloadRequest,
): string {
  return JSON.stringify(
    RedisReloadRequest$outboundSchema.parse(redisReloadRequest),
  );
}

export function redisReloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisReloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisReloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisReloadRequest' from JSON`,
  );
}
