/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedirectsOneRequest = {
  redirectId: string;
};

/** @internal */
export const RedirectsOneRequest$inboundSchema: z.ZodType<
  RedirectsOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redirectId: z.string(),
});

/** @internal */
export type RedirectsOneRequest$Outbound = {
  redirectId: string;
};

/** @internal */
export const RedirectsOneRequest$outboundSchema: z.ZodType<
  RedirectsOneRequest$Outbound,
  z.ZodTypeDef,
  RedirectsOneRequest
> = z.object({
  redirectId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedirectsOneRequest$ {
  /** @deprecated use `RedirectsOneRequest$inboundSchema` instead. */
  export const inboundSchema = RedirectsOneRequest$inboundSchema;
  /** @deprecated use `RedirectsOneRequest$outboundSchema` instead. */
  export const outboundSchema = RedirectsOneRequest$outboundSchema;
  /** @deprecated use `RedirectsOneRequest$Outbound` instead. */
  export type Outbound = RedirectsOneRequest$Outbound;
}

export function redirectsOneRequestToJSON(
  redirectsOneRequest: RedirectsOneRequest,
): string {
  return JSON.stringify(
    RedirectsOneRequest$outboundSchema.parse(redirectsOneRequest),
  );
}

export function redirectsOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedirectsOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedirectsOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedirectsOneRequest' from JSON`,
  );
}
