/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedirectsCreateRequest = {
  regex: string;
  replacement: string;
  permanent: boolean;
  applicationId: string;
};

/** @internal */
export const RedirectsCreateRequest$inboundSchema: z.ZodType<
  RedirectsCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  regex: z.string(),
  replacement: z.string(),
  permanent: z.boolean(),
  applicationId: z.string(),
});

/** @internal */
export type RedirectsCreateRequest$Outbound = {
  regex: string;
  replacement: string;
  permanent: boolean;
  applicationId: string;
};

/** @internal */
export const RedirectsCreateRequest$outboundSchema: z.ZodType<
  RedirectsCreateRequest$Outbound,
  z.ZodTypeDef,
  RedirectsCreateRequest
> = z.object({
  regex: z.string(),
  replacement: z.string(),
  permanent: z.boolean(),
  applicationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedirectsCreateRequest$ {
  /** @deprecated use `RedirectsCreateRequest$inboundSchema` instead. */
  export const inboundSchema = RedirectsCreateRequest$inboundSchema;
  /** @deprecated use `RedirectsCreateRequest$outboundSchema` instead. */
  export const outboundSchema = RedirectsCreateRequest$outboundSchema;
  /** @deprecated use `RedirectsCreateRequest$Outbound` instead. */
  export type Outbound = RedirectsCreateRequest$Outbound;
}

export function redirectsCreateRequestToJSON(
  redirectsCreateRequest: RedirectsCreateRequest,
): string {
  return JSON.stringify(
    RedirectsCreateRequest$outboundSchema.parse(redirectsCreateRequest),
  );
}

export function redirectsCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedirectsCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedirectsCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedirectsCreateRequest' from JSON`,
  );
}
