/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisDeployRequest = {
  redisId: string;
};

/** @internal */
export const RedisDeployRequest$inboundSchema: z.ZodType<
  RedisDeployRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
});

/** @internal */
export type RedisDeployRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisDeployRequest$outboundSchema: z.ZodType<
  RedisDeployRequest$Outbound,
  z.ZodTypeDef,
  RedisDeployRequest
> = z.object({
  redisId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisDeployRequest$ {
  /** @deprecated use `RedisDeployRequest$inboundSchema` instead. */
  export const inboundSchema = RedisDeployRequest$inboundSchema;
  /** @deprecated use `RedisDeployRequest$outboundSchema` instead. */
  export const outboundSchema = RedisDeployRequest$outboundSchema;
  /** @deprecated use `RedisDeployRequest$Outbound` instead. */
  export type Outbound = RedisDeployRequest$Outbound;
}

export function redisDeployRequestToJSON(
  redisDeployRequest: RedisDeployRequest,
): string {
  return JSON.stringify(
    RedisDeployRequest$outboundSchema.parse(redisDeployRequest),
  );
}

export function redisDeployRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployRequest' from JSON`,
  );
}
