/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedirectsDeleteRequest = {
  redirectId: string;
};

/** @internal */
export const RedirectsDeleteRequest$inboundSchema: z.ZodType<
  RedirectsDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redirectId: z.string(),
});

/** @internal */
export type RedirectsDeleteRequest$Outbound = {
  redirectId: string;
};

/** @internal */
export const RedirectsDeleteRequest$outboundSchema: z.ZodType<
  RedirectsDeleteRequest$Outbound,
  z.ZodTypeDef,
  RedirectsDeleteRequest
> = z.object({
  redirectId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedirectsDeleteRequest$ {
  /** @deprecated use `RedirectsDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = RedirectsDeleteRequest$inboundSchema;
  /** @deprecated use `RedirectsDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = RedirectsDeleteRequest$outboundSchema;
  /** @deprecated use `RedirectsDeleteRequest$Outbound` instead. */
  export type Outbound = RedirectsDeleteRequest$Outbound;
}

export function redirectsDeleteRequestToJSON(
  redirectsDeleteRequest: RedirectsDeleteRequest,
): string {
  return JSON.stringify(
    RedirectsDeleteRequest$outboundSchema.parse(redirectsDeleteRequest),
  );
}

export function redirectsDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedirectsDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedirectsDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedirectsDeleteRequest' from JSON`,
  );
}
