/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedirectsUpdateRequest = {
  redirectId: string;
  regex: string;
  replacement: string;
  permanent: boolean;
};

/** @internal */
export const RedirectsUpdateRequest$inboundSchema: z.ZodType<
  RedirectsUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redirectId: z.string(),
  regex: z.string(),
  replacement: z.string(),
  permanent: z.boolean(),
});

/** @internal */
export type RedirectsUpdateRequest$Outbound = {
  redirectId: string;
  regex: string;
  replacement: string;
  permanent: boolean;
};

/** @internal */
export const RedirectsUpdateRequest$outboundSchema: z.ZodType<
  RedirectsUpdateRequest$Outbound,
  z.ZodTypeDef,
  RedirectsUpdateRequest
> = z.object({
  redirectId: z.string(),
  regex: z.string(),
  replacement: z.string(),
  permanent: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedirectsUpdateRequest$ {
  /** @deprecated use `RedirectsUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = RedirectsUpdateRequest$inboundSchema;
  /** @deprecated use `RedirectsUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = RedirectsUpdateRequest$outboundSchema;
  /** @deprecated use `RedirectsUpdateRequest$Outbound` instead. */
  export type Outbound = RedirectsUpdateRequest$Outbound;
}

export function redirectsUpdateRequestToJSON(
  redirectsUpdateRequest: RedirectsUpdateRequest,
): string {
  return JSON.stringify(
    RedirectsUpdateRequest$outboundSchema.parse(redirectsUpdateRequest),
  );
}

export function redirectsUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedirectsUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedirectsUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedirectsUpdateRequest' from JSON`,
  );
}
