/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const RedisChangeStatusApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type RedisChangeStatusApplicationStatus = ClosedEnum<
  typeof RedisChangeStatusApplicationStatus
>;

export type RedisChangeStatusRequest = {
  redisId: string;
  applicationStatus: RedisChangeStatusApplicationStatus;
};

/** @internal */
export const RedisChangeStatusApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisChangeStatusApplicationStatus
> = z.nativeEnum(RedisChangeStatusApplicationStatus);

/** @internal */
export const RedisChangeStatusApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof RedisChangeStatusApplicationStatus
> = RedisChangeStatusApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisChangeStatusApplicationStatus$ {
  /** @deprecated use `RedisChangeStatusApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = RedisChangeStatusApplicationStatus$inboundSchema;
  /** @deprecated use `RedisChangeStatusApplicationStatus$outboundSchema` instead. */
  export const outboundSchema =
    RedisChangeStatusApplicationStatus$outboundSchema;
}

/** @internal */
export const RedisChangeStatusRequest$inboundSchema: z.ZodType<
  RedisChangeStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
  applicationStatus: RedisChangeStatusApplicationStatus$inboundSchema,
});

/** @internal */
export type RedisChangeStatusRequest$Outbound = {
  redisId: string;
  applicationStatus: string;
};

/** @internal */
export const RedisChangeStatusRequest$outboundSchema: z.ZodType<
  RedisChangeStatusRequest$Outbound,
  z.ZodTypeDef,
  RedisChangeStatusRequest
> = z.object({
  redisId: z.string(),
  applicationStatus: RedisChangeStatusApplicationStatus$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisChangeStatusRequest$ {
  /** @deprecated use `RedisChangeStatusRequest$inboundSchema` instead. */
  export const inboundSchema = RedisChangeStatusRequest$inboundSchema;
  /** @deprecated use `RedisChangeStatusRequest$outboundSchema` instead. */
  export const outboundSchema = RedisChangeStatusRequest$outboundSchema;
  /** @deprecated use `RedisChangeStatusRequest$Outbound` instead. */
  export type Outbound = RedisChangeStatusRequest$Outbound;
}

export function redisChangeStatusRequestToJSON(
  redisChangeStatusRequest: RedisChangeStatusRequest,
): string {
  return JSON.stringify(
    RedisChangeStatusRequest$outboundSchema.parse(redisChangeStatusRequest),
  );
}

export function redisChangeStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisChangeStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisChangeStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisChangeStatusRequest' from JSON`,
  );
}
