/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisStartRequest = {
  redisId: string;
};

/** @internal */
export const RedisStartRequest$inboundSchema: z.ZodType<
  RedisStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
});

/** @internal */
export type RedisStartRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisStartRequest$outboundSchema: z.ZodType<
  RedisStartRequest$Outbound,
  z.ZodTypeDef,
  RedisStartRequest
> = z.object({
  redisId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisStartRequest$ {
  /** @deprecated use `RedisStartRequest$inboundSchema` instead. */
  export const inboundSchema = RedisStartRequest$inboundSchema;
  /** @deprecated use `RedisStartRequest$outboundSchema` instead. */
  export const outboundSchema = RedisStartRequest$outboundSchema;
  /** @deprecated use `RedisStartRequest$Outbound` instead. */
  export type Outbound = RedisStartRequest$Outbound;
}

export function redisStartRequestToJSON(
  redisStartRequest: RedisStartRequest,
): string {
  return JSON.stringify(
    RedisStartRequest$outboundSchema.parse(redisStartRequest),
  );
}

export function redisStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStartRequest' from JSON`,
  );
}
