/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisCreateRequest = {
  name: string;
  appName: string;
  databasePassword: string;
  dockerImage?: string | undefined;
  projectId: string;
  description?: string | null | undefined;
  serverId?: string | null | undefined;
};

/** @internal */
export const RedisCreateRequest$inboundSchema: z.ZodType<
  RedisCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  appName: z.string(),
  databasePassword: z.string(),
  dockerImage: z.string().default("redis:8"),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  serverId: z.nullable(z.string()).optional(),
});

/** @internal */
export type RedisCreateRequest$Outbound = {
  name: string;
  appName: string;
  databasePassword: string;
  dockerImage: string;
  projectId: string;
  description?: string | null | undefined;
  serverId?: string | null | undefined;
};

/** @internal */
export const RedisCreateRequest$outboundSchema: z.ZodType<
  RedisCreateRequest$Outbound,
  z.ZodTypeDef,
  RedisCreateRequest
> = z.object({
  name: z.string(),
  appName: z.string(),
  databasePassword: z.string(),
  dockerImage: z.string().default("redis:8"),
  projectId: z.string(),
  description: z.nullable(z.string()).optional(),
  serverId: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisCreateRequest$ {
  /** @deprecated use `RedisCreateRequest$inboundSchema` instead. */
  export const inboundSchema = RedisCreateRequest$inboundSchema;
  /** @deprecated use `RedisCreateRequest$outboundSchema` instead. */
  export const outboundSchema = RedisCreateRequest$outboundSchema;
  /** @deprecated use `RedisCreateRequest$Outbound` instead. */
  export type Outbound = RedisCreateRequest$Outbound;
}

export function redisCreateRequestToJSON(
  redisCreateRequest: RedisCreateRequest,
): string {
  return JSON.stringify(
    RedisCreateRequest$outboundSchema.parse(redisCreateRequest),
  );
}

export function redisCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisCreateRequest' from JSON`,
  );
}
