/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const RedisUpdateApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type RedisUpdateApplicationStatus = ClosedEnum<
  typeof RedisUpdateApplicationStatus
>;

export type RedisUpdateRequest = {
  redisId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  databasePassword?: string | undefined;
  dockerImage?: string | undefined;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  externalPort?: number | null | undefined;
  createdAt?: string | undefined;
  applicationStatus?: RedisUpdateApplicationStatus | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const RedisUpdateApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisUpdateApplicationStatus
> = z.nativeEnum(RedisUpdateApplicationStatus);

/** @internal */
export const RedisUpdateApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof RedisUpdateApplicationStatus
> = RedisUpdateApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisUpdateApplicationStatus$ {
  /** @deprecated use `RedisUpdateApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = RedisUpdateApplicationStatus$inboundSchema;
  /** @deprecated use `RedisUpdateApplicationStatus$outboundSchema` instead. */
  export const outboundSchema = RedisUpdateApplicationStatus$outboundSchema;
}

/** @internal */
export const RedisUpdateRequest$inboundSchema: z.ZodType<
  RedisUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  databasePassword: z.string().optional(),
  dockerImage: z.string().default("redis:8"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  createdAt: z.string().optional(),
  applicationStatus: RedisUpdateApplicationStatus$inboundSchema.optional(),
  projectId: z.string().optional(),
});

/** @internal */
export type RedisUpdateRequest$Outbound = {
  redisId: string;
  name?: string | undefined;
  appName?: string | undefined;
  description?: string | null | undefined;
  databasePassword?: string | undefined;
  dockerImage: string;
  command?: string | null | undefined;
  env?: string | null | undefined;
  memoryReservation?: number | null | undefined;
  memoryLimit?: number | null | undefined;
  cpuReservation?: number | null | undefined;
  cpuLimit?: number | null | undefined;
  externalPort?: number | null | undefined;
  createdAt?: string | undefined;
  applicationStatus?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const RedisUpdateRequest$outboundSchema: z.ZodType<
  RedisUpdateRequest$Outbound,
  z.ZodTypeDef,
  RedisUpdateRequest
> = z.object({
  redisId: z.string(),
  name: z.string().optional(),
  appName: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  databasePassword: z.string().optional(),
  dockerImage: z.string().default("redis:8"),
  command: z.nullable(z.string()).optional(),
  env: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.number()).optional(),
  memoryLimit: z.nullable(z.number()).optional(),
  cpuReservation: z.nullable(z.number()).optional(),
  cpuLimit: z.nullable(z.number()).optional(),
  externalPort: z.nullable(z.number()).optional(),
  createdAt: z.string().optional(),
  applicationStatus: RedisUpdateApplicationStatus$outboundSchema.optional(),
  projectId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisUpdateRequest$ {
  /** @deprecated use `RedisUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = RedisUpdateRequest$inboundSchema;
  /** @deprecated use `RedisUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = RedisUpdateRequest$outboundSchema;
  /** @deprecated use `RedisUpdateRequest$Outbound` instead. */
  export type Outbound = RedisUpdateRequest$Outbound;
}

export function redisUpdateRequestToJSON(
  redisUpdateRequest: RedisUpdateRequest,
): string {
  return JSON.stringify(
    RedisUpdateRequest$outboundSchema.parse(redisUpdateRequest),
  );
}

export function redisUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisUpdateRequest' from JSON`,
  );
}
