/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisOneRequest = {
  redisId: string;
};

/** @internal */
export const RedisOneRequest$inboundSchema: z.ZodType<
  RedisOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
});

/** @internal */
export type RedisOneRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisOneRequest$outboundSchema: z.ZodType<
  RedisOneRequest$Outbound,
  z.ZodTypeDef,
  RedisOneRequest
> = z.object({
  redisId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisOneRequest$ {
  /** @deprecated use `RedisOneRequest$inboundSchema` instead. */
  export const inboundSchema = RedisOneRequest$inboundSchema;
  /** @deprecated use `RedisOneRequest$outboundSchema` instead. */
  export const outboundSchema = RedisOneRequest$outboundSchema;
  /** @deprecated use `RedisOneRequest$Outbound` instead. */
  export type Outbound = RedisOneRequest$Outbound;
}

export function redisOneRequestToJSON(
  redisOneRequest: RedisOneRequest,
): string {
  return JSON.stringify(RedisOneRequest$outboundSchema.parse(redisOneRequest));
}

export function redisOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisOneRequest' from JSON`,
  );
}
