/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisSaveExternalPortRequest = {
  redisId: string;
  externalPort: number | null;
};

/** @internal */
export const RedisSaveExternalPortRequest$inboundSchema: z.ZodType<
  RedisSaveExternalPortRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
  externalPort: z.nullable(z.number()),
});

/** @internal */
export type RedisSaveExternalPortRequest$Outbound = {
  redisId: string;
  externalPort: number | null;
};

/** @internal */
export const RedisSaveExternalPortRequest$outboundSchema: z.ZodType<
  RedisSaveExternalPortRequest$Outbound,
  z.ZodTypeDef,
  RedisSaveExternalPortRequest
> = z.object({
  redisId: z.string(),
  externalPort: z.nullable(z.number()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisSaveExternalPortRequest$ {
  /** @deprecated use `RedisSaveExternalPortRequest$inboundSchema` instead. */
  export const inboundSchema = RedisSaveExternalPortRequest$inboundSchema;
  /** @deprecated use `RedisSaveExternalPortRequest$outboundSchema` instead. */
  export const outboundSchema = RedisSaveExternalPortRequest$outboundSchema;
  /** @deprecated use `RedisSaveExternalPortRequest$Outbound` instead. */
  export type Outbound = RedisSaveExternalPortRequest$Outbound;
}

export function redisSaveExternalPortRequestToJSON(
  redisSaveExternalPortRequest: RedisSaveExternalPortRequest,
): string {
  return JSON.stringify(
    RedisSaveExternalPortRequest$outboundSchema.parse(
      redisSaveExternalPortRequest,
    ),
  );
}

export function redisSaveExternalPortRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisSaveExternalPortRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisSaveExternalPortRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisSaveExternalPortRequest' from JSON`,
  );
}
