/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RedisStopRequest = {
  redisId: string;
};

/** @internal */
export const RedisStopRequest$inboundSchema: z.ZodType<
  RedisStopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  redisId: z.string(),
});

/** @internal */
export type RedisStopRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisStopRequest$outboundSchema: z.ZodType<
  RedisStopRequest$Outbound,
  z.ZodTypeDef,
  RedisStopRequest
> = z.object({
  redisId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedisStopRequest$ {
  /** @deprecated use `RedisStopRequest$inboundSchema` instead. */
  export const inboundSchema = RedisStopRequest$inboundSchema;
  /** @deprecated use `RedisStopRequest$outboundSchema` instead. */
  export const outboundSchema = RedisStopRequest$outboundSchema;
  /** @deprecated use `RedisStopRequest$Outbound` instead. */
  export type Outbound = RedisStopRequest$Outbound;
}

export function redisStopRequestToJSON(
  redisStopRequest: RedisStopRequest,
): string {
  return JSON.stringify(
    RedisStopRequest$outboundSchema.parse(redisStopRequest),
  );
}

export function redisStopRequestFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopRequest' from JSON`,
  );
}
