/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SecurityDeleteRequest = {
  securityId: string;
};

/** @internal */
export const SecurityDeleteRequest$inboundSchema: z.ZodType<
  SecurityDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  securityId: z.string(),
});

/** @internal */
export type SecurityDeleteRequest$Outbound = {
  securityId: string;
};

/** @internal */
export const SecurityDeleteRequest$outboundSchema: z.ZodType<
  SecurityDeleteRequest$Outbound,
  z.ZodTypeDef,
  SecurityDeleteRequest
> = z.object({
  securityId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SecurityDeleteRequest$ {
  /** @deprecated use `SecurityDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = SecurityDeleteRequest$inboundSchema;
  /** @deprecated use `SecurityDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = SecurityDeleteRequest$outboundSchema;
  /** @deprecated use `SecurityDeleteRequest$Outbound` instead. */
  export type Outbound = SecurityDeleteRequest$Outbound;
}

export function securityDeleteRequestToJSON(
  securityDeleteRequest: SecurityDeleteRequest,
): string {
  return JSON.stringify(
    SecurityDeleteRequest$outboundSchema.parse(securityDeleteRequest),
  );
}

export function securityDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<SecurityDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityDeleteRequest' from JSON`,
  );
}
