/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SecurityCreateRequest = {
  applicationId: string;
  username: string;
  password: string;
};

/** @internal */
export const SecurityCreateRequest$inboundSchema: z.ZodType<
  SecurityCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  username: z.string(),
  password: z.string(),
});

/** @internal */
export type SecurityCreateRequest$Outbound = {
  applicationId: string;
  username: string;
  password: string;
};

/** @internal */
export const SecurityCreateRequest$outboundSchema: z.ZodType<
  SecurityCreateRequest$Outbound,
  z.ZodTypeDef,
  SecurityCreateRequest
> = z.object({
  applicationId: z.string(),
  username: z.string(),
  password: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SecurityCreateRequest$ {
  /** @deprecated use `SecurityCreateRequest$inboundSchema` instead. */
  export const inboundSchema = SecurityCreateRequest$inboundSchema;
  /** @deprecated use `SecurityCreateRequest$outboundSchema` instead. */
  export const outboundSchema = SecurityCreateRequest$outboundSchema;
  /** @deprecated use `SecurityCreateRequest$Outbound` instead. */
  export type Outbound = SecurityCreateRequest$Outbound;
}

export function securityCreateRequestToJSON(
  securityCreateRequest: SecurityCreateRequest,
): string {
  return JSON.stringify(
    SecurityCreateRequest$outboundSchema.parse(securityCreateRequest),
  );
}

export function securityCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<SecurityCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityCreateRequest' from JSON`,
  );
}
