/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SecurityUpdateRequest = {
  securityId: string;
  username: string;
  password: string;
};

/** @internal */
export const SecurityUpdateRequest$inboundSchema: z.ZodType<
  SecurityUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  securityId: z.string(),
  username: z.string(),
  password: z.string(),
});

/** @internal */
export type SecurityUpdateRequest$Outbound = {
  securityId: string;
  username: string;
  password: string;
};

/** @internal */
export const SecurityUpdateRequest$outboundSchema: z.ZodType<
  SecurityUpdateRequest$Outbound,
  z.ZodTypeDef,
  SecurityUpdateRequest
> = z.object({
  securityId: z.string(),
  username: z.string(),
  password: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SecurityUpdateRequest$ {
  /** @deprecated use `SecurityUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = SecurityUpdateRequest$inboundSchema;
  /** @deprecated use `SecurityUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = SecurityUpdateRequest$outboundSchema;
  /** @deprecated use `SecurityUpdateRequest$Outbound` instead. */
  export type Outbound = SecurityUpdateRequest$Outbound;
}

export function securityUpdateRequestToJSON(
  securityUpdateRequest: SecurityUpdateRequest,
): string {
  return JSON.stringify(
    SecurityUpdateRequest$outboundSchema.parse(securityUpdateRequest),
  );
}

export function securityUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<SecurityUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityUpdateRequest' from JSON`,
  );
}
