/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SecurityOneRequest = {
  securityId: string;
};

/** @internal */
export const SecurityOneRequest$inboundSchema: z.ZodType<
  SecurityOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  securityId: z.string(),
});

/** @internal */
export type SecurityOneRequest$Outbound = {
  securityId: string;
};

/** @internal */
export const SecurityOneRequest$outboundSchema: z.ZodType<
  SecurityOneRequest$Outbound,
  z.ZodTypeDef,
  SecurityOneRequest
> = z.object({
  securityId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SecurityOneRequest$ {
  /** @deprecated use `SecurityOneRequest$inboundSchema` instead. */
  export const inboundSchema = SecurityOneRequest$inboundSchema;
  /** @deprecated use `SecurityOneRequest$outboundSchema` instead. */
  export const outboundSchema = SecurityOneRequest$outboundSchema;
  /** @deprecated use `SecurityOneRequest$Outbound` instead. */
  export type Outbound = SecurityOneRequest$Outbound;
}

export function securityOneRequestToJSON(
  securityOneRequest: SecurityOneRequest,
): string {
  return JSON.stringify(
    SecurityOneRequest$outboundSchema.parse(securityOneRequest),
  );
}

export function securityOneRequestFromJSON(
  jsonString: string,
): SafeParseResult<SecurityOneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityOneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityOneRequest' from JSON`,
  );
}
