/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServerUpdateRequest = {
  name: string;
  description?: string | null | undefined;
  serverId: string;
  ipAddress: string;
  port: number;
  username: string;
  sshKeyId: string | null;
};

/** @internal */
export const ServerUpdateRequest$inboundSchema: z.ZodType<
  ServerUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  serverId: z.string(),
  ipAddress: z.string(),
  port: z.number(),
  username: z.string(),
  sshKeyId: z.nullable(z.string()),
});

/** @internal */
export type ServerUpdateRequest$Outbound = {
  name: string;
  description?: string | null | undefined;
  serverId: string;
  ipAddress: string;
  port: number;
  username: string;
  sshKeyId: string | null;
};

/** @internal */
export const ServerUpdateRequest$outboundSchema: z.ZodType<
  ServerUpdateRequest$Outbound,
  z.ZodTypeDef,
  ServerUpdateRequest
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  serverId: z.string(),
  ipAddress: z.string(),
  port: z.number(),
  username: z.string(),
  sshKeyId: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServerUpdateRequest$ {
  /** @deprecated use `ServerUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = ServerUpdateRequest$inboundSchema;
  /** @deprecated use `ServerUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = ServerUpdateRequest$outboundSchema;
  /** @deprecated use `ServerUpdateRequest$Outbound` instead. */
  export type Outbound = ServerUpdateRequest$Outbound;
}

export function serverUpdateRequestToJSON(
  serverUpdateRequest: ServerUpdateRequest,
): string {
  return JSON.stringify(
    ServerUpdateRequest$outboundSchema.parse(serverUpdateRequest),
  );
}

export function serverUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ServerUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerUpdateRequest' from JSON`,
  );
}
