/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SettingsToggleLogRotateRequest = {
  enable: boolean;
};

/** @internal */
export const SettingsToggleLogRotateRequest$inboundSchema: z.ZodType<
  SettingsToggleLogRotateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  enable: z.boolean(),
});

/** @internal */
export type SettingsToggleLogRotateRequest$Outbound = {
  enable: boolean;
};

/** @internal */
export const SettingsToggleLogRotateRequest$outboundSchema: z.ZodType<
  SettingsToggleLogRotateRequest$Outbound,
  z.ZodTypeDef,
  SettingsToggleLogRotateRequest
> = z.object({
  enable: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SettingsToggleLogRotateRequest$ {
  /** @deprecated use `SettingsToggleLogRotateRequest$inboundSchema` instead. */
  export const inboundSchema = SettingsToggleLogRotateRequest$inboundSchema;
  /** @deprecated use `SettingsToggleLogRotateRequest$outboundSchema` instead. */
  export const outboundSchema = SettingsToggleLogRotateRequest$outboundSchema;
  /** @deprecated use `SettingsToggleLogRotateRequest$Outbound` instead. */
  export type Outbound = SettingsToggleLogRotateRequest$Outbound;
}

export function settingsToggleLogRotateRequestToJSON(
  settingsToggleLogRotateRequest: SettingsToggleLogRotateRequest,
): string {
  return JSON.stringify(
    SettingsToggleLogRotateRequest$outboundSchema.parse(
      settingsToggleLogRotateRequest,
    ),
  );
}

export function settingsToggleLogRotateRequestFromJSON(
  jsonString: string,
): SafeParseResult<SettingsToggleLogRotateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettingsToggleLogRotateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettingsToggleLogRotateRequest' from JSON`,
  );
}
