/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserByAuthIdRequest = {
  authId: string;
};

/** @internal */
export const UserByAuthIdRequest$inboundSchema: z.ZodType<
  UserByAuthIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  authId: z.string(),
});

/** @internal */
export type UserByAuthIdRequest$Outbound = {
  authId: string;
};

/** @internal */
export const UserByAuthIdRequest$outboundSchema: z.ZodType<
  UserByAuthIdRequest$Outbound,
  z.ZodTypeDef,
  UserByAuthIdRequest
> = z.object({
  authId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserByAuthIdRequest$ {
  /** @deprecated use `UserByAuthIdRequest$inboundSchema` instead. */
  export const inboundSchema = UserByAuthIdRequest$inboundSchema;
  /** @deprecated use `UserByAuthIdRequest$outboundSchema` instead. */
  export const outboundSchema = UserByAuthIdRequest$outboundSchema;
  /** @deprecated use `UserByAuthIdRequest$Outbound` instead. */
  export type Outbound = UserByAuthIdRequest$Outbound;
}

export function userByAuthIdRequestToJSON(
  userByAuthIdRequest: UserByAuthIdRequest,
): string {
  return JSON.stringify(
    UserByAuthIdRequest$outboundSchema.parse(userByAuthIdRequest),
  );
}

export function userByAuthIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<UserByAuthIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserByAuthIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserByAuthIdRequest' from JSON`,
  );
}
