/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserByUserIdRequest = {
  userId: string;
};

/** @internal */
export const UserByUserIdRequest$inboundSchema: z.ZodType<
  UserByUserIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string(),
});

/** @internal */
export type UserByUserIdRequest$Outbound = {
  userId: string;
};

/** @internal */
export const UserByUserIdRequest$outboundSchema: z.ZodType<
  UserByUserIdRequest$Outbound,
  z.ZodTypeDef,
  UserByUserIdRequest
> = z.object({
  userId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserByUserIdRequest$ {
  /** @deprecated use `UserByUserIdRequest$inboundSchema` instead. */
  export const inboundSchema = UserByUserIdRequest$inboundSchema;
  /** @deprecated use `UserByUserIdRequest$outboundSchema` instead. */
  export const outboundSchema = UserByUserIdRequest$outboundSchema;
  /** @deprecated use `UserByUserIdRequest$Outbound` instead. */
  export type Outbound = UserByUserIdRequest$Outbound;
}

export function userByUserIdRequestToJSON(
  userByUserIdRequest: UserByUserIdRequest,
): string {
  return JSON.stringify(
    UserByUserIdRequest$outboundSchema.parse(userByUserIdRequest),
  );
}

export function userByUserIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<UserByUserIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserByUserIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserByUserIdRequest' from JSON`,
  );
}
